### ISSUE TITLE
v0.4.0-beta4 :the same problem as the one at the bottom

### ISSUE THREAD

**Issue by jang9824** [hectorgimenez/koolo#103]
### Details

v0.4.0-beta4
v0.4.0-beta3
v0.4.0-beta2
v0.4.0-beta1
https://youtu.be/esFrD1jyfsA
Like this Same issue with all versions  

Link. The symptoms are the same as the YouTube video

After participating in the character, from the act1 village
I'm not buying potions, I'm buying stamina potions. And I can't proceed in front of the portal and I keep having rejoin errors
  If you start with Act 5, you start hunting after the Stamina potion error, you cannot discard or sell items, and an error occurs where you discard items stored in the warehouse.

He's very good at finding directions when he's hunting

build or releases  I've done both It's the same problem

win10 pro
1280x720 
dia2lod 1.13c

### Version

v0.4.0-beta4

**Comment by Sunnyweeb** [comment]
are u using 1280x720 WINDOW mode?

**Comment by jang9824** [comment]
> 1280x720 WINDOW 모드를 사용하고 있나요?

yes T.T

**Comment by globusV1** [comment]
such as i said previously its wrong positions of clicks
currently bot try stash gold
1. open stash
2. click on deposit button - but offsets are not corrects
3. click on button OK - but message about deposit not showed up thats why he start running
4. bot detect thats gold still in ur inventory and try to click next stash tab button - but stash already closed
etc...

**Comment by Sunnyweeb** [comment]
but how is that possible that only you have those problems? their must be something wrong with the window size or anything like that?

**Comment by jang9824** [comment]
> 하지만 당신만이 그러한 문제를 안고 있다는 것이 어떻게 가능합니까? 창 크기나 그와 유사한 문제가 있는 것 같나요?

![스크린샷(3)](https://github.com/hectorgimenez/koolo/assets/164779982/9e4a46c2-c825-4209-9090-1bf64eb05de1)

**Comment by jang9824** [comment]
> 이전에 말했듯이 클릭 위치가 잘못되었습니다. 현재 봇은 금을 숨겨두려고 합니다.
> 
> 1. 은닉물을 열어라
> 2. 입금 버튼을 클릭하세요. 하지만 오프셋이 정확하지 않습니다.
> 3. 확인 버튼을 클릭하세요. 하지만 입금에 대한 메시지가 표시되지 않아 그가 달리기 시작합니다.
> 4. 봇은 인벤토리에 금이 남아 있음을 감지하고 다음 보관함 탭 버튼을 클릭하려고 합니다. 하지만 보관함은 이미 닫혀 있습니다 
>    .
> 
> 그게 내가 stash.go에서 사용하는 오프셋이야
> 
> ```
> const ( 
>  maxGoldPerStashTab   = 2500000 
>  stashGoldBtnX        = 1005 
>  stashGoldBtnY        = 525 
>  stashGoldBtnConfirmX = 545 
>  stashGoldBtnConfirmY = 385 
> )
> ```
> 
> 원래 그게 그거야
> 
> `stashGoldBtnX = 966`
> 
> 나는 동일한 증상을 가지고 있고 모든 오프셋을 확인한 후에 그것에 대해 말했습니다. 이제 나에게는 봇이 완벽하게 작동합니다.

I tried the store potion coordinate answer, but it didn't work T.T

**Comment by globusV1** [comment]
> but how is that possible that only you have those problems? their must be something wrong with the window size or anything like that?

all that we can do is compare ur window screen with mine and compare difference in positions...
https://ibb.co/ctM7TjP

**Comment by globusV1** [comment]
> > 이전에 말했듯이 클릭 위치가 잘못되었습니다. 현재 봇은 금을 숨겨두려고 합니다.
> > 
> > 1. 은닉물을 열어라
> > 2. 입금 버튼을 클릭하세요. 하지만 오프셋이 정확하지 않습니다.
> > 3. 확인 버튼을 클릭하세요. 하지만 입금에 대한 메시지가 표시되지 않아 그가 달리기 시작합니다.
> > 4. 봇은 인벤토리에 금이 남아 있음을 감지하고 다음 보관함 탭 버튼을 클릭하려고 합니다. 하지만 보관함은 이미 닫혀 있습니다
> >    .
> > 
> > 그게 내가 stash.go에서 사용하는 오프셋이야
> > ```
> > const ( 
> >  maxGoldPerStashTab   = 2500000 
> >  stashGoldBtnX        = 1005 
> >  stashGoldBtnY        = 525 
> >  stashGoldBtnConfirmX = 545 
> >  stashGoldBtnConfirmY = 385 
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 원래 그게 그거야
> > `stashGoldBtnX = 966`
> > 나는 동일한 증상을 가지고 있고 모든 오프셋을 확인한 후에 그것에 대해 말했습니다. 이제 나에게는 봇이 완벽하게 작동합니다.
> 
> I tried the store potion coordinate answer, but it didn't work T.T

store potions not work because u dont have all changes thats i made
full file coordinates.go
```

package ui

import (
	"github.com/hectorgimenez/d2go/pkg/data"
	"github.com/hectorgimenez/d2go/pkg/data/item"
	"github.com/hectorgimenez/koolo/internal/memory"
	"github.com/lxn/win"
)

const (
	itemBoxSize            = 37
	inventoryTopLeftX      = 880
	inventoryTopLeftY      = 365
	topCornerVendorWindowX = 50
	topCornerVendorWindowY = 110
	MercAvatarPositionX    = 36
	MercAvatarPositionY    = 39

	CubeTransmuteBtnX = 220
	CubeTransmuteBtnY = 390

	AnvilCenterX = 272
	AnvilCenterY = 333
	AnvilBtnX    = 360
	AnvilBtnY    = 510

	MainSkillButtonX = 596
	MainSkillButtonY = 693

	SecondarySkillButtonX = 686
	SecondarySkillButtonY = 693

	GambleRefreshButtonX = 360
	GambleRefreshButtonY = 510

	SkillListFirstSkillX = 687
	SkillListFirstSkillY = 590
	SkillListSkillOffset = 45

	FirstMercFromContractorListX = 175
	FirstMercFromContractorListY = 142
)


func GetScreenCoordsForItem(itm data.Item) data.Position {
	switch itm.Location {
	case item.LocationVendor, item.LocationStash, item.LocationSharedStash1, item.LocationSharedStash2, item.LocationSharedStash3:
		x := topCornerVendorWindowX + itm.Position.X*itemBoxSize
		y := topCornerVendorWindowY + itm.Position.Y*itemBoxSize

		return data.Position{X: x, Y: y}
	}

	x := inventoryTopLeftX + itm.Position.X*itemBoxSize
	y := inventoryTopLeftY + itm.Position.Y*itemBoxSize

	return data.Position{X: x, Y: y}
}

func GameWindowScale() float64 {
	dpi := win.GetDpiForWindow(memory.HWND)
	return float64(dpi) / 96.0
}

```

**Comment by Sunnyweeb** [comment]
> > but how is that possible that only you have those problems? their must be something wrong with the window size or anything like that?
> 
> all that we can do is compare ur window screen with mine and compare difference in positions... https://ibb.co/ctM7TjP

this here is mine at 1280x720 https://ibb.co/zhjDFMJ idk but it seems to be different? D:

**Comment by globusV1** [comment]
> > > but how is that possible that only you have those problems? their must be something wrong with the window size or anything like that?
> > 
> > 
> > all that we can do is compare ur window screen with mine and compare difference in positions... https://ibb.co/ctM7TjP
> 
> this here is mine at 1280x720 https://ibb.co/zhjDFMJ idk but it seems to be different? D:

my screen is same 1280x720 
but windows are totally different

**Comment by jang9824** [comment]
> my screen is same 1280x720

my screen is same 1280x720

**Comment by Sunnyweeb** [comment]
> > my screen is same 1280x720
> 
> my screen is same 1280x720

yes but look at inventory, its different

**Comment by jang9824** [comment]
> > > 내 화면은 1280x720과 동일합니다
> > 
> > 
> > 내 화면은 1280x720과 동일합니다
> 
> 네, 하지만 인벤토리를 보세요. 다르죠

![스크린샷(4)](https://github.com/hectorgimenez/koolo/assets/164779982/a600f066-9231-44c3-bbd3-f0b511d36849)

**Comment by jang9824** [comment]
I'll have to reinstall it..

**Comment by Sunnyweeb** [comment]
> I'll have to reinstall it..

try delte your config file from diablo 2 itself, its here:

C:\Users\>your windows user name<\Saved Games\Diablo II Resurrected and then delete "settings.json"

**Comment by jang9824** [comment]
> > 다시 설치해야겠네요..
> 
> 디아블로 2 자체에서 구성 파일을 삭제해 보세요. 해당 파일은 다음과 같습니다.
> 
> C:\Users>Windows 사용자 이름<\Saved Games\Diablo II Resurrented를 선택한 다음 "settings.json"을 삭제하세요.

If the same symptom occurs after reinstallation, I will try deleting the file. D:

**Comment by globusV1** [comment]
i've found the solution to this one

gameplay > accessibility
"large font mode" need to toogle off

**Comment by jang9824** [comment]
> 나는 이것에 대한 해결책을 찾았습니다
> 
> 게임플레이 > 접근성 "큰 글꼴 모드"를 너무 꺼야 함
> 
> 그러면 같은 인벤토리를 갖게 될 것입니다....

Wow, thank you so much!!!! I'm going to install a new Diablo and do this and that
Finally, it's done!!

**Comment by hectorgimenez** [comment]
Was the problem fixed when "large font mode" has been disabled?

**Comment by jang9824** [comment]
> "큰 글꼴 모드"가 비활성화되었을 때 문제가 해결되었습니까?

I've modified this and that, so it's not exactly right, but maybe

**Comment by globusV1** [comment]
> Was the problem fixed when "large font mode" has been disabled?

difference in interface and positions of clicks
https://ibb.co/ctM7TjP
https://ibb.co/zhjDFMJ
