### ISSUE TITLE
Fetching map data... crash

### ISSUE THREAD

**Issue by Crims452** [hectorgimenez/koolo#114]
### Details

I'm unable to get past the character selection screen when the game is loading in. Koolo will crash. seems like it has to do with fetching map data. I made sure to get d2lod 1.13c
time=2024-03-28T13:04:18.615-05:00 level=INFO msg="Waiting for character selection screen..."
time=2024-03-28T13:04:39.442-05:00 level=INFO msg="Character selection screen found"
time=2024-03-28T13:04:39.442-05:00 level=INFO msg="Selecting character..."
time=2024-03-28T13:04:45.316-05:00 level=INFO msg="Character found"
time=2024-03-28T13:04:50.753-05:00 level=DEBUG msg="Fetching map data..."

### Version

v0.4.0-beta5

**Comment by Sunnyweeb** [comment]
did you choose the terror_zone run?

**Comment by Crims452** [comment]
> did you choose the terror_zone run?

I do not think so, are you able to share with me an example config?

**Comment by imneckro** [comment]
mine crashes on creating game
```
time=2024-03-31T19:17:14.962+03:00 level=INFO msg="Waiting for character selection screen..."
time=2024-03-31T19:17:15.964+03:00 level=INFO msg="Character selection screen found"
time=2024-03-31T19:17:15.964+03:00 level=INFO msg="Selecting character..."
time=2024-03-31T19:17:15.964+03:00 level=INFO msg="Character found"
time=2024-03-31T19:17:49.428+03:00 level=ERROR msg="Error creating new game: error creating game! Timeout"
```

**Comment by mista79** [comment]
> ### Details
> I'm unable to get past the character selection screen when the game is loading in. Koolo will crash. seems like it has to do with fetching map data. I made sure to get d2lod 1.13c time=2024-03-28T13:04:18.615-05:00 level=INFO msg="Waiting for character selection screen..." time=2024-03-28T13:04:39.442-05:00 level=INFO msg="Character selection screen found" time=2024-03-28T13:04:39.442-05:00 level=INFO msg="Selecting character..." time=2024-03-28T13:04:45.316-05:00 level=INFO msg="Character found" time=2024-03-28T13:04:50.753-05:00 level=DEBUG msg="Fetching map data..."
> 
> ### Version
> v0.4.0-beta5

I had this issue and it works after rebooting.
