### ISSUE TITLE
terror zone

### ISSUE THREAD

**Issue by childofwar1980** [hectorgimenez/koolo#116]
everything else works great but when i add ,terror_zone to the list of runs it is ignored completely

**Comment by Sunnyweeb** [comment]
hi, is it "IGNORED" or does it close the entire bot? if i only want my char to run terror_zone the bot simply crashes

**Comment by childofwar1980** [comment]
Mine does not crash I have put the terror_zone argument in the beginning
middle and end of the run list but it just skips it as if it's not there

**Comment by Millionaar** [comment]
I'm not sure this feature has ever worked. Anyone had this one working?

**Comment by Sunnyweeb** [comment]
no i downloaded the first version that added terror_zones and it crashed (it crashed if you only put terror_zone in run:), i think they fix that after other things, funny because isn't terror zone of the best things int he game due to exp and always 85 area?

**Comment by divineblade7** [comment]
@childofwar1980  are you still experiencing this? Feel free to close if not. Try the latest beta release if you haven’t already. It’s fixed working there.
