### ISSUE TITLE
a few issues

### ISSUE THREAD

**Issue by childofwar1980** [hectorgimenez/koolo#119]
hammerdin will not use alternate ability on the 2nd baal wave which are immune to magic which leads to alot of deaths and only sometimes will the merc be able to clear it. also i have played hammerdin and blizz sorc both and the bot will just tele directly into the middle of infector of souls pack or lord de seis and immediately die about 99% of the time in chaos sanctuary. also the stairs leading to halls of vaught bot can only access it about 50% of the time. is there anything that can be done about these issues?

**Comment by anelmann** [comment]
Kolbot had an config option called " telestomp= true/false " if true chars would tele on to enemies 0 distance and attack. If false a min distance af x would be used depending on build. Just an idea for devs. Gives the option to take safety measure when char is not fully geared.

**Comment by artosimonyan** [comment]
This or some kind of an alternative will be implemented in the future.
