### ISSUE TITLE
(hopefully) Relatively simple to implement improvements

### ISSUE THREAD

**Issue by scythetleppo** [hectorgimenez/koolo#121]
### Details

beta5 looking less buggy than beta4; nice. Here are some suggestions that might be on the easier side. If you were programming in Python I would help myself :(

- Don't Bo in middle of pack. If bo needed, teleport away if available, and/or town.
- Stash gold after selling items, not before
- Always bo on waypoint change
- Flush your logs - currently log file 0kb while running, and often remains so if non-graceful exit
- Add barb trav horker script - it's just one run again and again and it's pretty straightforward programmatically:
1. town stuff
2. go to trav
3. run into durance 1 door to reset merc position
4. back to trav through door
5. shout to limit damage
6. stun shout on council with same range as current hammerdin script
7. hork corpses (would require corpse unit logic but it's just bool check on is corpse really, Path etc is all the same)
8. pickit
9. exit
- available space check on backpack before repeatedly try to pick up item and wait for fails
empty_cells = empty cells in usable grid
check for shape invwidth wide and invheight tall in empty_cells
I can give a python version of this if it's helpful 
- quick documentation on how bot deals with chest keys. I added key as pickit with limit, which caused bot to buy keys then sell them. I tried without keys and enabled open chest after meph, but he just stands there repeatedly trying to open locked chest with no keys again and again.
- quick documentation on when bot loads config. when I press start? or do I need to close bot entirely and restart it, for example.
- quick documentation on how hotkey settings work - currently there are 9 hotkeys requested for hammerdin:
1. hammer
2. vigor
3. concentration
4. cleanse
5. teleport
6. town teleport
7. battle command
8. battle orders
9. redemption
But there are only 8 available hotkeys. Currently, because cleanse and redemption aren't used, I just wrote them as the same key.
- ultimately, you can actually just cycle the F-keys and check skill_left and skill_right to see what's bound to what automatically; you don't need a config file for it.
- Bot doesn't use cleanse or redemption, under any circumstances. Probably redemption can easily be put right after attack sequence and/or at health under % relatively easily. Cleansing needs state check and probably a bit of logic about what's a more important aura at the time/monsters around.
Anyway good bot! Just some thoughts that I think might be relatively straightforward to do.

### Version

v0.4.0 beta5

**Comment by hectorgimenez** [comment]
Hey, thanks for the feedback! It hasn't gone unnoticed, give me some time to digest, for sure some of those things will be implemented. Despite it's not python, you can try anyway, Go is pretty basic and no other dependencies are needed!

**Comment by hectorgimenez** [comment]
@scythetleppo how are you getting the item size? are you reading it from memory or matching it against d2data db?

**Comment by scythetleppo** [comment]
Most of the static data comes from the text files; extract them directly from the game with [Casc Viewer](http://www.zezula.net/en/casc/main.html). They are tab-delimited csvs.

armor.txt for example will have all the armor sizes, gold costs, the image to use, which base item is exceptional or elite version of which other item, etc.
