### ISSUE TITLE
Mouse gets out of sync when paused

### ISSUE THREAD

**Issue by kamikazzi1** [hectorgimenez/koolo#131]
### Details

When I pause the bot while it is running, I can't control the mouse it seems like it is stuck in one spot and won't click anywhere else. Has anyone found a way around this?

### Version

Dev

**Comment by hectorgimenez** [comment]
Are you pausing in-game? Is it happening always? This happens when you hit the pause button during game menu.

**Comment by kamikazzi1** [comment]
Pausing using the GUI after character is already in a game. It is not always happening, but probably 8 out of 10.

**Comment by artosimonyan** [comment]
This was fixed in newer versions.
