### ISSUE TITLE
Please make junk pickup a configurable option instead of hardcoded

### ISSUE THREAD

**Issue by scythetleppo** [hectorgimenez/koolo#138]
### Details

![image](https://github.com/hectorgimenez/koolo/assets/99230615/9724e539-42c3-4018-a4e4-605c4d8dffa2)
I have been wondering why my bot spends so much time grabbing garbage that isn't in the NIPs, and I've combed through them several times trying to fix them. Turns out ever time I go out late night gambling, I come back and mister bot has revenged me by spending forever dealing with rubbish items (sometimes getting them stuck on cursor)

Please allow at the least to disable this entirely, or ideally a kind of "under # gold start picking up crap to sell"
Also it might be worthwhile to instead of just doing all magic+, do it by gold cost of item (item > base item > cost)

### Version

v0.4.0 beta5

**Comment by 13413j1j13j5315n13** [comment]
Fixed in https://github.com/hectorgimenez/koolo/pull/143
