### ISSUE TITLE
Please close process handle on stop (or at least on exit).

### ISSUE THREAD

**Issue by scythetleppo** [hectorgimenez/koolo#139]
### Details

After stopping koolo, in fact even after closing it entirely, D2R is not available for other processes to attach and memory read. I believe you are not gracefully closing the handle.

You will likely need to do this anyway if you want the bot to be able to stop and then restart via an already-running D2R.

### Version

v0.4.0 beta5

**Comment by hectorgimenez** [comment]
Yup, you are right, thanks for reporting

**Comment by hectorgimenez** [comment]
It should be fixed now on latest main branch, it will be added on the next release
