### ISSUE TITLE
Bot doing nothing after starting the game

### ISSUE THREAD

**Issue by morothia** [hectorgimenez/koolo#144]
### Details

```
time=2024-04-11T13:41:19.084+02:00 level=INFO msg="Waiting for character selection screen..."
time=2024-04-11T13:41:35.995+02:00 level=INFO msg="Character selection screen found"
time=2024-04-11T13:41:35.995+02:00 level=INFO msg="Selecting character..."
time=2024-04-11T13:41:35.995+02:00 level=INFO msg="Character found"
time=2024-04-11T13:41:41.005+02:00 level=DEBUG msg="Fetching map data..."
time=2024-04-11T13:41:42.962+02:00 level=DEBUG msg="Fetch completed" ms=1957
time=2024-04-11T13:41:42.962+02:00 level=INFO msg="Starting Game #0. Run list: Pindleskin"

```
I have been using the bot for a while and it has stopped working a few days ago. The log is above - the bot enters the game, selects the correct character and then does nothing and logs nothing. Even after 2hours, he still does nothing. The status is "starting" 

### Version

0.4.0 build from main branch

**Comment by Sunnyweeb** [comment]
i know its not a great solution, but just restart that bot, close the d2 window press stop and then start again, its a rare problem

**Comment by morothia** [comment]
No, the problem was persistent. Issue has located and solved - removing the discord integration data helped. I just wish it got logged somehow, that interaction with discord is the problem.
