### ISSUE TITLE
Bot tries to open chests forever

### ISSUE THREAD

**Issue by NRHGDW** [hectorgimenez/koolo#145]
### Details

![image](https://github.com/hectorgimenez/koolo/assets/99230615/77b5982f-b02d-45bf-9472-59016a50bd29)

Has been standing there trying for quite some time. He will continue until the game times out. If I buy keys, he sells them. If I add keys to nip he picks them up then sells them. I disabled everything chest-related in config but doesn't seem there's a global option; I'd rather skip them than waste a run. I don't know, what is the proper way to set up the use of keys for chests? Or is one coming? Thanks

### Version

v0.4.0 beta5

**Comment by mista79** [comment]
Try placing the key in a locked area in the inventory.

**Comment by nullptr-ref** [comment]
@mista79 that's all fine but won't help when the bot doesn't buy keys to start with and what happens when it runs out?

**Comment by mista79** [comment]
I didn't have this problem after placing the key into the locked area.
The bot always buys keys and will not sell them because it is in a locked area.

**Comment by nullptr-ref** [comment]
Be that as it may, the fact that the bot doesn't buy keys to start with is an issue as it will lead to never-ending loop of trying to open chests that are locked.

**Comment by mista79** [comment]
Yes, it should check if the key is present and if not, won't open the box.

**Comment by nullptr-ref** [comment]
This should be fixed with #152

**Comment by artosimonyan** [comment]
This will be fixed in the upcoming versions.
