### ISSUE TITLE
Mephisto/andy run - sorc staying in corner

### ISSUE THREAD

**Issue by morothia** [hectorgimenez/koolo#156]
### Details

After running meph and killing him, after items are picked, my blizzsorc decides to teleport east and stay in that position. Logs do not show anything valuable after the item picks. I believe she should use the red portal or exit game but sadly she waits for time out out there. Killing council members and chests are disabled. Very similar error happens on and Andy, but not on every run (on meph its consistent problem). Any ideas? 

### Version

0.4.0 build from main branch

**Comment by nullptr-ref** [comment]
Do you mind sharing the logs of the interactions and a screenshot of where exactly the sorc goes to, could help identify the issue

**Comment by morothia** [comment]
seems solved right now so i'm closin 👍

**Comment by morothia** [comment]
seems solved in current version
