### ISSUE TITLE
Bot grabs mouse cursor

### ISSUE THREAD

**Issue by nullptr-ref** [hectorgimenez/koolo#157]
### Details

When the bot starts identifying items or when it uses the waypoint to switch the area, it grabs the mouse cursor and repositions it inside of the bot window. 

I suspected the MovePointer function but it doesn't seem to be happening when interacting with NPCs etc. 

Since we're sending mouse clicks directly to the window via PostMessage, this shouldn't be occurring at all. Any help identifying the cause or fixing the issue would be appreciated.

### Version

v0.4.0 (latest dev)

**Comment by hectorgimenez** [comment]
Yes... I'm not sure how to fix it, will need to dig on it, but is done by the game. You can see how it happens just opening normal game in windowed mode and the open the inventory, you will se that your mouse will move automatically into the game window. Is the same that is happening to the bot when opening inventory or wp for example.

**Comment by hectorgimenez** [comment]
Done
