### ISSUE TITLE
Not buying ID scrolls

### ISSUE THREAD

**Issue by Sleestaka** [hectorgimenez/koolo#160]
### Details

Bot doesn't purchase ID scrolls and is causing me to have problems intown at vendors.

### Version

v0.4.0

**Comment by mista79** [comment]
Do you have ID book?

**Comment by Sleestaka** [comment]
I do have a tome, and it burns through 20 scrolls and doesnt buy any

**Comment by hectorgimenez** [comment]
It's weird! and TP ones are working as expected?

**Comment by Sleestaka** [comment]
Yes, tp's work fine

**Comment by divineblade7** [comment]
@Sleestaka  are you still experiencing this? try the latest beta release if so. It will work with id scrolls. only time it has issue is if it is in the middle of iding a bunch and it runs out then it will keep trying and doesnt see its out.

if you are no longer having an issue feel free to close this ticket.

**Comment by hectorgimenez** [comment]
I will close, feel free to reopen if you find this problem again
