### ISSUE TITLE
Suggestion: read castingFrames from memory

### ISSUE THREAD

**Issue by scythetleppo** [hectorgimenez/koolo#164]
### Details

castingFrames is not needed in config as it's just a comparison of the cast rate from memory vs a few small tables. If you need explanation on how to get the value let me know.

### Version

v0.4.0 beta5

**Comment by hectorgimenez** [comment]
Thanks for the feedback, is something I would like to do when I have some free time, agree!

**Comment by hectorgimenez** [comment]
Done!
