### ISSUE TITLE
no  online char 

### ISSUE THREAD

**Issue by Dlike92** [hectorgimenez/koolo#168]
### Details

no  online char 

```
time=2024-04-25T22:25:37.844+02:00 level=ERROR msg="error restoring memory" !BADKEY="Access is denied."
time=2024-04-25T22:25:37.844+02:00 level=ERROR msg="error restoring memory" !BADKEY="Access is denied."
```

### Version

Dev

**Comment by anelmann** [comment]
try this- after setting up you char in GUI go to the char name folder-> config.yaml -> insert your password manually and save. run the bot after

**Comment by Dlike92** [comment]
does not work, config will erase PW everytime i start bot
maybe problem with @(?! in PW?

**Comment by nullptr-ref** [comment]
@Dlike92 The password resetting was a bug that was already fixed with https://github.com/hectorgimenez/koolo/commit/9d262ae1dbe0f2524aa5c97be3be194eed913680

Everything should work normally now. Please update your code to the latest main branch and build the bot.

**Comment by Dlike92** [comment]
changed passwort 

everthing worked again
