### ISSUE TITLE
Not picking rejuvu pots

### ISSUE THREAD

**Issue by anelmann** [hectorgimenez/koolo#169]
### Details

Current dev, not picking reju pots. 

### Version

Dev

**Comment by hectorgimenez** [comment]
There was a small change on the configuration for pots:

https://github.com/hectorgimenez/koolo/blob/main/config/template/config.yaml#L26

could you check if in your character configuration you have the potion section like this or are you still using the old numeric?

**Comment by jang9824** [comment]
> 화분의 구성에 작은 특징이 있다:
> 
> https://github.com/hectorgimenez/koolo/blob/main/config/template/config.yaml#L26
> 
> 스타일 구성에 동일한 물약 목록이 있고, 나머지 숫자를 사용하고 주실 수 있는 재고가 있습니까?

inventory:
    inventoryLock:
        - - 1
          - 1
          - 1
          - 1
          - 1
          - 1
          - 1
          - 0
          - 0
          - 0
        - - 1
          - 1
          - 1
          - 1
          - 1
          - 1
          - 1
          - 0
          - 0
          - 0
        - - 1
          - 1
          - 1
          - 1
          - 1
          - 1
          - 1
          - 0
          - 0
          - 0
        - - 1
          - 1
          - 1
          - 1
          - 1
          - 1
          - 1
          - 0
          - 0
          - 0
    beltColumns:
        - healing
        - mana
        - rejuvenation
        - rejuvenation
character:
    class: lightning
    castingFrames: 8
    useMerc: true
    stashToShared: false
    useTeleport: true

**Comment by jang9824** [comment]
![스크린샷(5)](https://github.com/hectorgimenez/koolo/assets/164779982/689b7996-ddb2-4999-810d-76aab733e28c)

**Comment by jang9824** [comment]
> There was a small change on the configuration for pots:
> 
> https://github.com/hectorgimenez/koolo/blob/main/config/template/config.yaml#L26
> 
> could you check if in your character configuration you have the potion section like this or are you still using the old numeric?

![스크린샷(5)](https://github.com/hectorgimenez/koolo/assets/164779982/60b760ff-1eff-467c-902c-d062baa72eaa)

**Comment by xg6636** [comment]
I found this issue too. The config is proper,because current dev has a check of config before running.

**Comment by anelmann** [comment]
tried to copy config manually from template and put in my settings without using new gui for configuration. 
![image](https://github.com/hectorgimenez/koolo/assets/36128680/05c76b63-103b-44a2-abc9-62e027ddaf3c)
- still not picking up rejuv pots.

**Comment by Millionaar** [comment]
This might not be a belt issue. If I load the belt with rejuvs, it seems to still use them. It simply just doesn't pick them up even though in my misc.nip.

**Comment by xg6636** [comment]
I think I find out what happened.

### details

In `config.yaml`, the potion type value is "rejuvenation".
![屏幕截图 2024-04-28 123121](https://github.com/hectorgimenez/koolo/assets/90829467/fbebda34-1abf-4f25-8eed-d4709caad1c7)

But it is written as "rejuv" in `config.go`, this causes wrong potion count, the bot doesn't know how many cells are empty in belt.
![屏幕截图 2024-04-28 122941](https://github.com/hectorgimenez/koolo/assets/90829467/0e5ba247-d27f-4c79-aa73-5eee949134b0)

### fix

Replace `rejuv` with `rejuvenation` in 160th line of `config.go`.

**Comment by jang9824** [comment]
> 무슨 일이 일어났는지 알아낸 것 같아요.
> 
> ### 세부
> 에서 `config.yaml`물약 유형 값은 "회춘"입니다. ![屏幕截图 2024-04-28 123121](https://private-user-images.githubusercontent.com/90829467/326229617-fbebda34-1abf-4f25-8eed-d4709caad1c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyODMxNDEsIm5iZiI6MTcxNDI4Mjg0MSwicGF0aCI6Ii85MDgyOTQ2Ny8zMjYyMjk2MTctZmJlYmRhMzQtMWFiZi00ZjI1LThlZWQtZDQ3MDljYWFkMWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDA1NDA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzYmUxMjRkMjVjMGIyOWFkZjY4M2M3NGVjMDllODE2ZGRiMjIyMDI1NWM3ZDk4NzU4M2UzMzAxYzBkNGIyN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QYAbL9QhR6GVpaKWo8el801ZRqsJCBfpGg-KofQLzng)
> 
> 하지만 에서 "rejuv"로 쓰여 있어 `config.go`잘못된 물약 개수가 발생하고 봇은 벨트에 얼마나 많은 셀이 비어 있는지 알 수 없습니다. ![屏幕截图 2024-04-28 122941](https://private-user-images.githubusercontent.com/90829467/326229597-0e5ba247-d27f-4c79-aa73-5eee949134b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyODMxNDEsIm5iZiI6MTcxNDI4Mjg0MSwicGF0aCI6Ii85MDgyOTQ2Ny8zMjYyMjk1OTctMGU1YmEyNDctZDI3Zi00Yzc5LWFhNzMtNWVlZTk0OTEzNGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDA1NDA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxOGM5NmNkZTNiYTExMjE3ZTJhNWI5Y2E1YzQ1OTMzMmQ5MmEzYTViOWNhNDFmZWJiNWI0YTRiYmM4YjZlNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oqRt_YZrOtFbe7--pRZjc3ZaXAjdcHkk9MpMYhPBizM)
> 
> ### 고치다
> 의 160번째 줄로 교체 `rejuv`하세요 .`rejuvenation``config.go`

Thanks to you, it's been solved

**Comment by hectorgimenez** [comment]
Fixed now, thanks
