### ISSUE TITLE
Items by stash pages

### ISSUE THREAD

**Issue by scythetleppo** [hectorgimenez/koolo#170]
### Details

I noticed this in your code while looking through something else.
![image](https://github.com/hectorgimenez/koolo/assets/99230615/d53cd50e-a76c-409c-b2cf-3b0a53f98955)

If you want to know how to get the specific stash page for an item let me know and I can explain the process. All items' stash page location is in memory.

### Version

v0.4.0 beta5

**Comment by hectorgimenez** [comment]
I need to check, I remember that @13413j1j13j5315n13 told me that we can get the items but we are tagging them wrong (as if they were in the Vendor).

btw, @scythetleppo drop me an email (is on my github profile) I would like to share something

**Comment by scythetleppo** [comment]
From what I can see you are using this method, which is accurately commented as only working in single player mode.
![image](https://github.com/hectorgimenez/koolo/assets/99230615/d9736323-1425-4caf-bcce-e70a3fc477eb)

**Comment by hectorgimenez** [comment]
This is fixed now :)
