### ISSUE TITLE
Suggestion: Allow for unid items

### ISSUE THREAD

**Issue by scythetleppo** [hectorgimenez/koolo#171]
### Details

Currently, bot runs this to find which items to pick up (in part):

![image](https://github.com/hectorgimenez/koolo/assets/99230615/b7b4bf4e-21ae-42b2-9c01-acf550bf4e61)

However when the bot is determining what to identify, there is no further check for a match:

![image](https://github.com/hectorgimenez/koolo/assets/99230615/b7364732-dcbd-4ddb-92a7-56f326e39cda)

And then after identifying, bot checks for match to stash appropriate items:

![image](https://github.com/hectorgimenez/koolo/assets/99230615/97a41f4e-ac02-44c0-9813-e5c877c1ccc2)

I believe this means the bot will always pick up matching items, and then identify all of them, and then make the check if they should go to inventory or not. If I am reading this correctly, then I propose the following workflow should be a relatively easy fix, and allow for unid items:

1. evaluate vs nip to pick up
2. during id process, do not identify items which fully match a rule
3. stash items

In order to do that, I believe all you need to do is insert a check in the id process, since your itemfilter.Evaluate already accounts for matching stats and unid state:

![image](https://github.com/hectorgimenez/koolo/assets/99230615/c661a12d-2615-4bd5-ac95-b2f479b5ba46)

### Version

v0.4.0 beta5

**Comment by hectorgimenez** [comment]
With the new NIP parser this is also fixed now
