### ISSUE TITLE
I have a question.  low specification skin or legacy graphics mode

### ISSUE THREAD

**Issue by jang9824** [hectorgimenez/koolo#173]
### Details

Can you press the g key when you enter the room so I can change it to legacy graphics mode?
Or
Is there a way to add a command line so I can use a low specification skin?

### Version

v0.4.0-beta5

**Comment by hectorgimenez** [comment]
Currently this is not supported, positions in UI for legacy mode are in different places and hardcoded positions are for the new graphics.

**Comment by jang9824** [comment]
> 현재 이는 지원되지 않습니다. 레거시 모드에 대한 UI의 위치는 다른 위치에 있으며 하드코딩된 위치는 새 그래픽에 대한 것입니다.

Thank you for your answer.
