### ISSUE TITLE
use too many potions while teleporting to baal

### ISSUE THREAD

**Issue by xg6636** [hectorgimenez/koolo#174]
### Details

in v0.4.0 beta5, from 2nd keep wp to throne, the bot continues to use healing potions and rejuv.
in most cases, the bot runs out all the healing and rejuv potions.
in fact, it's not necessary, somtimes it needs to use potions, sometimes not.

### Version

v0.4.0 beta5

**Comment by divineblade7** [comment]
@xg6636 are you still running into this? I would adjust the health and mana pot thresholds if so.

**Comment by xg6636** [comment]
it seems that the subsequent versions already fixed this bug. i don't know, i'm not sure about it.

**Comment by divineblade7** [comment]
Making sure. Ok feel free to close this then. Glad it’s working for you.
