### ISSUE TITLE
Koolo.exe crashes/exits upon start, Windows 10 ltsc 21h2, 19044.4291

### ISSUE THREAD

**Issue by addeboiii** [hectorgimenez/koolo#189]
### Details

https://imgur.com/LANrYWg

The app window just flashes and then crashes/exit. The log file is empty. Nothing in windows event viewer. Disabled firewall and defender, but issue persist. Happening with all versions using the new GUI (0.4.0-beta2 to 0.4.0-beta6). Versions without GUI work fine.

Anyone have clue what is missing? Feels like some sort of package that is not included on LTSC maybe?

### Version

v0.4.0-beta6

**Comment by GFKSolar** [comment]
delete ur char configs. wrong line in config

**Comment by addeboiii** [comment]
You mean I should delete the "TEMPLATE" character config? There are no character configs.. No type of modification has been done to any of the files. I just download latest release, launch the exe and the result can been seen in the gif. If I clone the project and use build.bat, same result.

**Comment by nullptr-ref** [comment]
That's verry strange @addeboiii . Try to run the bot via source directly, here's what you gotta do: 

1 - Copy the config folder from the build directory into the main repo folder -> cmd -> koolo.
2 - Open a command prompt (as administrator) and navigate to the cmd -> koolo folder.
3 - Execute the bot via the go run main.go command and see if it works. If it errors out, provide us with the logs from the command prompt. 

Keep in mind that Koolo requires to run as administrator now so if you don't have admin rights it may cause those issues.

**Comment by addeboiii** [comment]
The exe is always run as admin. It is the only user account on the client and it is local administrator.

Here is output from cmd when I launch it with go run main.go. Cconfig folder "koolo-main\build\config" copied to koolo-main\cmd\koolo.

`C:\Users\Fedsmoker\Desktop\koolo-main\cmd\koolo>go run main.go
panic: The system could not find the environment option that was entered.

goroutine 27 [running]:
main.main.func1()
        C:/Users/Fedsmoker/Desktop/koolo-main/cmd/koolo/main.go:57 +0x285
golang.org/x/sync/errgroup.(*Group).Go.func1()
        C:/Users/Fedsmoker/go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
        C:/Users/Fedsmoker/go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:75 +0x96
exit status 2
`

**Comment by addeboiii** [comment]
Closed by mistake.

**Comment by hectorgimenez** [comment]
mmm looks like the error is related to the webview initialization, it's weird because all the latest versions of windows 10 and windows 11 already come with it preinstalled.

Just in case, you can try to download it: https://developer.microsoft.com/en-us/microsoft-edge/webview2?form=MA13LH you can try the standalone installer for your architecture, if it's already installed it will tell you when you run it, otherwise install it and restart and try again.

**Comment by hectorgimenez** [comment]
> Same error for me and i have webview2:( just auto closes but mine actually makes the game then closes

I don't think it's related to this issue, to me yours is more about the d2lod game, check the log file please

**Comment by hamptone69** [comment]
> > Same error for me and i have webview2:( just auto closes but mine actually makes the game then closes
> 
> I don't think it's related to this issue, to me yours is more about the d2lod game, check the log file please

time=2024-05-01T23:58:09.577-07:00 level=INFO msg="Waiting for character selection screen..."
time=2024-05-01T23:58:35.660-07:00 level=INFO msg="Character selection screen found"
time=2024-05-01T23:58:35.660-07:00 level=INFO msg="Selecting character..."
time=2024-05-01T23:58:47.439-07:00 level=INFO msg="Character found"
time=2024-05-01T23:58:51.861-07:00 level=DEBUG msg="Fetching map data..."

the second before char loads into game bot auto closes / d2r stays open though

**Comment by hamptone69** [comment]
Ok i fixed that and its not closing but now im attempting to use leveling script and it jsut keeps opening and closing the skill hot key f1-f8 and nothing else

**Comment by hectorgimenez** [comment]
> Ok i fixed that and its not closing but now im attempting to use leveling script and it jsut keeps opening and closing the skill hot key f1-f8 and nothing else tried both paladin and sorc level 1s

short answer: don't expect too much for the leveling script. But you can disable auto skill binding (not working well yet) and assign the skills manually, any key should be fine, koolo will autodetect them.
![image](https://github.com/hectorgimenez/koolo/assets/12543131/59b395e3-c8fb-4b79-9c05-0ed0d21e7d86)

**Comment by addeboiii** [comment]
> mmm looks like the error is related to the webview initialization, it's weird because all the latest versions of windows 10 and windows 11 already come with it preinstalled.
> 
> Just in case, you can try to download it: https://developer.microsoft.com/en-us/microsoft-edge/webview2?form=MA13LH you can try the standalone installer for your architecture, if it's already installed it will tell you when you run it, otherwise install it and restart and try again.

This resolved the issue. Thanks.
