### ISSUE TITLE
Question/suggestion: cubing of gems and runes

### ISSUE THREAD

**Issue by addeboiii** [hectorgimenez/koolo#198]
### Details

Is horadic_cube.go just for opening cow level? Or can it be used to cube gems and runes? How do you enable gems cubing?

### Version

v0.4.0-beta6

**Comment by nullptr-ref** [comment]
That's still not a feature that's implemented in the bot. I am working on it but it will require to first update some aspects of the d2go library before we can implement it successfully.

**Comment by hectorgimenez** [comment]
I will close this ticket, a preview version working with gems has been already implemented and will be published with the next release.
