### ISSUE TITLE
Is anyone able to get the terror zones to work?

### ISSUE THREAD

**Issue by Boredguy35** [hectorgimenez/koolo#200]
### Details

I'm using the new version and the terror zone run does nothing. Also the gambling does nothing.
time=2024-05-04T20:16:37.427-05:00 level=INFO msg="Waiting for character selection screen..."
time=2024-05-04T20:16:52.266-05:00 level=INFO msg="Character selection screen found"
time=2024-05-04T20:16:52.266-05:00 level=INFO msg="Selecting character..."
time=2024-05-04T20:16:52.266-05:00 level=INFO msg="Character found"
time=2024-05-04T20:16:56.282-05:00 level=DEBUG msg="Fetching map data..."
time=2024-05-04T20:16:58.180-05:00 level=DEBUG msg="Fetch completed" ms=1898

That's the log from a terror zone run, it sits in town until I close it.

### Version

v.0.4.0 beta6

**Comment by nullptr-ref** [comment]
Can you build the bot from source using the build script and try that version? If it still doesn't work, check the debug and scroll down to the terror zones to see if the bot detects them.

**Comment by Boredguy35** [comment]
Ok, I'll try to figure that out. Also the pickit it keeping every blue gothic/light plate, no matter what affix. I have made 0 changes to it.

**Comment by Boredguy35** [comment]
Ok, I followed the instructions to build it from source and it had the latest version already. I don't know how to actually run it without a convinent launcher lol. All I see is a bunch of folders, with more folders.

**Comment by nullptr-ref** [comment]
After you build it from source, the exe will be located in the build folder. Run it from there and add your config. 

When you're in a game, open the debug screen from the debug button and scroll down till you find the terror zones. Expand it and see if there are any entries there. 

You can also copy/paste the data from http://localhost:8087/debug-data?charName=YOURCHARACTERNAMEHERE.. 

!!!! IMPORTANT !!!! : That data contains the entries of the bnet username and bnet password, make sure you DO NOT share those.

**Comment by Boredguy35** [comment]
Ok I finally figured it out, in the debug menu I can scroll down to terror zones and it shows like
TerrorZones : null

I've tried to find and copy the data from that link by changing my name, but I must be doing that wrong.

**Comment by Boredguy35** [comment]
This is what it looks like for me, the runs are set for lower kurast chest and terror zone


{"AreaOrigin":{"X":0,"Y":0},"Corpse":{"Found":false,"IsHovered":false,"Position":{"X":0,"Y":0}},"Monsters":null,"CollisionGrid":null,"PlayerUnit":{"Name":"","ID":0,"Area":0,"Position":{"X":0,"Y":0},"Stats":null,"BaseStats":null,"Skills":null,"States":null,"Class":0,"LeftSkill":0,"RightSkill":0,"AvailableWaypoints":null},"NPCs":null,"Items":{"Belt":{"Items":null,"Name":""},"AllItems":null},"Objects":null,"AdjacentLevels":null,"Rooms":null,"OpenMenus":{"Inventory":false,"LoadingScreen":false,"NPCInteract":false,"NPCShop":false,"Stash":false,"Waypoint":false,"MapShown":false,"SkillTree":false,"Character":false,"QuitMenu":false,"Cube":false,"SkillSelect":false,"Anvil":false},"Roster":null,"HoverData":{"IsHovered":false,"UnitID":0,"UnitType":0},"TerrorZones":null,"Quests":null,"KeyBindings":{"CharacterScreen":{"Key1":[0,0],"Key2":[0,0]},"Inventory":{"Key1":[0,0],"Key2":[0,0]},"HoradricCube":{"Key1":[0,0],"Key2":[0,0]},"PartyScreen":{"Key1":[0,0],"Key2":[0,0]},"MercenaryScreen":{"Key1":[0,0],"Key2":[0,0]},"MessageLog":{"Key1":[0,0],"Key2":[0,0]},"QuestLog":{"Key1":[0,0],"Key2":[0,0]},"HelpScreen":{"Key1":[0,0],"Key2":[0,0]},"SkillTree":{"Key1":[0,0],"Key2":[0,0]},"SkillSpeedBar":{"Key1":[0,0],"Key2":[0,0]},"Skills":[{"SkillID":0,"Key1":[0,0],"Key2":[0,0]},{"SkillID":0,"Key1":[0,0],"Key2":[0,0]},{"SkillID":0,"Key1":[0,0],"Key2":[0,0]},{"SkillID":0,"Key1":[0,0],"Key2":[0,0]},{"SkillID":0,"Key1":[0,0],"Key2":[0,0]},{"SkillID":0,"Key1":[0,0],"Key2":[0,0]},{"SkillID":0,"Key1":[0,0],"Key2":[0,0]},{"SkillID":0,"Key1":[0,0],"Key2":[0,0]},{"SkillID":0,"Key1":[0,0],"Key2":[0,0]},{"SkillID":0,"Key1":[0,0],"Key2":[0,0]},{"SkillID":0,"Key1":[0,0],"Key2":[0,0]},{"SkillID":0,"Key1":[0,0],"Key2":[0,0]},{"SkillID":0,"Key1":[0,0],"Key2":[0,0]},{"SkillID":0,"Key1":[0,0],"Key2":[0,0]},{"SkillID":0,"Key1":[0,0],"Key2":[0,0]},{"SkillID":0,"Key1":[0,0],"Key2":[0,0]}],"SelectPreviousSkill":{"Key1":[0,0],"Key2":[0,0]},"SelectNextSkill":{"Key1":[0,0],"Key2":[0,0]},"ShowBelt":{"Key1":[0,0],"Key2":[0,0]},"UseBelt":[{"Key1":[0,0],"Key2":[0,0]},{"Key1":[0,0],"Key2":[0,0]},{"Key1":[0,0],"Key2":[0,0]},{"Key1":[0,0],"Key2":[0,0]}],"SwapWeapons":{"Key1":[0,0],"Key2":[0,0]},"Chat":{"Key1":[0,0],"Key2":[0,0]},"Run":{"Key1":[0,0],"Key2":[0,0]},"ToggleRunWalk":{"Key1":[0,0],"Key2":[0,0]},"StandStill":{"Key1":[0,0],"Key2":[0,0]},"ForceMove":{"Key1":[0,0],"Key2":[0,0]},"ShowItems":{"Key1":[0,0],"Key2":[0,0]},"ShowPortraits":{"Key1":[0,0],"Key2":[0,0]},"Automap":{"Key1":[0,0],"Key2":[0,0]},"CenterAutomap":{"Key1":[0,0],"Key2":[0,0]},"FadeAutomap":{"Key1":[0,0],"Key2":[0,0]},"PartyOnAutomap":{"Key1":[0,0],"Key2":[0,0]},"NamesOnAutomap":{"Key1":[0,0],"Key2":[0,0]},"ToggleMiniMap":{"Key1":[0,0],"Key2":[0,0]},"SayHelp":{"Key1":[0,0],"Key2":[0,0]},"SayFollowMe":{"Key1":[0,0],"Key2":[0,0]},"SayThisIsForYou":{"Key1":[0,0],"Key2":[0,0]},"SayThanks":{"Key1":[0,0],"Key2":[0,0]},"SaySorry":{"Key1":[0,0],"Key2":[0,0]},"SayBye":{"Key1":[0,0],"Key2":[0,0]},"SayNowYouDie":{"Key1":[0,0],"Key2":[0,0]},"SayRetreat":{"Key1":[0,0],"Key2":[0,0]},"ClearScreen":{"Key1":[0,0],"Key2":[0,0]},"ClearMessages":{"Key1":[0,0],"Key2":[0,0]},"Zoom":{"Key1":[0,0],"Key2":[0,0]},"LegacyToggle":{"Key1":[0,0],"Key2":[0,0]}},"CharacterCfg":{"MaxGameLength":0,"Username":"","Password":"","Realm":"","CharacterName":"","CommandLineArgs":"","Health":{"HealingPotionAt":0,"ManaPotionAt":0,"RejuvPotionAtLife":0,"RejuvPotionAtMana":0,"MercHealingPotionAt":0,"MercRejuvPotionAt":0,"ChickenAt":0,"MercChickenAt":0},"Inventory":{"InventoryLock":null,"BeltColumns":["","","",""]},"Character":{"Class":"","CastingFrames":0,"UseMerc":false,"StashToShared":false,"UseTeleport":false},"Game":{"MinGoldPickupThreshold":0,"ClearTPArea":false,"Difficulty":"","RandomizeRuns":false,"Runs":null,"Pindleskin":{"SkipOnImmunities":null},"Pit":{"MoveThroughBlackMarsh":false,"OpenChests":false,"FocusOnElitePacks":false},"StonyTomb":{"OpenChests":false,"FocusOnElitePacks":false},"AncientTunnels":{"OpenChests":false,"FocusOnElitePacks":false},"Mephisto":{"KillCouncilMembers":false,"OpenChests":false},"Tristram":{"ClearPortal":false,"FocusOnElitePacks":false},"Nihlathak":{"ClearArea":false},"Diablo":{"KillDiablo":false,"ClearArea":false,"OnlyElites":false},"Baal":{"KillBaal":false,"DollQuit":false,"SoulQuit":false},"Eldritch":{"KillShenk":false},"TerrorZone":{"FocusOnElitePacks":false,"SkipOnImmunities":null,"SkipOtherRuns":false,"Areas":null},"Leveling":{"EnsurePointsAllocation":false,"EnsureKeyBinding":false}},"Companion":{"Enabled":false,"Leader":false,"LeaderName":"","Attack":false,"GameNameTemplate":"","GamePassword":""},"Gambling":{"Enabled":false,"Items":null},"BackToTown":{"NoHpPotions":false,"NoMpPotions":false,"MercDied":false},"Runtime":{"CastDuration":0,"Rules":null}}}

**Comment by nullptr-ref** [comment]
It seems that we are reading the terror zones at a specific address that works for online only and not offline. Hector will check the offline tz handling and address it. 

For now I recommend removing the TZ for offline so it doesn't cause the exit game loop.

**Comment by artosimonyan** [comment]
TZs are wonky. Will be rewritten in the upcoming versions.
