### ISSUE TITLE
Got bot working for most part but he has trouble with vendor potions/tp;s

### ISSUE THREAD

**Issue by hamptone69** [hectorgimenez/koolo#203]
### Details

I jus noticed bot was sitting in the field trying to TP for over 20 minutes but he had no scrolls doing nothing else,

another issue when he goes to shop half the time he wont buy pots and the second he leaves town he opens a tp to go to vendor, does nothing at vendor runs back out of town and or tp's depending on the scirpt, just to go to shop again and buy nothing ... he has the gold

Also i have not got him to open cows with cube once yet and if i manually open it and press resume he instantly leaves the game

### Version

newest

**Comment by hamptone69** [comment]
Locked chests bot will spam trying to open it, i didnt wait to see for how long but i waited a while of him just spamming clicking the chests when out of keys, is there a way i can turn off opening locked chests all together?

**Comment by hamptone69** [comment]
![image](https://github.com/hectorgimenez/koolo/assets/168715437/054a2183-5bf1-43cc-9475-393e20578ccf)

bot gets stuck at shop with flotiing items as you can see here, shop and inventory are closed but he gets stuck with a item on his mouse and doesn't move

**Comment by divineblade7** [comment]
> Also i have not got him to open cows with cube once yet and if i manually open it and press resume he instantly leaves the game
> 

I’ve had it work when placing the cube in a locked part of inventory. When I had it in stash it would fail sometimes because it couldn’t tell what tab it was on when looking for cube. 

Also make sure you have keys and tome of tp and time of Id in a locked part of your inventory and that seems to help mine as well

**Comment by divineblade7** [comment]
Still having this issue @hamptone69 ?  This has been fixed in latest release. Feel free to close.
