### ISSUE TITLE
Often get this error in cows and chaos sanctuary

### ISSUE THREAD

**Issue by Nowack32** [hectorgimenez/koolo#206]
When this happened the bot just stopped doing anything and just stood and got killed by cows.

### Details

level=WARN msg="Game finished with errors, reason: unrecoverable error occurred, game can not continue: attempt limit reached on step: InteractObjectStep: object 141 could not be interacted. Game total time: 333.25s"

Why does this happen in those areas?

### Version

beta6

**Comment by hectorgimenez** [comment]
Looks like it can not reach a chest, let me look to this interaction error, it happens very often and it's annoying

**Comment by artosimonyan** [comment]
Interactions have been re-written in the newer versions and shouldn't be an issue.
