### ISSUE TITLE
Do not move automatically..

### ISSUE THREAD

**Issue by 012oov** [hectorgimenez/koolo#208]
### Details

It works fine from creating a game to connecting to it.

The most strange thing is, the character doesn't move at all, but, once I click anywhere, it starts working properly. And when one action is finished, it stops again.

I don't know how to fix this.

### Version

v.0.4.0

**Comment by HYPERTONE** [comment]
Were you able to resolve this? Can you share more details?

**Comment by hectorgimenez** [comment]
it's still an issue?

**Comment by 012oov** [comment]
Yeah I still have the problem. Successfully create room, but nothing.. Auto-clicking seems to be operating because mouse doesn't work. Strange thing is, once I click the waypoint, it works.

**Comment by HYPERTONE** [comment]
My native resolution is 3440x1440. 

Running D2R at 1280x720 does not allow the character to move. Previously I changed my native resolution to 1920x1080 with D2R at 1280x720 and had no issues. The latest update seems to have broken this.

Any ideas?

**Comment by artosimonyan** [comment]
Should be fixed in the latest, upcoming versions. If you still have any issues, feel free to hop by discord or open a new issue.
