### ISSUE TITLE
Keybind issue while leveling

### ISSUE THREAD

**Issue by ozzyian** [hectorgimenez/koolo#209]
### Details

When creating a new character and starting the leveling profile (lightning sorc and paladin) it just stands in town trying to bind some skill over and over. Turning off autobind works but then no skills will used/bound.

### Version

dev

**Comment by onyxbadge** [comment]
Did you ever figure out what causes this?

**Comment by theksk23** [comment]
you can bind them yourself as a workaround.
I thought there was another, releated issue for this but unable to find it r/n

**Comment by artosimonyan** [comment]
This is an issue with current versions but the logic will be completely rewritten in the upcoming release.
