### ISSUE TITLE
Tries depositing gold 2x through all stash tabs

### ISSUE THREAD

**Issue by divineblade7** [hectorgimenez/koolo#213]
Interesting quirk ive noticed since turning off gambling since it was bugged in the last release, it will try depositing gold through all stash tabs as expected, walk a bit away, and then go back and try every stash tab again every time it visits stash. 

Not a huge thing, just something i noticed.

**Comment by nullptr-ref** [comment]
Do you have cubing recipies enabled and did it actually combine some gems? If it does it calls the stash logic which will try to stash the gold once again. 

We do have plans to address the gold stashing logic in the near future to avoid all that.

**Comment by divineblade7** [comment]
I apologize for not noting which commit I used. This was before I pulled the cubing recipes commit, so it wasn’t from what.. I noticed it the day before posting. Just didn’t get a chance to post. 

Awesome. Thank you null, yea I’m just making sure I don’t fill up on gold to avoid that. I haven’t tried re-enabling gambling yet to see if it will still fill up the inventory again without selling. But If it does that again I’ll update here.

**Comment by divineblade7** [comment]
Enabled gambling again to test and it still fills up whole inventory and still tries to buy more over and over till game timeout is reached.

**Comment by divineblade7** [comment]
commit: feba50097719754e9b0ce67bf0ca2d4b3011fd8a
update:  I noticed that when gold is completely full, it does the 2x deposit each tab then leaves game, starts new game and does it all over again on repeat.

When i then enable gambling it goes back to buying a full inv, and still trying to buy more even when full.

**Comment by hectorgimenez** [comment]
gambling should be fixed now, also gold stashing should work better
