### ISSUE TITLE
Endless create/leave loop when TZ changed to a TZ run that is not enabled.

### ISSUE THREAD

**Issue by divineblade7** [hectorgimenez/koolo#216]
commit: feba50097719754e9b0ce67bf0ca2d4b3011fd8a

It will create game, go to the TZ that is not enabled on the TZ list. and show game completed once it took waypoint there then leave and do again till the hour is over. If i restart bot it will resume as normal and skip this TZ since its not enabled. The current TZ during this was stony field (this was not enabled, but the prior hours TZ was jail, which is enabled.)

+skip all runs and only do tz when available is enabled.

``` time=13:28:03 level=INFO msg="Starting Game #1. Run list: TerrorZone Run: Stony Field, Jail Level 1, Jail Level 2, Jail Level 3"
time=13:28:03 level=INFO msg="Running: TerrorZone Run: Stony Field, Jail Level 1, Jail Level 2, Jail Level 3"
time=13:28:03 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=13:28:08 level=DEBUG msg="Load completed, continuing execution"
time=13:28:08 level=DEBUG msg="Checking for character corpse..."
time=13:28:08 level=DEBUG msg="Character corpse not found :D"
time=13:28:08 level=DEBUG msg="Checking for items to identify..."
time=13:28:08 level=DEBUG msg="No items to identify..."
time=13:28:08 level=DEBUG msg="Belt Stats Health: 8/8 healing, 4/4 mana, 4/4 rejuv."
time=13:28:08 level=DEBUG msg="Checking for items to stash..."
time=13:28:08 level=DEBUG msg="No items to stash..."
time=13:28:08 level=DEBUG msg="Checking for items to stash..."
time=13:28:08 level=DEBUG msg="No items to stash..."
time=13:28:08 level=DEBUG msg="TZ area skipped" area="Stony Field"
time=13:28:12 level=DEBUG msg="CTA found: swapping weapon and casting Battle Command / Battle Orders"
time=13:28:12 level=DEBUG msg=Buffing...
time=13:28:15 level=DEBUG msg="Reached area" area="Stony Field"
time=13:28:15 level=DEBUG msg="No items detected, waiting a bit and will try again" waitMs=1000
time=13:28:16 level=INFO msg="Run TerrorZone Run: Stony Field, Jail Level 1, Jail Level 2, Jail Level 3 finished, length: 13.20s" ```

**Comment by nydicil** [comment]
I have similar problem.
TZ is in Arreat Plateu. I noticed that my nova sorc stucks a lot of times on the map, spelling a lot of nova when there is a lot of fire in area and doesnt teleport to new place. So I wanted to disable Arreat Plateu in config. After that bot creates new game, sorc goes to Arreat WP, casts all  buffs and quits game. 

time=11:53:46 level=INFO msg="Waiting for character selection screen..."
time=11:54:02 level=INFO msg="Character selection screen found"
time=11:54:02 level=INFO msg="Selecting character..."
time=11:54:02 level=INFO msg="Character found"
time=11:54:06 level=DEBUG msg="Fetching map data..."
time=11:54:09 level=DEBUG msg="Fetch completed" ms=3708
time=11:54:09 level=INFO msg="Starting Game #0. Run list: TerrorZone Run: Arreat Plateau, Hell2, pit"
time=11:54:09 level=INFO msg="Running: TerrorZone Run: Arreat Plateau, Hell2"
time=11:54:10 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=11:54:12 level=DEBUG msg="Load completed, continuing execution"
time=11:54:12 level=DEBUG msg="Checking for character corpse..."
time=11:54:12 level=DEBUG msg="Character corpse not found :D"
time=11:54:12 level=DEBUG msg="Checking for items to stash..."
time=11:54:12 level=DEBUG msg="Checking for items to identify..."
time=11:54:12 level=DEBUG msg="No items to identify..."
time=11:54:12 level=DEBUG msg="Belt Stats Health: 4/4 healing, 3/4 mana, 8/8 rejuv."
time=11:54:12 level=DEBUG msg="Checking for items to stash..."
time=11:54:12 level=DEBUG msg="Checking for items to stash..."
time=11:54:12 level=DEBUG msg="TZ area skipped" area="Arreat Plateau"
time=11:54:16 level=DEBUG msg="CTA found: swapping weapon and casting Battle Command / Battle Orders"
time=11:54:16 level=DEBUG msg=Buffing...
time=11:54:20 level=DEBUG msg="Reached area" area="Arreat Plateau"
time=11:54:20 level=DEBUG msg="Clearing TZ area" area=Hell2
time=11:54:20 level=DEBUG msg="Destination area not found" area=Hell2
time=11:54:20 level=WARN msg="Game finished with errors, reason: unrecoverable error occurred, game can not continue: attempt limit reached on step: InteractEntranceStep: area Hell2 [126]  not found. Game total time: 10.78s" supervisor=MoooMooo mapSeed=1502982702
time=11:54:23 level=INFO msg=Stopping... configuration=MoooMooo
time=11:54:23 level=INFO msg="Finished stopping" configuration=MoooMooo
time=11:54:30 level=ERROR msg="Error creating new game: error creating game! Timeout"
