### ISSUE TITLE
Chicken on souls not working

### ISSUE THREAD

**Issue by divineblade7** [hectorgimenez/koolo#217]
Commit: feba50097719754e9b0ce67bf0ca2d4b3011fd8a

Tested in a few baal games. Chicken on souls not functioning when enabled in regular runs, or in TZ runs.

Have not tested doll chicken.

**Comment by xg6636** [comment]
i found this issue too.
this seemed occurring in lobby games,
it works fine in non-lobby games in most cases.

**Comment by divineblade7** [comment]
All my tests were done in private games @xg6636

**Comment by hectorgimenez** [comment]
Could you please try again? I think it should work now
