### ISSUE TITLE
World Stone Keep pathing errors

### ISSUE THREAD

**Issue by divineblade7** [hectorgimenez/koolo#222]
Commit: e0840d6eb2ec1cc4dbb2711717422fd223d1febe

In new commit it had been auto leaves once taking waypoint to worldstone level 2. with this error. let it run for a few games because i get that error periodically in other areas that are seemingly random levels sometimes. But it did that for 6 games.

reverted back to commit before the pather changes and it ~~mostly~~ works 
(edit: mostly, because still seeing a similar error in old pather some games as well)

old commit error:
``` time=23:39:52 level=WARN msg="Game finished with errors, reason: unrecoverable error occurred, game can not continue: attempt limit reached on step: MoveToStep: path could not be calculated, maybe there is an obstacle or a flying platform (arcane sanctuary). Game total time: 36.64s" supervisor=Hammer```

New pather changes error every game so far
``` time=23:10:21 level=WARN msg="Game finished with errors, reason: unrecoverable error occurred, game can not continue: attempt limit reached on step: MoveToStep: path could not be calculated, maybe there is an obstacle or a flying platform (arcane sanctuary). Game total time: 16.20s" supervisor=Hammer```

Also retested chicken on souls and dolls in private games. Neither function is working. When teleing to throne it had souls and dolls on the way and doesnt leave. However i see in the logs sometimes it will show ```time=23:35:12 level=INFO msg="Triggering chicken action"``` without the health amount so maybe that is chickening for souls at some point

**Comment by divineblade7** [comment]
Sure, i pulled the latest @hectorgimenez  but its closing koolo as soon as it gets in game.  not sure why yet. log only gets as far as:

``` time=11:18:53 level=INFO msg="Waiting for character selection screen..."
time=11:19:12 level=INFO msg="Character selection screen found"
time=11:19:12 level=INFO msg="Selecting character..."
time=11:19:14 level=INFO msg="Character found"
time=11:19:20 level=DEBUG msg="Fetching map data..." ```

but i am unsure the reason, the prior build from commit: e0840d6eb2ec1cc4dbb2711717422fd223d1febe is still running fine.

**Comment by hectorgimenez** [comment]
@divineblade7 can we close this issue?

**Comment by divineblade7** [comment]
I ran a few tests yesterday after the last issue was fixed, and i could try the new pathfinder improvements. I didnt experience any errors yet in the few runs i did like before. I will update if there are any more errors with those runs. Thank you!
