### ISSUE TITLE
Removing check if player is in town when taking tp causes kurast chest run to bug

### ISSUE THREAD

**Issue by dmelia** [hectorgimenez/koolo#224]
### Details

the removal of the following code :
`if d.PlayerUnit.Area.IsTown() {return}`
during the refactor of tp_actions.go, makes the lower kurast chest run bug (the player tries to open a portal in town).

### Version

dev

**Comment by hectorgimenez** [comment]
When is this happening? When going back to sell junk or what?

**Comment by dmelia** [comment]
This is sometimes happening with other runs too, it's not specifically the lower kurast chest run. I fixed it by reverting the code change to the ReturnTown() function in tp_actions.go
full code :
`func (b *Builder) ReturnTown() *StepChainAction {
	return NewStepChain(func(d game.Data) (steps []step.Step) {
		if d.PlayerUnit.Area.IsTown() {
			return
		}

		return []step.Step{
			step.OpenPortal(),
			step.InteractObject(object.TownPortal, func(d game.Data) bool {
				return d.PlayerUnit.Area.IsTown()
			}),
		}
	}, Resettable())
}`
