### ISSUE TITLE
Bot gets stuck on "hidden stash" in diablo run

### ISSUE THREAD

**Issue by dmelia** [hectorgimenez/koolo#231]
### Details

When killing monsters as a hammerdin, in close proximity to a large "hidden stash" container, after killing the monsters the bot keeps trying to "kill" the hidden stash and gets stuck.

### Version

dev

**Comment by theksk23** [comment]
That might also happen when traversing on act1 like the Monestary or Catacombs: Sometimes barrels do block the way of the character.

Was thinking along the lines of adding these types of objects to either the Door, or Chest routines, but did not further investigate what the correesponding implications would be.
I do recall kolbot rather aggressively popping them!
