### ISSUE TITLE
Has the teleportation range changed?

### ISSUE THREAD

**Issue by jang9824** [hectorgimenez/koolo#234]
### Details

(On all maps Sometimes, I can't find my way, and I keep writing teleports on the wall, walking in place)

This issue has improved since the e371613 commitment
But when I observed it, I found that it's still 
Sometimes teleporting on the wall, I checked that it was moving while walking in place
I was using the teleport to rub against the wall
Occurred if you are lucky to pass through

### Version

e371613

**Comment by hectorgimenez** [comment]
If you look at the logs, now every new game is logging the map seed in the log file (when fetching the map data). When this happens to you, please report the mapseed, difficulty and where the character was stuck (the place and what run you were doing), it will be very helpful to debug the problem

**Comment by jang9824** [comment]
time=23:33:52 level=WARN msg="Game finished with errors, reason: unrecoverable error occurred, game can not continue: attempt limit reached on step: MoveToStep: path could not be calculated, maybe there is an obstacle or a flying platform (arcane sanctuary). Game total time: 117.85s" supervisor=조선왕조실록샐록 mapSeed=1502982702
mapSeed=153091399
mapSeed=281227340
mapSeed=448375049
mapSeed=1502982702
mapSeed=1502982702
Game finished with errors, reason: unrecoverable error occurred, game can not continue: attempt limit reached on step: InteractObjectStep: object 59 could not be interacted. Game total time: 178.05s" supervisor=조선왕조실록샐록 
mapSeed=1983157186

Game finished with errors, reason: fatal error detected, Koolo will try to exit game and create a new one: Error occurred calculating path, destination point outside current level and matching level not found\n Stacktrace: goroutine 10 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/hectorgimenez/koolo/internal.(*Bot).Run.func2()\n\tgithub.com/hectorgimenez/koolo/internal/bot.go:73 +0x3d\npanic({0x9ac4e0?, 0xcb7160?})\n\truntime/panic.go:770 +0x132\ngithub.com/hectorgimenez/koolo/internal/pather.(*PathFinder).GetPath(_, {{{0x1400, 0x1798}, {0x0, 0x0, {0x0, 0x0}}, {0xc006582a00, 0x6, 0x8}, ...}, ...}, ...)\n\tgithub.com/hectorgimenez/koolo/internal/pather/path_finder.go:40 +0x10c5\ngithub.com/hectorgimenez/koolo/internal/action/step.(*MoveToStep).Run(_, {{{0x1400, 0x1798}, {0x0, 0x0, {0x0, 0x0}}, {0xc006582a00, 0x6, 0x8}, ...}, ...}, ...)\n\tgithub.com/hectorgimenez/koolo/internal/action/step/move_to.go:120 +0x874\ngithub.com/hectorgimenez/koolo/internal/action.(*StepChainAction).NextStep(_, {{{0x1400, 0x1798}, {0x0, 0x0, {0x0, 0x0}}, {0xc006582a00, 0x6, 0x8}, ...}, ...}, ...)\n\tgithub.com/hectorgimenez/koolo/internal/action/action_step_chain.go:47 +0x222\ngithub.com/hectorgimenez/koolo/internal/action.(*Chain).NextStep(_, {{{0x1400, 0x1798}, {0x0, 0x0, {0x0, 0x0}}, {0xc006582a00, 0x6, 0x8}, ...}, ...}, ...)\n\tgithub.com/hectorgimenez/koolo/internal/action/action_chain.go:48 +0x1f6\ngithub.com/hectorgimenez/koolo/internal/action.(*Chain).NextStep(_, {{{0x1400, 0x1798}, {0x0, 0x0, {0x0, 0x0}}, {0xc006582a00, 0x6, 0x8}, ...}, ...}, ...)\n\tgithub.com/hectorgimenez/koolo/internal/action/action_chain.go:48 +0x1f6\ngithub.com/hectorgimenez/koolo/internal/action.(*Chain).NextStep(_, {{{0x1400, 0x1798}, {0x0, 0x0, {0x0, 0x0}}, {0xc006582a00, 0x6, 0x8}, ...}, ...}, ...)\n\tgithub.com/hectorgimenez/koolo/internal/action/action_chain.go:48 +0x1f6\ngithub.com/hectorgimenez/koolo/internal.(*Bot).Run(0xc000118000, {0xcbdd40, 0xc001326230}, 0x0, {0xc00199d380, 0x5, 0x8})\n\tgithub.com/hectorgimenez/koolo/internal/bot.go:164 +0x199e\ngithub.com/hectorgimenez/koolo/internal.(*SinglePlayerSupervisor).Start.func1()\n\tgithub.com/hectorgimenez/koolo/internal/single_supervisor.go:71 +0x272\ncreated by github.com/hectorgimenez/koolo/internal.(*SinglePlayerSupervisor).Start in goroutine 36\n\tgithub.com/hectorgimenez/koolo/internal/single_supervisor.go:45 +0x188\n. Game total time: 2.00s" supervisor=조선왕조실록샐록 
mapSeed=1502982702

time=23:10:24 level=WARN msg="Game finished with errors, reason: unrecoverable error occurred, game can not continue: attempt limit reached on step: MoveToStep: path could not be calculated, maybe there is an obstacle or a flying platform (arcane sanctuary). Game total time: 90.41s" supervisor=조선왕조실록샐록 mapSeed=1502982702

Hell mode
tp and  baal,diabol ,nihlathak,pit
All hunts Occur frequently on specified maps

**Comment by hectorgimenez** [comment]
I think this should be fixed now

**Comment by jang9824** [comment]
> 이 문제는 이제 해결되어야 할 것 같아요

Thank you always.
I'll apply the latest commit and proceed with the test
If there's no problem, I'll end it

If you have any questions, I'll give you feedback
