### ISSUE TITLE
Errors while identifying 1-cell item

### ISSUE THREAD

**Issue by xg6636** [hectorgimenez/koolo#235]
### Details

when there were 2 1-cell items, the error occured, the cursor became one of the items, maybe a ring or 1 small charm,
and the bot would try to put the item into the inventory , but it couldn't, because the inventoy window was closed.

if the bot could identify items by Cain, maybe those errors wouldn't happen.

### Version

dev

**Comment by divineblade7** [comment]
It ran out of id scrolls during the identify procedure. it seems to only check if it has any before starting. then will fill up at set points. but if u only have 4 scrolls and 5 items to id in bags that will happen. its done that to me a few times too

**Comment by xg6636** [comment]
> It ran out of id scrolls during the identify procedure. it seems to only check if it has any before starting. then will fill up at set points. but if u only have 4 scrolls and 5 items to id in bags that will happen. its done that to me a few times too

in my cases, there were enough id scrolls, the error happened while there were 5 or 12 id scrolls.
