### ISSUE TITLE
Not a bug but a request

### ISSUE THREAD

**Issue by imneckro** [hectorgimenez/koolo#239]
### Details

1)It would be great if bot could recognize diablo walk ingame and kill him before creating new game.
Thisway ,walks wouldn't go wasted.

I've already stashed my char's Anni, so bot could pick up new anni if Uber Diablo spawns.

2)Additionally after killing him, would be great if already got anni in inventory, 
 a) return to town and stash inventory's anni in shared tab, 
 b) return to Diablo's corpse and pick up new found anni,
 c) return to town and stash it in shared tab,
 d) get back from stash the old anni.

### Version

v0.4.0-beta6

### Logs

request

**Comment by xg6636** [comment]
maybe an easier solution: chicken while meeting diablo clone.

**Comment by divineblade7** [comment]
> maybe an easier solution: chicken while meeting diablo clone.

His request was to kill dclone if he spawned in game even if he wasn’t encountered yet. As far as I understand.

**Comment by imneckro** [comment]
> > maybe an easier solution: chicken while meeting diablo clone.
> 
> 
> 
> His request was to kill dclone if he spawned in game even if he wasn’t encountered yet. As far as I understand. 

Exactly

**Comment by hectorgimenez** [comment]
Maybe what we can do is go to town and stay there? Killing dclone will not be easy for most characters and even if we kill him we will need to deal with stashing current annihilus into the shared stash and then picking up the new one. Of course it's doable but not sure if it's worth the effort The issue list is very long right now

**Comment by imneckro** [comment]
> Maybe what we can do is go to town and stay there? Killing dclone will not be easy for most characters and even if we kill him we will need to deal with stashing current annihilus into the shared stash and then picking up the new one. Of course it's doable but not sure if it's worth the effort The issue list is very long right now

Thanks a lot for all your effort. I understand completely.
