### ISSUE TITLE
Companion mode stuck on champs select

### ISSUE THREAD

**Issue by totodelee** [hectorgimenez/koolo#243]
### Details

Hi guys, 

Koolo work nicely overall on my side, but when i try companion mode it can't find my character.

let me know if i can give you more info

### Version

v0.4.6

### Logs

time=23:33:37 level=INFO msg="Waiting for character selection screen..."
time=23:34:38 level=INFO msg="Character selection screen found"
time=23:34:38 level=INFO msg="Selecting character..."
time=23:34:39 level=ERROR msg="error running supervisor Paladin: error waiting for character selection screen: character tototestte not found"

**Comment by totodelee** [comment]
I've built from latest commit

**Comment by divineblade7** [comment]
Can you share a pic of your character select screen please @totodelee

**Comment by totodelee** [comment]
keek, i deactivated the companion mode but it doesn't work anymore.

i prefer not share my character name.

but i was working nicely until today

**Comment by divineblade7** [comment]
Names are case sensitive so it is possible that could be an issue. But more information is needed to assist with some issues. I understand, be advised support will be more limited without some information. 

There was a d2r update pushed today that caused issues.

**Comment by totodelee** [comment]
update for the new d2r patch fixed the issue. 

 [9457712](https://github.com/hectorgimenez/koolo/commit/9457712c3ac7d82053baed25972042b6a42799fe)

**Comment by totodelee** [comment]
update for the new d2r patch fixed the issue. 

 [9457712](https://github.com/hectorgimenez/koolo/commit/9457712c3ac7d82053baed25972042b6a42799fe)
