### ISSUE TITLE
Chaos Sanctuary. Can't open seal. No TZ.

### ISSUE THREAD

**Issue by nydicil** [hectorgimenez/koolo#244]
### Details

It was working a few days ago, now everytime my Nova Sorc stucks during opening the seal. She is trying to teleport into it.

![be69fef3200c4f9d5b285b492e441867](https://github.com/hectorgimenez/koolo/assets/169338642/1049083b-6b10-46d5-b709-dabf820c6a6c)

### Version

43b22d8 (up to date commit)

### Logs

time=14:42:42 level=DEBUG msg="Monster detected close to the player, casting Nova over it"
time=14:42:42 level=DEBUG msg="Clearing area..." monsterID=362
time=14:42:42 level=DEBUG msg="Clearing area..." monsterID=312
time=14:42:47 level=DEBUG msg="Clearing area..." monsterID=310
time=14:42:47 level=DEBUG msg="Monster detected close to the player, casting Nova over it"
time=14:42:48 level=DEBUG msg="Clearing area..." monsterID=310
time=14:42:48 level=DEBUG msg="Clearing area..." monsterID=312
time=14:42:53 level=DEBUG msg="Clearing area..." monsterID=310
time=14:42:53 level=DEBUG msg="Clearing area..." monsterID=310
time=14:42:54 level=DEBUG msg="Clearing area..." monsterID=310
time=14:42:54 level=DEBUG msg="Clearing area..." monsterID=312
time=14:42:55 level=DEBUG msg="Clearing area..." monsterID=312
time=14:42:56 level=DEBUG msg="Clearing area..." monsterID=310
time=14:42:57 level=DEBUG msg="Clearing area..." monsterID=310
time=14:42:57 level=DEBUG msg="Monster detected close to the player, casting Nova over it"
time=14:42:58 level=DEBUG msg="Moving to next seal" seal=1
time=14:42:58 level=DEBUG msg="Seal found, start teleporting" seal=1
time=14:43:03 level=DEBUG msg="Moving to next seal" seal=1
time=14:43:03 level=DEBUG msg="We are close enough to the seal" seal=1
time=14:43:03 level=DEBUG msg="Clearing area..." monsterID=306
time=14:43:04 level=DEBUG msg="CTA found: swapping weapon and casting Battle Command / Battle Orders"
time=14:43:04 level=DEBUG msg=Buffing...
time=14:43:16 level=DEBUG msg="Seal activated, waiting for elite group to spawn" seal=1
time=14:43:16 level=DEBUG msg="Moving to next seal" seal=2
time=14:43:16 level=DEBUG msg="Seal found, start teleporting" seal=2
time=14:43:17 level=DEBUG msg="Moving to next seal" seal=2
time=14:43:17 level=DEBUG msg="We are close enough to the seal" seal=2
time=14:43:17 level=DEBUG msg="Clearing area..." monsterID=306
time=14:43:50 level=WARN msg="Game finished with errors, reason: unrecoverable error occurred, game can not continue: attempt limit reached on step: MoveToStep: path could not be calculated, maybe there is an obstacle or a flying platform (arcane sanctuary). Game total time: 138.73s" supervisor=lulaaabe mapSeed=1019097224

**Comment by childofwar1980** [comment]
what version are you using? most of us cant even get the bot to start after the d2r update

**Comment by nydicil** [comment]
Ver is written above the log. It's the newest version. I pulled the latest version by "git pull" in git bash and then rebuilt.
Yeah, bot is working really bad recently, I run it only on Pit, works almost flawless atm.

**Comment by dmelia** [comment]
FOH paladin is the same, gets stuck trying to "attack" the seal

**Comment by Quick-Benn** [comment]
The last version to fix the d2r patch problem is working for me. I don’t run chaos, but I also have errors every run with FOH paladin without teleport (index out of range).
It seems to come from the previous commit (improve pathfinding precision). I rebuilt without this commit and I had only 1 error in 2 hours of run.

**Comment by childofwar1980** [comment]
i just pulled the latest build and run a nova sorc and can confirm the seal problem still exists, she just teleports into the seal forever and never activates it

**Comment by hectorgimenez** [comment]
> i just pulled the latest build and run a nova sorc and can confirm the seal problem still exists, she just teleports into the seal forever and never activates it

Yes, new version just fixed the game update, nothing about the seal yet

**Comment by childofwar1980** [comment]
this issue appears to be fixed in the latest build
