### ISSUE TITLE
Koolo doesnt recognize character on selection screen after last update for new d2r version

### ISSUE THREAD

**Issue by nydicil** [hectorgimenez/koolo#245]
### Details

Stucks on selection screen, doesn't create the game. 

![988099db2def0bcc57b3e81e89ed36dc](https://github.com/hectorgimenez/koolo/assets/169338642/6554be4b-aa72-4d1b-8fc9-b96becab7d7d)

### Version

9457712

### Logs

time=18:29:39 level=INFO msg="Waiting for character selection screen..."

**Comment by totodelee** [comment]
are you sure you launching the new build ?

had same issue but update [9457712](https://github.com/hectorgimenez/koolo/commit/9457712c3ac7d82053baed25972042b6a42799fe) fixed the issue

**Comment by nydicil** [comment]
yes, but think d2go has to be fixed, not koolo by itself

**Comment by JayCheung777** [comment]
this issue happens again. I think it caused by latest d2r update at 3rd Dec.

**Comment by JayCheung777** [comment]
I'm not sure if these 2 files should be updated. 
go.mod :   
github.com/hectorgimenez/d2go v0.0.0-20240522151855-b42823864338

go.sum: 
github.com/hectorgimenez/d2go v0.0.0-20240522151855-b42823864338 h1:1gSN6fKcwUlZH+P1TYU1npNSdWngtbG4r8CihjOWO8A=
github.com/hectorgimenez/d2go v0.0.0-20240522151855-b42823864338/go.mod h1:1U3l3Ma//LIj2CAOcP3Yg3s84LAWrI6F8E+38B4su9Y=
