### ISSUE TITLE
Level script stuck selecting skills

### ISSUE THREAD

**Issue by onyxbadge** [hectorgimenez/koolo#247]
### Details

I load the character into the game it checks the quests and then opens the skills at the bottom of the screen. It just keeps opening and closing. I tried having skills (attack and tp) with and without hotkeys but it made no difference. Can anyone tell me if I've done something wrong or is it the bot?

### Version

6242d17

### Logs

In the log the final entry is checking for items to stash 

time=21:13:48 level=DEBUG msg="Checking for items to stash..."

**Comment by hectorgimenez** [comment]
Hello, yeah it's not working well, for now you can disable it under the leveling run and assign skill to buttons manually

![image](https://github.com/hectorgimenez/koolo/assets/12543131/0dc0170d-ef11-4e6d-a08e-5764575d2c22)

**Comment by onyxbadge** [comment]
Thanks for that I'm not sure how I missed that setting 😅
