### ISSUE TITLE
Failed to enter Countess' tower level 2 and Pit

### ISSUE THREAD

**Issue by xg6636** [hectorgimenez/koolo#248]
### Details

the bot could find the path and go to the enterance, however, it walked around the enterance again and again,
it could not enter it.
these issues happened a few days ago, they did not happened often those days.
after recent 2 commits, those happened very frequently, almost happened every run.

### Version

dev

### Logs

time=16:06:45 level=INFO msg="Running: countess"
time=16:06:47 level=INFO msg="Current life is 68%, healing on NPC"
time=16:06:58 level=INFO msg="Key binding not found, skipping buff" skill=""
time=16:09:23 level=INFO msg="Key binding not found, skipping buff" skill=""
time=16:09:53 level=INFO msg="Key binding not found, skipping buff" skill=""
time=16:10:23 level=INFO msg="Key binding not found, skipping buff" skill=""
time=16:10:53 level=INFO msg="Key binding not found, skipping buff" skill=""
time=16:11:23 level=INFO msg="Key binding not found, skipping buff" skill=""
time=16:11:53 level=INFO msg="Key binding not found, skipping buff" skill=""
time=16:12:23 level=INFO msg="Key binding not found, skipping buff" skill=""
time=16:12:53 level=INFO msg="Key binding not found, skipping buff" skill=""
time=16:13:23 level=INFO msg="Key binding not found, skipping buff" skill=""
time=16:13:53 level=INFO msg="Key binding not found, skipping buff" skill=""
time=16:14:23 level=INFO msg="Key binding not found, skipping buff" skill=""
time=16:14:53 level=INFO msg="Key binding not found, skipping buff" skill=""
time=16:15:05 level=WARN msg="Game finished with errors, reason: max game length reached, try to exit game: 500.03. Game total time: 500.06s" supervisor=AnaaNova mapSeed=1973263323

**Comment by hectorgimenez** [comment]
try again with the latest commits, we are playing a little bit with the pather, so you can expect some unstability
