### ISSUE TITLE
Level script wont start moving

### ISSUE THREAD

**Issue by onyxbadge** [hectorgimenez/koolo#252]
### Details

I start the run. It makes the game and goes through the town checks then crashes. I'm using the latest release of the bot.

### Version

v0.4.0

### Logs

time=19:24:37 level=DEBUG msg="Checking for items to stash..."
time=19:24:37 level=DEBUG msg="Checking for items to stash..."
time=19:24:37 level=INFO msg="Starting Den of Evil run"
time=19:24:37 level=ERROR msg="fatal error detected, forcing shutdown" supervisor=Pal error="runtime error: index out of range [200] with length 200" stacktrace="goroutine 220 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/hectorgimenez/koolo/internal.(*SupervisorManager).Start.func2.1()\n\tgithub.com/hectorgimenez/koolo/internal/manager.go:76 +0x108\npanic({0x1266200?, 0xc0000b9d40?})\n\truntime/panic.go:770 +0x132\ngithub.com/hectorgimenez/koolo/internal/pather.(*World).To(...)\n\tgithub.com/hectorgimenez/koolo/internal/pather/world.go:59\ngithub.com/hectorgimenez/koolo/internal/pather.(*PathFinder).GetPath(_, {{{0x15e0, 0x1130}, {0x0, 0x0, {0x0, 0x0}}, {0xc000daee00, 0x5, 0x8}, ...}, ...}, ...)\n\tgithub.com/hectorgimenez/koolo/internal/pather/path_finder.go:138 +0xaea\ngithub.com/hectorgimenez/koolo/internal/action.(*Builder).MoveToArea.func2({{{0x15e0, 0x1130}, {0x0, 0x0, {0x0, 0x0}}, {0xc000daee00, 0x5, 0x8}, {0xc000e60008, ...}, ...}, ...})\n\tgithub.com/hectorgimenez/koolo/internal/action/move.go:80 +0x5d7\ngithub.com/hectorgimenez/koolo/internal/action.(*Builder).MoveTo.func1({{{0x15e0, 0x1130}, {0x0, 0x0, {0x0, 0x0}}, {0xc000daee00, 0x5, 0x8}, {0xc000e60008, ...}, ...}, ...})\n\tgithub.com/hectorgimenez/koolo/internal/action/move.go:126 +0xcb\ngithub.com/hectorgimenez/koolo/internal/action.(*Chain).NextStep(_, {{{0x15e0, 0x1130}, {0x0, 0x0, {0x0, 0x0}}, {0xc000daee00, 0x5, 0x8}, ...}, ...}, ...)\n\tgithub.com/hectorgimenez/koolo/internal/action/action_chain.go:34 +0x65\ngithub.com/hectorgimenez/koolo/internal/action.(*Chain).NextStep(_, {{{0x15e0, 0x1130}, {0x0, 0x0, {0x0, 0x0}}, {0xc000daee00, 0x5, 0x8}, ...}, ...}, ...)\n\tgithub.com/hectorgimenez/koolo/internal/action/action_chain.go:48 +0x1f6\ngithub.com/hectorgimenez/koolo/internal/action.(*Chain).NextStep(_, {{{0x15e0, 0x1130}, {0x0, 0x0, {0x0, 0x0}}, {0xc000daee00, 0x5, 0x8}, ...}, ...}, ...)\n\tgithub.com/hectorgimenez/koolo/internal/action/action_chain.go:48 +0x1f6\ngithub.com/hectorgimenez/koolo/internal.(*Bot).Run(0xc000af4000, {0x14cfa20, 0xc0009100a0}, 0x1, {0xc000d17020, 0x1, 0x1})\n\tgithub.com/hectorgimenez/koolo/internal/bot.go:177 +0x1c36\ngithub.com/hectorgimenez/koolo/internal.(*SinglePlayerSupervisor).Start(0xc000720040)\n\tgithub.com/hectorgimenez/koolo/internal/single_supervisor.go:70 +0x485\ngithub.com/hectorgimenez/koolo/internal.(*SupervisorManager).Start.func2()\n\tgithub.com/hectorgimenez/koolo/internal/manager.go:82 +0xa2\ncreated by github.com/hectorgimenez/koolo/internal.(*SupervisorManager).Start in goroutine 239\n\tgithub.com/hectorgimenez/koolo/internal/manager.go:69 +0x21d\n"
time=19:24:37 level=INFO msg=Stopping... configuration=Pal
time=19:24:37 level=INFO msg="Finished stopping" configuration=Pal

**Comment by mista79** [comment]
Me too, it made the game and stayed in town, but I didn't see it crash.
This character always right-clicks the skill menu

**Comment by Millionaar** [comment]
any luck? mine was having the same issue yesterday. I tried again today and it seems to have fixed that issue. 
however it now runs the den of evil but can't progress any further. Seems like the new Blizzard patch broke a bunch of things..

**Comment by theksk23** [comment]
Adding it to this bugreport,  stuff like  `if !d.Quests[quest.Act1DenOfEvil].Completed() {` seems to have stopped working (since patch?) in general, these states are never completed.

**Comment by hectorgimenez** [comment]
yup, leveling is still broken (never worked well tho)

**Comment by onyxbadge** [comment]
I couldn't get it to work all so I just manually leveled the char. The rest of the bot had been working great for me otherwise so thanks for all the hard work
