### ISSUE TITLE
How to change items for gambling?

### ISSUE THREAD

**Issue by nydicil** [hectorgimenez/koolo#259]
I'd like to change items for gambling, now char is buying circlet amus and rings. 
How to disable circlets? Can't find where it is, anyone could help?

**Comment by theksk23** [comment]
While that setting is not exposed to GUI, you can modify it in the characters config directly, see: https://github.com/hectorgimenez/koolo/blob/67b8becf4df0027962604806a86ba8858e46b3ab/config/template/config.yaml#L176

**Comment by nydicil** [comment]
Thanks mate, now you helped me 🙂
