### ISSUE TITLE
Bot will hold item and do nothing - video of it happening

### ISSUE THREAD

**Issue by jik0n** [hectorgimenez/koolo#26]
Bot will randomly grab an item and hold it and do nothing except move the mouse around the screen.
Hyper-V vm my mouse starts the bot then I immediately remove it from the VM screen and never place it back unless I need to interrupt the bot to either fix this issue or start it again from crash. I'm including a youtube video clip of it happening. You can see the sorc orb weapon on the mouse  moving around doing nothing.

https://youtu.be/zQmX3GTqktc?si=JjlML23mf0vqVY1n

**Comment by hectorgimenez** [comment]
Could you check if when this happens the ID tome is empty? this was reported before, I think it should be fixed with latest commits from today, if you are building it from source code you can pull latest changes in main branch and build it again

**Comment by jik0n** [comment]
@hectorgimenez I increased how many bosses the bot does to recreate the issue and thats exactly what happened. Bot ran out of ID scrolls and it happened again. I trimmed my pickit down and cut the bosses down to 2-3 and it wasn't happening again which means the bot had time to shop more.

I'm not building from source because I'm a typical end user that honestly couldn't figure that part out. I'm happy to wait for another release though.

Thanks for all you do on this project and for helping, I'll trim my config back down to lower boss count for the time being until a new release.

**Comment by jik0n** [comment]
@hectorgimenez is it possible to increase the frequency in which the bot checks and/or buys ID / TP scrolls? Mine just got stuck with no TPs somewhere

**Comment by jik0n** [comment]
Issue with bot holding an item just happened with ID tome full

**Comment by jik0n** [comment]
@hectorgimenez if you're not running into the issue could you please share the specific pickit you're using? I suspect the bot is having issues with stash / inv management depending on the specific item. I'd like to compare it to mine to see differences and maybe figure out what gear? I could be way off here and completely wrong but its the only thing I can think of after pondering this issue and watching the behavior.
