### ISSUE TITLE
bot can not login

### ISSUE THREAD

**Issue by JoseeePZ** [hectorgimenez/koolo#260]
### Details

bot can not login into my bnet. Tried to add the commandline arguments -username -password -address manually but that also didnt work. MFA is disabled. When i am trying to log in into my bnet i have to solve a captcha. Can this be the issue?

### Version

dev

### Logs

time=13:25:01 level=INFO msg="Waiting for character selection screen..."

**Comment by theksk23** [comment]
Yap, if you have been flagged for "please solve this capture"; the bot cannot login.
That can to my experience happen if you
- try to login with non-valid credentials too often
- sucessfully login too often in time-window (like restarting 4 Bots 10 times in 10 minutes? dont do that..) 

It might help if you can get hold of a new public IP address (try restarting your router if you have a dynamic IP address).
Waiting does also help, give it 12 hours maybe?

**Comment by JoseeePZ** [comment]
yep, turning on vpn worked for me
