### ISSUE TITLE
Stuck in offline mode for 1 account

### ISSUE THREAD

**Issue by crackedsash** [hectorgimenez/koolo#262]
Stuck in offline on one bot but if i switch account it works properly… suspect it has sometjing to do with sign usage in email adDress…. Example email: gosu@gmail.com works fine but when i switch to gosu.hasu-life@gmail.com its stuck in offline mode…

**Comment by theksk23** [comment]
Are you positive these credentials are valid?
Have you tried logging in using Battle.net Launcher? 

If you get a Captcha on login using launcher, bot will not be able to use this account, also see: https://github.com/hectorgimenez/koolo/issues/260

As far as (my interpretation of) the bot is concerned, that username/E-Mail is just a string: https://github.com/hectorgimenez/koolo/blob/67b8becf4df0027962604806a86ba8858e46b3ab/internal/config/config.go#L56

**Comment by crackedsash** [comment]
Uff, figured it out was a space after email i Didnt see. Thanks for Help guys
