### ISSUE TITLE
Running: diablo Koolo has ended

### ISSUE THREAD

**Issue by jang9824** [hectorgimenez/koolo#264]
### Details

![image](https://github.com/hectorgimenez/koolo/assets/164779982/ec69a4d3-8594-49ef-b325-9aa23074ef0f)
1. Koolo (sometimes) stops operating at this position

2. Move waypoints at unspecified tz

Game ending. Joining the game, etc 
It's happening again.

### Version

67b8bec

### Logs

time=03:01:35 level=INFO msg="Running: diablo"
time=03:01:35 level=DEBUG msg="Checking for character corpse..."
time=03:01:35 level=DEBUG msg="Character corpse not found :D"
time=03:01:35 level=DEBUG msg="Checking for items to identify..."
time=03:01:35 level=DEBUG msg="No items to identify..."
time=03:01:35 level=DEBUG msg="Belt Stats Health: 4/4 healing, 4/4 mana, 8/8 rejuv."
time=03:01:35 level=DEBUG msg="Checking for items to stash..."
time=03:01:35 level=DEBUG msg="Checking for items to stash..."
time=03:01:35 level=DEBUG msg="Monster detected close to the player, casting Nova over it"
time=03:01:35 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance."
time=03:01:36 level=DEBUG msg="Monster detected close to the player, casting Nova over it"
time=03:01:38 level=DEBUG msg="Monster detected close to the player, casting Nova over it"
time=03:01:38 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance."
time=03:01:40 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance."
time=03:01:40 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=03:01:40 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance."
time=03:01:40 level=DEBUG msg="Load completed, continuing execution"
time=03:01:41 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance."
time=03:01:41 level=DEBUG msg="Monster detected close to the player, casting Nova over it"
time=03:01:42 level=DEBUG msg="Monster detected close to the player, casting Nova over it"
time=03:01:42 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance."
time=03:01:43 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance."
time=03:01:44 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance."
time=03:01:44 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance."
time=03:01:46 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance."
time=03:01:46 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance."
time=03:01:48 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance."
time=03:01:49 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance."
time=03:01:49 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance."
time=03:01:49 level=DEBUG msg="Item Detected: GrimHelm [6] at X:25112 Y:5922"
time=03:01:50 level=DEBUG msg="Picking up: Grim Helm [Rare]"
time=03:01:50 level=INFO msg="Item picked up: Grim Helm [Rare]"
time=03:01:50 level=DEBUG msg="Item Detected: Ring [6] at X:25093 Y:5900"
time=03:01:51 level=DEBUG msg="Picking up: Ring [Rare]"
time=03:01:51 level=INFO msg="Item picked up: Ring [Rare]"
time=03:01:52 level=DEBUG msg="Item Detected: WarScepter [6] at X:25091 Y:5898"
time=03:01:52 level=DEBUG msg="Picking up: War Scepter [Rare]"
time=03:01:52 level=ERROR msg="fatal error detected, forcing shutdown" supervisor=태종 error="runtime error: index out of range [797] with length 600" stacktrace="goroutine 38360 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/hectorgimenez/koolo/internal.(*SupervisorManager).Start.func2.1()\n\tgithub.com/hectorgimenez/koolo/internal/manager.go:76 +0x108\npanic({0x1246200?, 0xc017192c18?})\n\truntime/panic.go:770 +0x132\ngithub.com/hectorgimenez/koolo/internal/pather.(*World).SetTile(...)\n\tgithub.com/hectorgimenez/koolo/internal/pather/world.go:33\ngithub.com/hectorgimenez/koolo/internal/pather.(*PathFinder).GetPath(_, {{{0x1d4c, 0x1388}, {0x0, 0x0, {0x0, 0x0}}, {0xc015463688, 0x9, 0x11}, ...}, ...}, ...)\n\tgithub.com/hectorgimenez/koolo/internal/pather/path_finder.go:133 +0xae7\ngithub.com/hectorgimenez/koolo/internal/action/step.(*MoveToStep).Run(_, {{{0x1d4c, 0x1388}, {0x0, 0x0, {0x0, 0x0}}, {0xc015463688, 0x9, 0x11}, ...}, ...}, ...)\n\tgithub.com/hectorgimenez/koolo/internal/action/step/move_to.go:126 +0x874\ngithub.com/hectorgimenez/koolo/internal/action.(*StepChainAction).NextStep(_, {{{0x1d4c, 0x1388}, {0x0, 0x0, {0x0, 0x0}}, {0xc015463688, 0x9, 0x11}, ...}, ...}, ...)\n\tgithub.com/hectorgimenez/koolo/internal/action/action_step_chain.go:47 +0x222\ngithub.com/hectorgimenez/koolo/internal/action.(*Chain).NextStep(_, {{{0x1d4c, 0x1388}, {0x0, 0x0, {0x0, 0x0}}, {0xc015463688, 0x9, 0x11}, ...}, ...}, ...)\n\tgithub.com/hectorgimenez/koolo/internal/action/action_chain.go:48 +0x1f6\ngithub.com/hectorgimenez/koolo/internal.(*Bot).Run(0xc001424b80, {0x14af3a0, 0xc000c28000}, 0x0, {0xc00ae22780, 0x6, 0x8})\n\tgithub.com/hectorgimenez/koolo/internal/bot.go:177 +0x1c36\ngithub.com/hectorgimenez/koolo/internal.(*SinglePlayerSupervisor).Start(0xc000e1a008)\n\tgithub.com/hectorgimenez/koolo/internal/single_supervisor.go:70 +0x485\ngithub.com/hectorgimenez/koolo/internal.(*SupervisorManager).Start.func2()\n\tgithub.com/hectorgimenez/koolo/internal/manager.go:82 +0xa2\ncreated by github.com/hectorgimenez/koolo/internal.(*SupervisorManager).Start in goroutine 37284\n\tgithub.com/hectorgimenez/koolo/internal/manager.go:69 +0x21d\n"
time=03:01:52 level=INFO msg=Stopping... configuration=태종
time=03:01:52 level=INFO msg="Finished stopping" configuration=태종
[koolo-log-2024-05-26-13-53-11.txt](https://github.com/hectorgimenez/koolo/files/15448506/koolo-log-2024-05-26-13-53-11.txt)

**Comment by theksk23** [comment]
can confirm these are happening (less since [67b8bec](https://github.com/hectorgimenez/koolo/commit/67b8becf4df0027962604806a86ba8858e46b3ab) but still) across the board, also saw negative values for the ouf of range if thats worth anything..

**Comment by nydicil** [comment]
True, have the same problem

**Comment by jang9824** [comment]
time=18:10:55 level=INFO msg="Running: diablo"
time=18:10:55 level=DEBUG msg="Checking for character corpse..."
time=18:10:55 level=DEBUG msg="Character corpse not found :D"
time=18:10:55 level=DEBUG msg="Checking for items to identify..."
time=18:10:55 level=INFO msg="Identifying 1 items..."
time=18:10:56 level=DEBUG msg="Load completed, continuing execution"
time=18:10:56 level=DEBUG msg="CTA found: swapping weapon and casting Battle Command / Battle Orders"
time=18:10:56 level=DEBUG msg=Buffing...
time=18:10:57 level=INFO msg="Visiting vendor..." forceRefill=false
time=18:10:57 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=18:10:58 level=DEBUG msg="Load completed, continuing execution"
time=18:10:58 level=DEBUG msg="CTA found: swapping weapon and casting Battle Command / Battle Orders"
time=18:10:58 level=DEBUG msg=Buffing...
time=18:11:02 level=DEBUG msg="Buying: 1 Healing potions and 0 Mana potions"
time=18:11:04 level=DEBUG msg="Purchased Super Healing Potion [X:9 Y:9]"
time=18:11:05 level=DEBUG msg="Item Amulet [Magic] sold"
time=18:11:06 level=DEBUG msg="Checking for items to stash..."
time=18:11:06 level=DEBUG msg="Checking for items to stash..."
time=18:11:07 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance."
time=18:11:07 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance."
time=18:11:08 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=18:11:08 level=DEBUG msg="Load completed, continuing execution"
time=18:11:08 level=DEBUG msg="Monster detected close to the player, casting Nova over it"
time=18:11:09 level=DEBUG msg="Monster detected close to the player, casting Nova over it"
time=18:11:10 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance."
time=18:11:10 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance."
time=18:11:11 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance."
time=18:11:11 level=DEBUG msg="CTA found: swapping weapon and casting Battle Command / Battle Orders"
time=18:11:11 level=DEBUG msg=Buffing...
time=18:11:12 level=DEBUG msg="Monster detected close to the player, casting Nova over it"
time=18:11:13 level=DEBUG msg="Item Detected: HornedHelm [4] at X:25115 Y:5913"
time=18:11:15 level=DEBUG msg="Picking up: Horned Helm [Magic]"
time=18:11:15 level=INFO msg="Item picked up: Horned Helm [Magic]"
time=18:11:17 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance."
time=18:11:19 level=DEBUG msg="Clearing area..." monsterID=478
time=18:11:20 level=DEBUG msg="Clearing area..." monsterID=478
time=18:11:21 level=DEBUG msg="Clearing area..." monsterID=697
time=18:11:22 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance."
time=18:11:23 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance."
time=18:11:23 level=DEBUG msg="Clearing area..." monsterID=478
time=18:11:24 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance."
time=18:11:24 level=DEBUG msg="Clearing area..." monsterID=603
time=18:11:25 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance."
time=18:11:25 level=DEBUG msg="Clearing area..." monsterID=603
time=18:11:25 level=DEBUG msg="Clearing area..." monsterID=478
time=18:11:25 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance."
time=18:11:25 level=ERROR msg="fatal error detected, forcing shutdown" supervisor=조선왕조실록샐록 error="runtime error: index out of range [799] with length 600" stacktrace="goroutine 72 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/hectorgimenez/koolo/internal.(*SupervisorManager).Start.func2.1()\n\tgithub.com/hectorgimenez/koolo/internal/manager.go:76 +0x108\npanic({0xb46160?, 0xc0119cf248?})\n\truntime/panic.go:770 +0x132\ngithub.com/hectorgimenez/koolo/internal/pather.(*World).SetTile(...)\n\tgithub.com/hectorgimenez/koolo/internal/pather/world.go:33\ngithub.com/hectorgimenez/koolo/internal/pather.(*PathFinder).GetPath(_, {{{0x1d4c, 0x1388}, {0x0, 0x0, {0x0, 0x0}}, {0xc00d23ed08, 0x22, 0x23}, ...}, ...}, ...)\n\tgithub.com/hectorgimenez/koolo/internal/pather/path_finder.go:134 +0xa1a\ngithub.com/hectorgimenez/koolo/internal/pather.(*PathFinder).GetClosestWalkablePath(_, {{{0x1d4c, 0x1388}, {0x0, 0x0, {0x0, 0x0}}, {0xc00d23ed08, 0x22, 0x23}, ...}, ...}, ...)\n\tgithub.com/hectorgimenez/koolo/internal/pather/path_finder.go:162 +0x17a\ngithub.com/hectorgimenez/koolo/internal/action/step.(*MoveToStep).Run(_, {{{0x1d4c, 0x1388}, {0x0, 0x0, {0x0, 0x0}}, {0xc00d23ed08, 0x22, 0x23}, ...}, ...}, ...)\n\tgithub.com/hectorgimenez/koolo/internal/action/step/move_to.go:127 +0x87a\ngithub.com/hectorgimenez/koolo/internal/action.(*StepChainAction).NextStep(_, {{{0x1d4c, 0x1388}, {0x0, 0x0, {0x0, 0x0}}, {0xc00d23ed08, 0x22, 0x23}, ...}, ...}, ...)\n\tgithub.com/hectorgimenez/koolo/internal/action/action_step_chain.go:47 +0x222\ngithub.com/hectorgimenez/koolo/internal/action.(*Chain).NextStep(_, {{{0x1d4c, 0x1388}, {0x0, 0x0, {0x0, 0x0}}, {0xc00d23ed08, 0x22, 0x23}, ...}, ...}, ...)\n\tgithub.com/hectorgimenez/koolo/internal/action/action_chain.go:48 +0x1f6\ngithub.com/hectorgimenez/koolo/internal.(*Bot).Run(0xc00146c080, {0xdaf740, 0xc0068a8410}, 0x0, {0xc0040a2380, 0x6, 0x8})\n\tgithub.com/hectorgimenez/koolo/internal/bot.go:177 +0x1c36\ngithub.com/hectorgimenez/koolo/internal.(*SinglePlayerSupervisor).Start(0xc000062000)\n\tgithub.com/hectorgimenez/koolo/internal/single_supervisor.go:70 +0x485\ngithub.com/hectorgimenez/koolo/internal.(*SupervisorManager).Start.func2()\n\tgithub.com/hectorgimenez/koolo/internal/manager.go:82 +0xa2\ncreated by github.com/hectorgimenez/koolo/internal.(*SupervisorManager).Start in goroutine 11\n\tgithub.com/hectorgimenez/koolo/internal/manager.go:69 +0x21d\n"
time=18:11:25 level=INFO msg=Stopping... configuration=조선왕조실록샐록
time=18:11:25 level=INFO msg="Finished stopping" configuration=조선왕조실록샐록
