### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by Prestapro** [hectorgimenez/koolo#27]
Interesting bot, try to use.
Try to start but get this error.
Please help me.

`# gocv.io/x/gocv
..\go\pkg\mod\gocv.io\x\gocv@v0.33.0\calib3d_string.go:3:9: undefined: CalibFlag
..\go\pkg\mod\gocv.io\x\gocv@v0.33.0\calib3d_string.go:29:9: undefined: CalibCBFlag
..\go\pkg\mod\gocv.io\x\gocv@v0.33.0\core_string.go:3:9: undefined: MatType
..\go\pkg\mod\gocv.io\x\gocv@v0.33.0\core_string.go:57:9: undefined: CompareType
..\go\pkg\mod\gocv.io\x\gocv@v0.33.0\core_string.go:75:9: undefined: CovarFlags
..\go\pkg\mod\gocv.io\x\gocv@v0.33.0\core_string.go:93:9: undefined: DftFlags
..\go\pkg\mod\gocv.io\x\gocv@v0.33.0\core_string.go:113:9: undefined: RotateFlag
..\go\pkg\mod\gocv.io\x\gocv@v0.33.0\core_string.go:125:9: undefined: KMeansFlags
..\go\pkg\mod\gocv.io\x\gocv@v0.33.0\core_string.go:137:9: undefined: NormType
..\go\pkg\mod\gocv.io\x\gocv@v0.33.0\core_string.go:159:9: undefined: TermCriteriaType
..\go\pkg\mod\gocv.io\x\gocv@v0.33.0\core_string.go:159:9: too many errors
# github.com/robotn/gohook
..\go\pkg\mod\github.com\robotn\gohook@v0.41.0\event.go:51:10: undefined: addEvent
..\go\pkg\mod\github.com\robotn\gohook@v0.41.0\event.go:62:7: undefined: Start
..\go\pkg\mod\github.com\robotn\gohook@v0.41.0\event.go:75:18: undefined: KeyHold
..\go\pkg\mod\github.com\robotn\gohook@v0.41.0\event.go:83:18: undefined: KeyUp
..\go\pkg\mod\github.com\robotn\gohook@v0.41.0\event.go:95:22: undefined: KeyUp
..\go\pkg\mod\github.com\robotn\gohook@v0.41.0\event.go:96:4: undefined: End
..\go\pkg\mod\github.com\robotn\gohook@v0.41.0\event.go:113:7: undefined: Start
..\go\pkg\mod\github.com\robotn\gohook@v0.41.0\event.go:121:17: undefined: MouseMove
..\go\pkg\mod\github.com\robotn\gohook@v0.41.0\event.go:128:22: undefined: MouseDown
..\go\pkg\mod\github.com\robotn\gohook@v0.41.0\event.go:129:4: undefined: End
..\go\pkg\mod\github.com\robotn\gohook@v0.41.0\event.go:129:4: too many errors
# github.com/go-vgo/robotgo
..\go\pkg\mod\github.com\go-vgo\robotgo@v1.0.0-rc2.1\img.go:92:40: undefined: Bitmap
..\go\pkg\mod\github.com\go-vgo\robotgo@v1.0.0-rc2.1\img.go:107:38: undefined: Bitmap
..\go\pkg\mod\github.com\go-vgo\robotgo@v1.0.0-rc2.1\img.go:137:20: undefined: Bitmap
..\go\pkg\mod\github.com\go-vgo\robotgo@v1.0.0-rc2.1\screen.go:26:28: undefined: Rect
..\go\pkg\mod\github.com\go-vgo\robotgo@v1.0.0-rc2.1\robotgo_fn_v1.go:9:2: undefined: Move
..\go\pkg\mod\github.com\go-vgo\robotgo@v1.0.0-rc2.1\robotgo_fn_v1.go:17:2: undefined: Toggle
..\go\pkg\mod\github.com\go-vgo\robotgo@v1.0.0-rc2.1\robotgo_fn_v1.go:18:2: undefined: MilliSleep
..\go\pkg\mod\github.com\go-vgo\robotgo@v1.0.0-rc2.1\robotgo_fn_v1.go:20:2: undefined: MoveSmooth
..\go\pkg\mod\github.com\go-vgo\robotgo@v1.0.0-rc2.1\robotgo_fn_v1.go:21:2: undefined: Toggle
..\go\pkg\mod\github.com\go-vgo\robotgo@v1.0.0-rc2.1\robotgo_fn_v1.go:29:9: undefined: MoveSmooth
..\go\pkg\mod\github.com\go-vgo\robotgo@v1.0.0-rc2.1\robotgo_fn_v1.go:29:9: too many errors

`

**Comment by Prestapro** [comment]
Now I have this error:
`go run cmd/koolo/main.go
# gocv.io/x/gocv
In file included from aruco.cpp:1:
aruco.h:5:10: fatal error: opencv2/opencv.hpp: No such file or directory
 #include <opencv2/opencv.hpp>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.`

**Comment by hectorgimenez** [comment]
yeah you should first install opencv, I updated the README with the dependencies and the process, also better to use the build.bat script, I think will be easier.

**Comment by hectorgimenez** [comment]
Try to build it with static linking: `go run -tags static --ldflags -extldflags="-static" cmd\koolo\main.go` (you will need to add opencv to your PATH)

or try to just use the build.bat script

**Comment by Prestapro** [comment]
Is it possible by chance to have video tutoria; describing the whole process for a newbie and it’s difficult for me. I also cannot understend steps.

**Comment by Prestapro** [comment]
How I see I'm closer, try to configurate map. If you have time.
`2023-09-13T11:16:40.746+0100	INFO	internal/supervisor.go:132	Starting Game #1. Run list: ArachnidLair, StonyTomb, Pit
2023-09-13T11:16:40.746+0100	DEBUG	internal/bot.go:46	Fetching map data...
2023-09-13T11:16:41.626+0100	FATAL	internal/single_supervisor.go:43	Panic detected, Koolo will exit	{"panic": "exit status 1"}
github.com/hectorgimenez/koolo/internal.(*SinglePlayerSupervisor).Start.func1
	github.com/hectorgimenez/koolo/internal/single_supervisor.go:43
runtime.gopanic
	runtime/panic.go:914
github.com/hectorgimenez/koolo/internal/reader/map_client.GetMapData
	github.com/hectorgimenez/koolo/internal/reader/map_client/client.go:19
github.com/hectorgimenez/koolo/internal/reader.(*GameReader).GetData
	github.com/hectorgimenez/koolo/internal/reader/reader.go:28
github.com/hectorgimenez/koolo/internal.(*Bot).Run
	github.com/hectorgimenez/koolo/internal/bot.go:47
github.com/hectorgimenez/koolo/internal.(*SinglePlayerSupervisor).Start
	github.com/hectorgimenez/koolo/internal/single_supervisor.go:70
main.main.func2
	./main.go:96
golang.org/x/sync/errgroup.(*Group).Go.func1
	golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75
`

**Comment by hectorgimenez** [comment]
I updated the documentation few days ago and added some scripts to help during the setup process, maybe you can try again

**Comment by Prestapro** [comment]
Thanks for your help.
Now error:
`2023-09-26T12:41:10.824-0700	INFO	internal/supervisor.go:133	Starting Game #1. Run list: Pit, ArachnidLair, StonyTomb
2023-09-26T12:41:10.824-0700	DEBUG	internal/bot.go:46	Fetching map data...
2023-09-26T12:41:10.845-0700	FATAL	internal/single_supervisor.go:43	Panic detected, Koolo will exit	{"panic": "Error detected fetching Map Data from Diablo II: LoD 1.13c game, please make sure you have the classic expansion game installed AND config.yaml D2LoDPath is pointing to the correct game path. Error: {\"level\":30,\"time\":1695757270836,\"source\":\"map/main.c:91\",\"msg\":\"Cli:Start\",\"version\":\"v0.9.0-21-g8981-dirty\",\"hash\":\"8981d1f32f83a843a8224b376812a86df71a7ef4\"}\r\n{\"level\":20,\"time\":1695757270836,\"source\":\"map/main.c:124\",\"msg\":\"Cli:Arg\",\"game\":\"E:/Games/Diablo II\"}\r\n{\"level\":20,\"time\":1695757270836,\"source\":\"map/main.c:105\",\"msg\":\"Cli:Arg\",\"seed\": \"0x2f78b1e4\"}\r\n{\"level\":20,\"time\":1695757270836,\"source\":\"map/main.c:109\",\"msg\":\"Cli:Arg\",\"difficulty\":2}\r\n{\"level\":20,\"time\":1695757270836,\"source\":\"map/d2_client.c:147\",\"msg\":\"Init:Dll\",\"path\":\"E:/Games/Diablo II\"}\r\n{\"level\":30,\"time\":1695757270836,\"source\":\"map/d2_client.c:180\",\"msg\":\"Init:Game\",\"version\":\"\",\"path\":\"E:/Games/Diablo II/\"}\r\n{\"level\":50,\"time\":1695757270837,\"source\":\"map/offset.c:43\",\"msg\":\"Dll:Init:Failed\",\"dll\":\"Fog.DLL\",\"offset\":0}\r\n"}
github.com/hectorgimenez/koolo/internal.(*SinglePlayerSupervisor).Start.func1
	github.com/hectorgimenez/koolo/internal/single_supervisor.go:43
runtime.gopanic
	runtime/panic.go:914
github.com/hectorgimenez/koolo/internal/reader/map_client.GetMapData
	github.com/hectorgimenez/koolo/internal/reader/map_client/client.go:20
github.com/hectorgimenez/koolo/internal/reader.(*GameReader).GetData
	github.com/hectorgimenez/koolo/internal/reader/reader.go:29
github.com/hectorgimenez/koolo/internal.(*Bot).Run
	github.com/hectorgimenez/koolo/internal/bot.go:47
github.com/hectorgimenez/koolo/internal.(*SinglePlayerSupervisor).Start
	github.com/hectorgimenez/koolo/internal/single_supervisor.go:70
main.main.func2
	./main.go:96
golang.org/x/sync/errgroup.(*Group).Go.func1
	golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75`

**Comment by hectorgimenez** [comment]
Looks like you are missing the old Diablo 2 LoD 1.13c installed in your system and modifying the config.yaml to point to the installation directory

**Comment by hectorgimenez** [comment]
It must be 1.13c
