### ISSUE TITLE
FATAL ERROR

### ISSUE THREAD

**Issue by pampppp** [hectorgimenez/koolo#270]
### Details

someboddy know how to fix this error?

bot stop working after 1 hour ~

### Version

v dev

### Logs

time=04:19:18 level=ERROR msg="fatal error detected, forcing shutdown" supervisor=pap error="runtime error: index out of range [800] with length 800" stacktrace="goroutine 11201 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/hectorgimenez/koolo/internal.(*SupervisorManager).Start.func2.1()\n\tgithub.com/hectorgimenez/koolo/internal/manager.go:76 +0x108\npanic({0x18a6200?, 0xc007524180?})\n\truntime/panic.go:770 +0x132\ngithub.com/hectorgimenez/koolo/internal/pather.(*World).To(...)\n\tgithub.com/hectorgimenez/koolo/internal/pather/world.go:59\ngithub.com/hectorgimenez/koolo/internal/pather.(*PathFinder).GetPath(_, {{{0xbb8, 0x12e8}, {0x0, 0x0, {0x0, 0x0}}, {0xc007deca00, 0x8, 0x8}, ...}, ...}, ...)\n\tgithub.com/hectorgimenez/koolo/internal/pather/path_finder.go:138 +0xad2\ngithub.com/hectorgimenez/koolo/internal/action.(*Builder).MoveTo.func1({{{0xbb8, 0x12e8}, {0x0, 0x0, {0x0, 0x0}}, {0xc007deca00, 0x8, 0x8}, {0xc007588008, ...}, ...}, ...})\n\tgithub.com/hectorgimenez/koolo/internal/action/move.go:244 +0x1554\ngithub.com/hectorgimenez/koolo/internal/action.(*Chain).NextStep(_, {{{0xbb8, 0x12e8}, {0x0, 0x0, {0x0, 0x0}}, {0xc007deca00, 0x8, 0x8}, ...}, ...}, ...)\n\tgithub.com/hectorgimenez/koolo/internal/action/action_chain.go:34 +0x65\ngithub.com/hectorgimenez/koolo/internal.(*Bot).Run(0xc00071c180, {0x1b0fa20, 0xc000ba0140}, 0x0, {0xc00108a300, 0x7, 0x8})\n\tgithub.com/hectorgimenez/koolo/internal/bot.go:177 +0x1c36\ngithub.com/hectorgimenez/koolo/internal.(*SinglePlayerSupervisor).Start(0xc0001ea000)\n\tgithub.com/hectorgimenez/koolo/internal/single_supervisor.go:70 +0x485\ngithub.com/hectorgimenez/koolo/internal.(*SupervisorManager).Start.func2()\n\tgithub.com/hectorgimenez/koolo/internal/manager.go:82 +0xa2\ncreated by github.com/hectorgimenez/koolo/internal.(*SupervisorManager).Start in goroutine 11195\n\tgithub.com/hectorgimenez/koolo/internal/manager.go:69 +0x21d\n"

**Comment by hectorgimenez** [comment]
On the log, when it says "fetching map data" it will also print the mapseed, could you share that map seed and difficulty?

**Comment by pampppp** [comment]
this what gpt told me

Erreur principale :

L'erreur principale est une runtime error: index out of range [800] with length 800, ce qui signifie que le programme essaie d'accéder à l'indice 800 d'un tableau ou d'une slice qui n'a que 800 éléments (les indices vont de 0 à 799).
Déclenchement de l'erreur :

La fonction qui cause cette erreur est github.com/hectorgimenez/koolo/internal/pather.(*PathFinder).GetPath à la ligne 138 dans path_finder.go.
Cette fonction semble être appelée par github.com/hectorgimenez/koolo/internal/action.(*Builder).MoveTo.func1 à la ligne 244 dans move.go.
Propagation de l'erreur :

L'erreur se propage dans la chaîne d'appel, passant par github.com/hectorgimenez/koolo/internal/action.(*Chain).NextStep et github.com/hectorgimenez/koolo/internal.(*Bot).Run, avant d'atteindre le niveau du superviseur (SinglePlayerSupervisor et SupervisorManager).
Supervision et Gestion des erreurs :

github.com/hectorgimenez/koolo/internal.(*SupervisorManager).Start.func2.1 et github.com/hectorgimenez/koolo/internal.(*SupervisorManager).Start montrent que le gestionnaire de superviseur a tenté de gérer cette erreur, mais a finalement dû forcer l'arrêt du programme.

**Comment by pampppp** [comment]
no i was sleeping and i useed "random run" this time

the bot is struck sometime at a monster so i want try random run for killing more diversity of monster

but if i read the log
the crash happen at eldrich this time

this the log for the last run


time=04:18:09 level=DEBUG msg="Fetching map data..." seed=1445350694 difficulty=hell
time=04:18:13 level=DEBUG msg="Fetch completed" ms=4717
time=04:18:13 level=INFO msg="Starting Game #7. Run list: eldritch, andariel, summoner, council, countess, tristram, pindleskin"
time=04:18:13 level=INFO msg="Running: eldritch"
time=04:18:14 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=04:18:17 level=DEBUG msg="Load completed, continuing execution"
time=04:18:17 level=DEBUG msg="Checking for character corpse..."
time=04:18:17 level=DEBUG msg="Character corpse not found :D"
time=04:18:17 level=DEBUG msg="Checking for items to identify..."
time=04:18:17 level=DEBUG msg="No items to identify..."
time=04:18:17 level=DEBUG msg="Belt Stats Health: 0/8 healing, 0/4 mana, 3/4 rejuv."
time=04:18:17 level=DEBUG msg="Need more pots, let's buy them."
time=04:18:17 level=INFO msg="Visiting vendor..." forceRefill=false
time=04:18:31 level=DEBUG msg="Buying: 8 Healing potions and 4 Mana potions"
time=04:18:32 level=DEBUG msg="Purchased Super Healing Potion [X:9 Y:3]"
time=04:18:33 level=DEBUG msg="Purchased Super Healing Potion [X:9 Y:3]"
time=04:18:35 level=DEBUG msg="Purchased Super Healing Potion [X:9 Y:3]"
time=04:18:35 level=DEBUG msg="Purchased Super Healing Potion [X:9 Y:3]"
time=04:18:36 level=DEBUG msg="Purchased Super Healing Potion [X:9 Y:3]"
time=04:18:37 level=DEBUG msg="Purchased Super Healing Potion [X:9 Y:3]"
time=04:18:38 level=DEBUG msg="Purchased Super Healing Potion [X:9 Y:3]"
time=04:18:39 level=DEBUG msg="Purchased Super Healing Potion [X:9 Y:3]"
time=04:18:41 level=DEBUG msg="Purchased Super Mana Potion [X:9 Y:4]"
time=04:18:41 level=DEBUG msg="Purchased Super Mana Potion [X:9 Y:4]"
time=04:18:42 level=DEBUG msg="Purchased Super Mana Potion [X:9 Y:4]"
time=04:18:43 level=DEBUG msg="Purchased Super Mana Potion [X:9 Y:4]"
time=04:18:44 level=DEBUG msg="Checking for items to stash..."
time=04:18:44 level=DEBUG msg="Checking for items to stash..."
time=04:18:50 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=04:18:57 level=DEBUG msg="Load completed, continuing execution"
time=04:18:57 level=DEBUG msg=Buffing...
time=04:19:02 level=DEBUG msg="Using HealingPotion potion [Column: 2]. HP: 59 MP: 95"
time=04:19:06 level=DEBUG msg="Using HealingPotion potion [Column: 1]. HP: 59 MP: 91"
time=04:19:07 level=DEBUG msg="Aborting item pickup, monster nearby" monster="{UnitID:1761387723 Name:453 IsHovered:false Position:{X:3720 Y:5064} Stats:map[life:32768 maxlife:32768 level:79 damagereduced:25 fireresist:66 lightningresist:15 coldresist:130 poisonresist:15 velocitypercent:175 attackrate:100 otheranimrate:100 pierceidx:8793] Type:Minion}"
time=04:19:09 level=DEBUG msg="Item Detected: SuperHealingPotion [2] at X:3728 Y:5074"
time=04:19:09 level=INFO msg="At least 2 monsters detected close to the character, targeting closest one: 453"
time=04:19:12 level=DEBUG msg="Item Detected: SuperHealingPotion [2] at X:3728 Y:5074"
time=04:19:12 level=DEBUG msg="Picking up: Super Healing Potion [Normal]"
time=04:19:13 level=INFO msg="Item picked up: Super Healing Potion [Normal]"
time=04:19:13 level=INFO msg="Item picked up: Super Healing Potion [Normal]"
time=04:19:18 level=INFO msg="At least 3 monsters detected close to the character, targeting closest one: 605"
time=04:19:18 level=ERROR msg="fatal error detected, forcing shutdown" supervisor=pap error="runtime error: index out of range [800] with length 800" stacktrace="goroutine 11201 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/hectorgimenez/koolo/internal.(*SupervisorManager).Start.func2.1()\n\tgithub.com/hectorgimenez/koolo/internal/manager.go:76 +0x108\npanic({0x18a6200?, 0xc007524180?})\n\truntime/panic.go:770 +0x132\ngithub.com/hectorgimenez/koolo/internal/pather.(*World).To(...)\n\tgithub.com/hectorgimenez/koolo/internal/pather/world.go:59\ngithub.com/hectorgimenez/koolo/internal/pather.(*PathFinder).GetPath(_, {{{0xbb8, 0x12e8}, {0x0, 0x0, {0x0, 0x0}}, {0xc007deca00, 0x8, 0x8}, ...}, ...}, ...)\n\tgithub.com/hectorgimenez/koolo/internal/pather/path_finder.go:138 +0xad2\ngithub.com/hectorgimenez/koolo/internal/action.(*Builder).MoveTo.func1({{{0xbb8, 0x12e8}, {0x0, 0x0, {0x0, 0x0}}, {0xc007deca00, 0x8, 0x8}, {0xc007588008, ...}, ...}, ...})\n\tgithub.com/hectorgimenez/koolo/internal/action/move.go:244 +0x1554\ngithub.com/hectorgimenez/koolo/internal/action.(*Chain).NextStep(_, {{{0xbb8, 0x12e8}, {0x0, 0x0, {0x0, 0x0}}, {0xc007deca00, 0x8, 0x8}, ...}, ...}, ...)\n\tgithub.com/hectorgimenez/koolo/internal/action/action_chain.go:34 +0x65\ngithub.com/hectorgimenez/koolo/internal.(*Bot).Run(0xc00071c180, {0x1b0fa20, 0xc000ba0140}, 0x0, {0xc00108a300, 0x7, 0x8})\n\tgithub.com/hectorgimenez/koolo/internal/bot.go:177 +0x1c36\ngithub.com/hectorgimenez/koolo/internal.(*SinglePlayerSupervisor).Start(0xc0001ea000)\n\tgithub.com/hectorgimenez/koolo/internal/single_supervisor.go:70 +0x485\ngithub.com/hectorgimenez/koolo/internal.(*SupervisorManager).Start.func2()\n\tgithub.com/hectorgimenez/koolo/internal/manager.go:82 +0xa2\ncreated by github.com/hectorgimenez/koolo/internal.(*SupervisorManager).Start in goroutine 11195\n\tgithub.com/hectorgimenez/koolo/internal/manager.go:69 +0x21d\n"
time=04:19:18 level=INFO msg=Stopping... configuration=pap
time=04:19:18 level=INFO msg="Finished stopping" configuration=pap

**Comment by pampppp** [comment]
and previous game this is the log of the end
was on summoner

time=04:11:10 level=INFO msg="Running: summoner"
time=04:11:10 level=DEBUG msg="Checking for character corpse..."
time=04:11:10 level=DEBUG msg="Character corpse not found :D"
time=04:11:10 level=DEBUG msg="Checking for items to identify..."
time=04:11:10 level=INFO msg="Identifying 1 items..."
time=04:11:12 level=INFO msg="Visiting vendor..." forceRefill=false
time=04:11:20 level=DEBUG msg="Buying: 8 Healing potions and 0 Mana potions"
time=04:11:21 level=DEBUG msg="Purchased Super Healing Potion [X:9 Y:3]"
time=04:11:22 level=DEBUG msg="Purchased Super Healing Potion [X:9 Y:3]"
time=04:11:23 level=DEBUG msg="Purchased Super Healing Potion [X:9 Y:3]"
time=04:11:24 level=DEBUG msg="Purchased Super Healing Potion [X:9 Y:3]"
time=04:11:25 level=DEBUG msg="Purchased Super Healing Potion [X:9 Y:3]"
time=04:11:26 level=DEBUG msg="Purchased Super Healing Potion [X:9 Y:3]"
time=04:11:28 level=DEBUG msg="Purchased Super Healing Potion [X:9 Y:3]"
time=04:11:29 level=DEBUG msg="Purchased Super Healing Potion [X:9 Y:3]"
time=04:11:30 level=DEBUG msg="Item Ring [Magic] sold"
time=04:11:31 level=DEBUG msg="Checking for items to stash..."
time=04:11:31 level=DEBUG msg="Checking for items to stash..."
time=04:11:36 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=04:11:38 level=DEBUG msg="Load completed, continuing execution"
time=04:11:38 level=DEBUG msg=Buffing...
time=04:11:48 level=INFO msg="At least 1 monsters detected close to the character, targeting closest one: 40"
time=04:11:52 level=INFO msg="At least 1 monsters detected close to the character, targeting closest one: 131"
time=04:11:56 level=INFO msg="At least 1 monsters detected close to the character, targeting closest one: 40"
time=04:11:56 level=INFO msg="At least 1 monsters detected close to the character, targeting closest one: 40"
time=04:11:58 level=INFO msg="At least 4 monsters detected close to the character, targeting closest one: 56"
time=04:11:59 level=INFO msg="At least 3 monsters detected close to the character, targeting closest one: 40"
time=04:11:59 level=INFO msg="At least 2 monsters detected close to the character, targeting closest one: 40"
time=04:12:00 level=INFO msg="Character stuck and monsters detected, trying to kill monsters around"
time=04:12:02 level=INFO msg="Character stuck and monsters detected, trying to kill monsters around"
time=04:12:02 level=INFO msg="Character stuck and monsters detected, trying to kill monsters around"
time=04:12:03 level=INFO msg="Character stuck and monsters detected, trying to kill monsters around"
time=04:12:05 level=INFO msg="Character stuck and monsters detected, trying to kill monsters around"
time=04:12:08 level=INFO msg="At least 4 monsters detected close to the character, targeting closest one: 56"
time=04:12:10 level=INFO msg="At least 6 monsters detected close to the character, targeting closest one: 56"
time=04:12:13 level=INFO msg="At least 3 monsters detected close to the character, targeting closest one: 56"
time=04:12:14 level=INFO msg="At least 2 monsters detected close to the character, targeting closest one: 56"
time=04:12:19 level=INFO msg="Character stuck and monsters detected, trying to kill monsters around"
time=04:12:23 level=INFO msg="At least 1 monsters detected close to the character, targeting closest one: 131"
time=04:12:28 level=INFO msg="At least 3 monsters detected close to the character, targeting closest one: 131"
time=04:12:36 level=INFO msg="At least 5 monsters detected close to the character, targeting closest one: 40"
time=04:12:41 level=DEBUG msg="Using HealingPotion potion [Column: 1]. HP: 57 MP: 98"
time=04:12:43 level=DEBUG msg="Using ManaPotion potion [Column: 3]. HP: 57 MP: 0"
time=04:13:35 level=DEBUG msg="Using HealingPotion potion [Column: 1]. HP: 57 MP: 100"
time=04:13:49 level=INFO msg="At least 6 monsters detected close to the character, targeting closest one: 40"
time=04:14:18 level=DEBUG msg="Using ManaPotion potion [Column: 3]. HP: 86 MP: 0"
time=04:14:39 level=DEBUG msg="Using ManaPotion potion [Column: 3]. HP: 79 MP: 0"
time=04:14:55 level=DEBUG msg="Using HealingPotion potion [Column: 2]. HP: 55 MP: 0"
time=04:14:55 level=DEBUG msg="Using ManaPotion potion [Column: 3]. HP: 55 MP: 0"
time=04:15:00 level=DEBUG msg="Using HealingPotion potion [Column: 1]. HP: 60 MP: 0"
time=04:15:01 level=INFO msg="At least 6 monsters detected close to the character, targeting closest one: 40"
time=04:15:48 level=DEBUG msg="Using HealingPotion potion [Column: 2]. HP: 56 MP: 1"
time=04:16:13 level=INFO msg="At least 2 monsters detected close to the character, targeting closest one: 40"
time=04:16:44 level=DEBUG msg=Buffing...
time=04:17:03 level=DEBUG msg="Item Detected: SuperManaPotion [2] at X:25149 Y:5508"
time=04:17:03 level=DEBUG msg="Picking up: Super Mana Potion [Normal]"
time=04:17:03 level=INFO msg="Item picked up: Super Mana Potion [Normal]"
time=04:17:03 level=DEBUG msg="Item Detected: RejuvenationPotion [2] at X:25145 Y:5507"
time=04:17:03 level=DEBUG msg="Picking up: Rejuvenation Potion [Normal]"
time=04:17:04 level=INFO msg="Item picked up: Rejuvenation Potion [Normal]"
time=04:17:04 level=DEBUG msg="Item Detected: SuperHealingPotion [2] at X:25143 Y:5508"
time=04:17:04 level=DEBUG msg="Picking up: Super Healing Potion [Normal]"
time=04:17:05 level=INFO msg="Item picked up: Super Healing Potion [Normal]"
time=04:17:06 level=INFO msg="At least 1 monsters detected close to the character, targeting closest one: 131"
time=04:17:11 level=INFO msg="At least 7 monsters detected close to the character, targeting closest one: 40"
time=04:17:15 level=DEBUG msg="Using HealingPotion potion [Column: 2]. HP: 53 MP: 0"
time=04:17:15 level=DEBUG msg="Using ManaPotion potion [Column: 3]. HP: 53 MP: 0"
time=04:17:15 level=INFO msg="At least 7 monsters detected close to the character, targeting closest one: 40"
time=04:17:17 level=INFO msg="At least 4 monsters detected close to the character, targeting closest one: 40"
time=04:17:17 level=INFO msg="At least 4 monsters detected close to the character, targeting closest one: 40"
time=04:17:18 level=INFO msg="At least 8 monsters detected close to the character, targeting closest one: 131"
time=04:17:19 level=DEBUG msg="Using HealingPotion potion [Column: 2]. HP: 60 MP: 80"
time=04:17:22 level=DEBUG msg="Using HealingPotion potion on Mercenary [Column: 1]. HP: 59"
time=04:17:28 level=DEBUG msg="Using HealingPotion potion on Mercenary [Column: 1]. HP: 50"
time=04:17:56 level=DEBUG msg="Using RejuvenationPotion potion on Mercenary [Column: 4]. HP: 19"
time=04:17:58 level=WARN msg="Game finished with errors, reason: max game length reached, try to exit game: 900.01. Game total time: 900.03s" supervisor=pap mapSeed=1838917835
time=04:18:09 level=DEBUG msg="Fetching map data..." seed=1445350694 difficulty=hell
time=04:18:13 level=DEBUG msg="Fetch completed" ms=4717
time=04:18:13 level=INFO msg="Starting Game #7. Run list: eldritch, andariel, summoner, council, countess, tristram, pindleskin"
time=04:18:13 level=INFO msg="Running: eldritch"
time=04:18:14 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=04:18:17 level=DEBUG msg="Load completed, continuing execution"
time=04:18:17 level=DEBUG msg="Checking for character corpse..."
time=04:18:17 level=DEBUG msg="Character corpse not found :D"
time=04:18:17 level=DEBUG msg="Checking for items to identify..."
time=04:18:17 level=DEBUG msg="No items to identify..."
time=04:18:17 level=DEBUG msg="Belt Stats Health: 0/8 healing, 0/4 mana, 3/4 rejuv."
time=04:18:17 level=DEBUG msg="Need more pots, let's buy them."
time=04:18:17 level=INFO msg="Visiting vendor..." forceRefill=false
time=04:18:31 level=DEBUG msg="Buying: 8 Healing potions and 4 Mana potions"
time=04:18:32 level=DEBUG msg="Purchased Super Healing Potion [X:9 Y:3]"
time=04:18:33 level=DEBUG msg="Purchased Super Healing Potion [X:9 Y:3]"
time=04:18:35 level=DEBUG msg="Purchased Super Healing Potion [X:9 Y:3]"
time=04:18:35 level=DEBUG msg="Purchased Super Healing Potion [X:9 Y:3]"
time=04:18:36 level=DEBUG msg="Purchased Super Healing Potion [X:9 Y:3]"
time=04:18:37 level=DEBUG msg="Purchased Super Healing Potion [X:9 Y:3]"
time=04:18:38 level=DEBUG msg="Purchased Super Healing Potion [X:9 Y:3]"
time=04:18:39 level=DEBUG msg="Purchased Super Healing Potion [X:9 Y:3]"
time=04:18:41 level=DEBUG msg="Purchased Super Mana Potion [X:9 Y:4]"
time=04:18:41 level=DEBUG msg="Purchased Super Mana Potion [X:9 Y:4]"
time=04:18:42 level=DEBUG msg="Purchased Super Mana Potion [X:9 Y:4]"
time=04:18:43 level=DEBUG msg="Purchased Super Mana Potion [X:9 Y:4]"
time=04:18:44 level=DEBUG msg="Checking for items to stash..."
time=04:18:44 level=DEBUG msg="Checking for items to stash..."
time=04:18:50 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=04:18:57 level=DEBUG msg="Load completed, continuing execution"
time=04:18:57 level=DEBUG msg=Buffing...
time=04:19:02 level=DEBUG msg="Using HealingPotion potion [Column: 2]. HP: 59 MP: 95"
time=04:19:06 level=DEBUG msg="Using HealingPotion potion [Column: 1]. HP: 59 MP: 91"
time=04:19:07 level=DEBUG msg="Aborting item pickup, monster nearby" monster="{UnitID:1761387723 Name:453 IsHovered:false Position:{X:3720 Y:5064} Stats:map[life:32768 maxlife:32768 level:79 damagereduced:25 fireresist:66 lightningresist:15 coldresist:130 poisonresist:15 velocitypercent:175 attackrate:100 otheranimrate:100 pierceidx:8793] Type:Minion}"
time=04:19:09 level=DEBUG msg="Item Detected: SuperHealingPotion [2] at X:3728 Y:5074"
time=04:19:09 level=INFO msg="At least 2 monsters detected close to the character, targeting closest one: 453"
time=04:19:12 level=DEBUG msg="Item Detected: SuperHealingPotion [2] at X:3728 Y:5074"
time=04:19:12 level=DEBUG msg="Picking up: Super Healing Potion [Normal]"
time=04:19:13 level=INFO msg="Item picked up: Super Healing Potion [Normal]"
time=04:19:13 level=INFO msg="Item picked up: Super Healing Potion [Normal]"
time=04:19:18 level=INFO msg="At least 3 monsters detected close to the character, targeting closest one: 605"
time=04:19:18 level=ERROR msg="fatal error detected, forcing shutdown" supervisor=pap error="runtime error: index out of range [800] with length 800" stacktrace="goroutine 11201 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/hectorgimenez/koolo/internal.(*SupervisorManager).Start.func2.1()\n\tgithub.com/hectorgimenez/koolo/internal/manager.go:76 +0x108\npanic({0x18a6200?, 0xc007524180?})\n\truntime/panic.go:770 +0x132\ngithub.com/hectorgimenez/koolo/internal/pather.(*World).To(...)\n\tgithub.com/hectorgimenez/koolo/internal/pather/world.go:59\ngithub.com/hectorgimenez/koolo/internal/pather.(*PathFinder).GetPath(_, {{{0xbb8, 0x12e8}, {0x0, 0x0, {0x0, 0x0}}, {0xc007deca00, 0x8, 0x8}, ...}, ...}, ...)\n\tgithub.com/hectorgimenez/koolo/internal/pather/path_finder.go:138 +0xad2\ngithub.com/hectorgimenez/koolo/internal/action.(*Builder).MoveTo.func1({{{0xbb8, 0x12e8}, {0x0, 0x0, {0x0, 0x0}}, {0xc007deca00, 0x8, 0x8}, {0xc007588008, ...}, ...}, ...})\n\tgithub.com/hectorgimenez/koolo/internal/action/move.go:244 +0x1554\ngithub.com/hectorgimenez/koolo/internal/action.(*Chain).NextStep(_, {{{0xbb8, 0x12e8}, {0x0, 0x0, {0x0, 0x0}}, {0xc007deca00, 0x8, 0x8}, ...}, ...}, ...)\n\tgithub.com/hectorgimenez/koolo/internal/action/action_chain.go:34 +0x65\ngithub.com/hectorgimenez/koolo/internal.(*Bot).Run(0xc00071c180, {0x1b0fa20, 0xc000ba0140}, 0x0, {0xc00108a300, 0x7, 0x8})\n\tgithub.com/hectorgimenez/koolo/internal/bot.go:177 +0x1c36\ngithub.com/hectorgimenez/koolo/internal.(*SinglePlayerSupervisor).Start(0xc0001ea000)\n\tgithub.com/hectorgimenez/koolo/internal/single_supervisor.go:70 +0x485\ngithub.com/hectorgimenez/koolo/internal.(*SupervisorManager).Start.func2()\n\tgithub.com/hectorgimenez/koolo/internal/manager.go:82 +0xa2\ncreated by github.com/hectorgimenez/koolo/internal.(*SupervisorManager).Start in goroutine 11195\n\tgithub.com/hectorgimenez/koolo/internal/manager.go:69 +0x21d\n"
time=04:19:18 level=INFO msg=Stopping... configuration=pap
time=04:19:18 level=INFO msg="Finished stopping" configuration=pap

**Comment by pampppp** [comment]
this is the entier log

[koolo-log-2024-05-27-22-45-00.txt](https://github.com/hectorgimenez/koolo/files/15470166/koolo-log-2024-05-27-22-45-00.txt)

**Comment by AquaRush** [comment]
Hello, @pampppp 

Could you please `git pull` the latest commits and confirm whether you still get the stated error?
