### ISSUE TITLE
chaos sanctuary problems

### ISSUE THREAD

**Issue by childofwar1980** [hectorgimenez/koolo#272]
### Details

currently chaos sanctuary is broken completely for blizz sorc and has many problems for other classes as well. when set to kill diablo with no clear options selected there are many crashes as soon as chaos sanctuary is entered and when it doesnt crash to desktop the sorc will teleport to the first seal and freeze and exit game without attempting to clear the seal and foh paladin when doing a walking run will get stuck frequently and exit game also foh paladin currently runs directly into mob packs before casting foh and that is not ideal and could use an adjustment

### Version

v0.4.0

### Logs

[koolo-log-2024-05-28-00-11-31.txt](https://github.com/hectorgimenez/koolo/files/15476535/koolo-log-2024-05-28-00-11-31.txt)

**Comment by amefumi** [comment]
I've seen the similar problem when my foh pal cannot open the door of ancient tunnel
When running chaos and selecting clear area, it just teleports here and there but not casting any skills and not triggering the seal.

**Comment by childofwar1980** [comment]
also the sorc is back to casting teleport at the seal then quitting the game

**Comment by childofwar1980** [comment]
i reverted to the 0.4.0 latest release build and the seals work in that build however blizz sorc cannot survive tele stomping into lord de seis mob pack or the infector of souls pack. This needs to be adjusted so that she picks a spot away from them and attacks from a safe distance

**Comment by childofwar1980** [comment]
yay the latest build seems to have fixed most of the problems but there is still one problem thats been around since the beginning, in act 4 bot has problems clicking on tyrael to res merc could you look into that? THEN EVERYTHING IS FIXED :)

**Comment by childofwar1980** [comment]
new problem latest build everytime the bot goes to town during chaos run for any reason to get potions or res merc when finished and enters town portal back to chaos there is a hard crash
[koolo-log-2024-05-31-11-55-40.txt](https://github.com/user-attachments/files/15517729/koolo-log-2024-05-31-11-55-40.txt)

**Comment by childofwar1980** [comment]
with latest build i did some testing and the back to town script for potions is fixed and most hard crashes are fixed however there is still a hard crash occasionally when teleporting into chaos sanctuary from river of flame and it seems to trigger if you get hit by an udar on the way in and you have the stun effect on you. also often the bot will just freeze up and stop doing anything randomly until chicken and the clicking on tyrael is still broken.
[koolo-log-2024-06-06-12-58-39.txt](https://github.com/user-attachments/files/15686232/koolo-log-2024-06-06-12-58-39.txt)
