### ISSUE TITLE
Sorc doesn't cast Energy Shield at all.

### ISSUE THREAD

**Issue by AquaRush** [hectorgimenez/koolo#273]
### Details

Bot works completely fine, uses CTA, swaps and then prebuffs using only Frozen Armor without Energy Shield.
I don't have experience with Go lang and tried to self compile by changing the code but it doesn't seem work and I'd rather make this issue since I run Hardcore and not Softcore.
Thanks in advance for the help.

### Version

v0.4.0

### Logs

time=13:24:14 level=INFO msg="Waiting for character selection screen..."
time=13:24:33 level=INFO msg="Character selection screen found"
time=13:24:33 level=INFO msg="Selecting character..."
time=13:24:34 level=INFO msg="Character found"
time=13:24:43 level=ERROR msg="Error creating new game: timeout"
time=13:24:43 level=INFO msg="Waiting for character selection screen..."
time=13:24:44 level=INFO msg="Character selection screen found"
time=13:24:44 level=INFO msg="Selecting character..."
time=13:24:44 level=INFO msg="Character found"
time=13:24:52 level=ERROR msg="Error creating new game: timeout"
time=13:24:52 level=INFO msg="Waiting for character selection screen..."
time=13:24:53 level=INFO msg="Character selection screen found"
time=13:24:53 level=INFO msg="Selecting character..."
time=13:24:53 level=INFO msg="Character found"
time=13:24:55 level=INFO msg=Stopping... configuration=BobSorc
time=13:24:55 level=INFO msg="Finished stopping" configuration=BobSorc
time=13:25:01 level=ERROR msg="Error creating new game: timeout"
time=13:25:56 level=INFO msg="Waiting for character selection screen..."
time=13:26:13 level=INFO msg="Character selection screen found"
time=13:26:13 level=INFO msg="Selecting character..."
time=13:26:15 level=INFO msg="Character found"
time=13:26:21 level=DEBUG msg="Fetching map data..." seed=68354223 difficulty=normal
time=13:26:23 level=DEBUG msg="Fetch completed" ms=2903
time=13:26:23 level=INFO msg="Starting Game #0. Run list: lower_kurast_chest, ancient_tunnels, andariel, stony_tomb, mephisto"
time=13:26:23 level=INFO msg="Running: lower_kurast_chest"
time=13:26:24 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=13:26:24 level=DEBUG msg="Load completed, continuing execution"
time=13:26:24 level=DEBUG msg="Checking for character corpse..."
time=13:26:24 level=DEBUG msg="Character corpse not found :D"
time=13:26:24 level=DEBUG msg="Checking for items to stash..."
time=13:26:24 level=DEBUG msg="Checking for items to identify..."
time=13:26:24 level=DEBUG msg="No items to identify..."
time=13:26:24 level=DEBUG msg="Belt Stats Health: 4/4 healing, 4/4 mana, 8/8 rejuv."
time=13:26:24 level=DEBUG msg="Checking for items to stash..."
time=13:26:24 level=DEBUG msg="Checking for items to stash..."
time=13:26:26 level=INFO msg="Traversing areas to reach destination" areas="[75 76 77 78 79]"
time=13:26:27 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=13:26:31 level=DEBUG msg="Load completed, continuing execution"
time=13:26:35 level=DEBUG msg="CTA found: swapping weapon and casting Battle Command / Battle Orders"
time=13:26:35 level=DEBUG msg=Buffing...
time=13:26:38 level=DEBUG msg="Reached area" area="Spider Forest"
time=13:26:38 level=INFO msg="Trying to autodiscover Waypoint for current area" area="Spider Forest"
time=13:26:49 level=INFO msg="Waypoint discovered" area="Spider Forest"
time=13:27:10 level=DEBUG msg="Reached area" area="Great Marsh"
time=13:27:10 level=INFO msg="Trying to autodiscover Waypoint for current area" area="Great Marsh"
time=13:27:24 level=INFO msg="Waypoint discovered" area="Great Marsh"
time=13:27:25 level=DEBUG msg="CTA found: swapping weapon and casting Battle Command / Battle Orders"
time=13:27:25 level=DEBUG msg=Buffing...
time=13:27:46 level=DEBUG msg="Reached area" area="Flayer Jungle"
time=13:27:46 level=INFO msg="Trying to autodiscover Waypoint for current area" area="Flayer Jungle"
time=13:27:46 level=WARN msg="Game finished with errors, reason: unrecoverable error occurred, game can not continue: attempt limit reached on step: InteractObjectStep: object is too far away: 237. Current distance: 160. Game total time: 82.35s" supervisor=BobSorc mapSeed=68354223
time=13:27:49 level=INFO msg=Stopping... configuration=BobSorc
time=13:27:49 level=INFO msg="Finished stopping" configuration=BobSorc
time=13:27:55 level=ERROR msg="Error creating new game: timeout"
time=13:28:54 level=INFO msg="Koolo shutting down..."

**Comment by xg6636** [comment]
I suppose you use nova sorc mode.
in the leveling sorc mode, the bot doesn't use energy shield buff,
you may edit the source to add energy shield buff and compile it yourself,
then you have a shield-energy-valid bot.

**Comment by AquaRush** [comment]
I've made a PR to issue this bug as other users also stated it, still don't know what causes it but I've added an additional check in the PR in order to be sure it buffs at all times.
