### ISSUE TITLE
Leveling

### ISSUE THREAD

**Issue by dmelia** [hectorgimenez/koolo#274]
### Details

The bot gets stuck trying to start a leveling run on den of evil. This happens every game.

### Version

dev

### Logs

time=09:10:51 level=INFO msg="Starting Den of Evil run"
time=09:10:51 level=ERROR msg="fatal error detected, forcing shutdown" supervisor=HoHoHo error="runtime error: index out of range [200] with length 200" stacktrace="goroutine 99 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/hectorgimenez/koolo/internal.(*SupervisorManager).Start.func2.1()\n\tgithub.com/hectorgimenez/koolo/internal/manager.go:76 +0x108\npanic({0x9a8f80?, 0xc00001c1c8?})\n\truntime/panic.go:770 +0x132\ngithub.com/hectorgimenez/koolo/internal/pather.(*World).To(...)\n\tgithub.com/hectorgimenez/koolo/internal/pather/world.go:59\ngithub.com/hectorgimenez/koolo/internal/pather.(*PathFinder).GetPath(_, {{{0x1590, 0x1518}, {0x0, 0x0, {0x0, 0x0}}, {0xc001700200, 0x5, 0x8}, ...}, ...}, ...)\n\tgithub.com/hectorgimenez/koolo/internal/pather/path_finder.go:138 +0xaca\ngithub.com/hectorgimenez/koolo/internal/action.(*Builder).MoveToArea.func2({{{0x1590, 0x1518}, {0x0, 0x0, {0x0, 0x0}}, {0xc001700200, 0x5, 0x8}, {0xc001772008, ...}, ...}, ...})\n\tgithub.com/hectorgimenez/koolo/internal/action/move.go:80 +0x5d7\ngithub.com/hectorgimenez/koolo/internal/action.(*Builder).MoveTo.func1({{{0x1590, 0x1518}, {0x0, 0x0, {0x0, 0x0}}, {0xc001700200, 0x5, 0x8}, {0xc001772008, ...}, ...}, ...})\n\tgithub.com/hectorgimenez/koolo/internal/action/move.go:126 +0xcb\ngithub.com/hectorgimenez/koolo/internal/action.(*Chain).NextStep(_, {{{0x1590, 0x1518}, {0x0, 0x0, {0x0, 0x0}}, {0xc001700200, 0x5, 0x8}, ...}, ...}, ...)\n\tgithub.com/hectorgimenez/koolo/internal/action/action_chain.go:34 +0x65\ngithub.com/hectorgimenez/koolo/internal/action.(*Chain).NextStep(_, {{{0x1590, 0x1518}, {0x0, 0x0, {0x0, 0x0}}, {0xc001700200, 0x5, 0x8}, ...}, ...}, ...)\n\tgithub.com/hectorgimenez/koolo/internal/action/action_chain.go:48 +0x1f6\ngithub.com/hectorgimenez/koolo/internal/action.(*Chain).NextStep(_, {{{0x1590, 0x1518}, {0x0, 0x0, {0x0, 0x0}}, {0xc001700200, 0x5, 0x8}, ...}, ...}, ...)\n\tgithub.com/hectorgimenez/koolo/internal/action/action_chain.go:48 +0x1f6\ngithub.com/hectorgimenez/koolo/internal.(*Bot).Run(0xc0009ee080, {0xc15680, 0xc000d52410}, 0x1, {0xc0008daaa0, 0x1, 0x1})\n\tgithub.com/hectorgimenez/koolo/internal/bot.go:177 +0x1c36\ngithub.com/hectorgimenez/koolo/internal.(*SinglePlayerSupervisor).Start(0xc0007ae038)\n\tgithub.com/hectorgimenez/koolo/internal/single_supervisor.go:70 +0x485\ngithub.com/hectorgimenez/koolo/internal.(*SupervisorManager).Start.func2()\n\tgithub.com/hectorgimenez/koolo/internal/manager.go:82 +0xa2\ncreated by github.com/hectorgimenez/koolo/internal.(*SupervisorManager).Start in goroutine 42\n\tgithub.com/hectorgimenez/koolo/internal/manager.go:69 +0x21d\n"

**Comment by dmelia** [comment]
> Reported already in issue #269 known issue at the moment since the game update.

Not the same issue. The bot bugs before doing anything in town.

**Comment by divineblade7** [comment]
Leveling itself is broken at the moment. So is hold off on running any more leveling for the time being.
