### ISSUE TITLE
cannot transmute the flawless gem to a perfect gem in cube

### ISSUE THREAD

**Issue by VincentQing116** [hectorgimenez/koolo#286]
### Details

Updated to latest version.But the bot cannnot drop the flawless gem into cub to transmue. it moves flawless gem between inventory and stash repeatly.So I have to disable the feature of cube. Please help me out. Thanks.

### Version

v0.4.0

### Logs

there is no error log.

**Comment by nydicil** [comment]
Same here, bot puts gems into the cube but doesn't click transmute button

**Comment by nullptr-ref** [comment]
this is fixed in the latest versions (dev)
