### ISSUE TITLE
Cow mode feedback / issues

### ISSUE THREAD

**Issue by jik0n** [hectorgimenez/koolo#29]
I managed to figure out how to use the latest via dev instructions and ran a cow level attempt. Few things I noticed:

1. It uses the TP tome in my blocked inv slot instead of one in the non blocked ones causing things it picks up to fill that slot and not be touched
2. If its inv is full it will try to pick the item up a few more times then tele away / back and try again eventually leaving and just ignoring the item (why is it not going to town to sell?)
3. It has issues if a tome already exists in the cube or something else does

**Comment by hectorgimenez** [comment]
I think point 1 and 2 should be fixed now with the latest commits in main branch

**Comment by jik0n** [comment]
@hectorgimenez as someone who is very new to building from source do I just go back into the root koolo folder and re-run "build.bat" without removing the old "build" directory? Or do I follow the entire process again from scratch? I don't want to mess anything up lol

**Comment by hectorgimenez** [comment]
you should run `git pull` from your terminal in the project directory and that will fetch the updates, and then yes, you can run the build.bat again (the script deletes previous build directory, so backup your config file before running it again)

**Comment by jik0n** [comment]
Just tried to run cows and noticed a possible bug... it picked up a large item in tristram which filled my inv so when it went to buy a TP tome to make the portal it couldn't so it crashed. Maybe have it ID / sell before attempting to buy a TP tome?

**Comment by jik0n** [comment]
Looks like the original issues are resolved after doing a few cow runs (sorry I couldn't test sooner, been kind of sick and not on my computer much). Thanks so much for updating the bot so quickly!

Only bug left I see is if the bot fills its inv in trist and can pick up the leg it will crash if it can't buy a TP tome

**Comment by hectorgimenez** [comment]
update and try again, it should be fixed now I think

**Comment by jik0n** [comment]
issue appears resolved now. Thanks!
