### ISSUE TITLE
Companion mode starts always in normal difficulty 

### ISSUE THREAD

**Issue by PrivateName55** [hectorgimenez/koolo#301]
### Details

If I activate Companion mode everything works fine. The only problem I got is that it´s only starts in normal difficulty. If I deactivate companion mode the difficulty is set correctly to hell. If I try to switch manually (press Pause and start a new game in Hell) the d2r.exe is ended directly. Configuration is also set correctly.  

the log file also says that game was in hell:

time=01:20:53 level=DEBUG msg="Fetching map data..." seed=767128917 difficulty=hell

But its just normal

### Version

v0.4.0

### Logs

time=01:20:56 level=INFO msg="Starting Game #2. Run list: andariel"
time=01:20:56 level=INFO msg="Running: andariel"
time=01:20:57 level=DEBUG msg="Checking for character corpse..."
time=01:20:57 level=DEBUG msg="Character corpse not found :D"
time=01:20:57 level=DEBUG msg="Checking for items to identify..."
time=01:20:57 level=DEBUG msg="No items to identify..."
time=01:20:57 level=DEBUG msg="Belt Stats Health: 8/8 healing, 4/4 mana, 1/4 rejuv."
time=01:20:57 level=DEBUG msg="Checking for items to stash..."
time=01:20:57 level=DEBUG msg="Checking for items to stash..."
time=01:21:01 level=DEBUG msg="CTA found: swapping weapon and casting Battle Command / Battle Orders"
time=01:21:01 level=DEBUG msg=Buffing...
time=01:21:17 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance"
time=01:21:17 level=DEBUG msg="Clearing area..." monsterID=7
time=01:21:17 level=DEBUG msg="Item Detected: HeavyGloves [4] at X:22548 Y:9549"
time=01:21:18 level=DEBUG msg="Picking up: Heavy Gloves [Magic]"
time=01:21:18 level=INFO msg="Item picked up: Heavy Gloves [Magic]"
time=01:21:18 level=DEBUG msg="No items detected, waiting a bit and will try again" waitMs=81
time=01:21:18 level=INFO msg="Run andariel finished, length: 21.87s"
time=01:21:35 level=DEBUG msg="Fetching map data..." seed=1487399883 difficulty=hell
time=01:21:38 level=DEBUG msg="Fetch completed" ms=3324

**Comment by nullptr-ref** [comment]
You can change the difficulty setting in the config/Settings.json file -> `"Lobby Difficulty": 2,` for hell. After the change restart the leader/bot

**Comment by SoundsLegit** [comment]
You can temporarily fix this by changing settings.json file
change "Lobby Difficulty" value to 2
