### ISSUE TITLE
Improper CTA Usage - Not Using BO

### ISSUE THREAD

**Issue by HYPERTONE** [hectorgimenez/koolo#302]
### Details

CTA is equipped and koolo successfully switches to it, however does not use BO but only uses BC.

Anyone else experiencing this issue? 

### Version

dev

### Logs

time=12:51:10 level=INFO msg="Starting Game #32. Run list: eldritch"
time=12:51:10 level=INFO msg="Running: eldritch"
time=12:51:10 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=12:51:13 level=DEBUG msg="Load completed, continuing execution"
time=12:51:13 level=DEBUG msg="Checking for character corpse..."
time=12:51:13 level=DEBUG msg="Character corpse not found :D"
time=12:51:13 level=DEBUG msg="Checking for items to identify..."
time=12:51:13 level=DEBUG msg="No items to identify..."
time=12:51:13 level=DEBUG msg="Belt Stats Health: 7/8 healing, 0/0 mana, 8/8 rejuv."
time=12:51:13 level=DEBUG msg="Checking for items to stash..."
time=12:51:13 level=INFO msg="Stashing items..."
time=12:51:18 level=DEBUG msg="Tab 1 is full, switching to next one"
time=12:51:20 level=INFO msg="Item Amulet [Rare] stashed" nipFile="config/Blizzard Sorc/pickit/rare.nip:10" rawRule="[type] == amulet \t\t&& [quality] == rare"
time=12:51:20 level=DEBUG msg="Checking for items to stash..."
time=12:51:28 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance"
time=12:51:28 level=DEBUG msg="Aborting item pickup, monster nearby" monster="{UnitID:3199274682 Name:453 IsHovered:true Position:{X:3738 Y:5067} Stats:map[life:17920 maxlife:32768 level:79 damagereduced:25 fireresist:66 lightningresist:15 coldresist:130 poisonresist:15 velocitypercent:175 attackrate:100 otheranimrate:100 pierceidx:8784] Type:Minion}"
time=12:51:29 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance"
time=12:51:30 level=DEBUG msg="Item Detected: SuperHealingPotion [2] at X:3736 Y:5068"
time=12:51:30 level=DEBUG msg="Picking up: Super Healing Potion [Normal]"
time=12:51:30 level=INFO msg="Item picked up: Super Healing Potion [Normal]"
time=12:51:31 level=DEBUG msg="CTA found: swapping weapon and casting Battle Command / Battle Orders"
time=12:51:31 level=DEBUG msg="Post CTA Buffing..."
time=12:51:42 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance"
time=12:51:42 level=DEBUG msg="Monster detected close to the player, casting Blizzard over it"
time=12:51:43 level=DEBUG msg="Clearing area..." monsterID=453
time=12:51:43 level=DEBUG msg="Clearing area..." monsterID=453
time=12:51:44 level=DEBUG msg="Clearing area..." monsterID=453
time=12:51:44 level=DEBUG msg="Clearing area..." monsterID=453
time=12:51:45 level=DEBUG msg="Clearing area..." monsterID=453
time=12:51:45 level=DEBUG msg="Monster detected close to the player, casting Blizzard over it"
time=12:51:45 level=DEBUG msg="Clearing area..." monsterID=453
time=12:51:45 level=DEBUG msg="Clearing area..." monsterID=453
time=12:51:45 level=DEBUG msg="Clearing area..." monsterID=453
time=12:51:45 level=DEBUG msg="Clearing area..." monsterID=453
time=12:51:46 level=DEBUG msg="Clearing area..." monsterID=453
time=12:51:46 level=DEBUG msg="Clearing area..." monsterID=453
time=12:51:47 level=DEBUG msg="No items detected, waiting a bit and will try again" waitMs=999
time=12:51:48 level=INFO msg="Run eldritch finished, length: 37.26s"
time=12:51:53 level=DEBUG msg="Fetching map data..." seed=1479326647 difficulty=hell
time=12:51:55 level=DEBUG msg="Fetch completed" ms=1407

**Comment by HYPERTONE** [comment]
I found if I pause the bot, manually switch to my CTA and click on BO, then switch back to primary weapon - it successfully uses BO upon entering the next zone.

However, it's only using BO and not BC.

**Comment by HYPERTONE** [comment]
More details:

This seems to happen when the bot receives an error while it's trying to pick up an item or cannot determine if a monster is dead. It just continues to cast blizzard into an area until the game times out. This seems to completely ignore the CTA buff even though it think it has used the CTA buffs.



time=14:00:16 level=INFO msg="Starting Game #124. Run list: eldritch"
time=14:00:16 level=INFO msg="Running: eldritch"
time=14:00:16 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=14:00:19 level=DEBUG msg="Load completed, continuing execution"
time=14:00:19 level=DEBUG msg="Checking for character corpse..."
time=14:00:19 level=DEBUG msg="Character corpse not found :D"
time=14:00:19 level=DEBUG msg="Checking for items to identify..."
time=14:00:19 level=DEBUG msg="No items to identify..."
time=14:00:19 level=DEBUG msg="Belt Stats Health: 8/8 healing, 0/0 mana, 5/8 rejuv."
time=14:00:19 level=DEBUG msg="Checking for items to stash..."
time=14:00:19 level=DEBUG msg="Checking for items to stash..."
time=14:00:19 level=INFO msg="Current life is 73%, healing on NPC"
time=14:00:27 level=DEBUG msg="CTA found: swapping weapon and casting Battle Command / Battle Orders"
time=14:00:27 level=DEBUG msg="Post CTA Buffing..."
time=14:00:33 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance"
time=14:00:34 level=DEBUG msg="Aborting item pickup, monster nearby" monster="{UnitID:35558181 Name:453 IsHovered:false Position:{X:3731 Y:5072} Stats:map[life:25344 maxlife:32768 level:79 damagereduced:25 fireresist:66 lightningresist:15 coldresist:130 poisonresist:15 velocitypercent:175 attackrate:100 otheranimrate:100 pierceidx:8785] Type:Minion}"
time=14:00:35 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance"
time=14:00:36 level=DEBUG msg="Aborting item pickup, monster nearby" monster="{UnitID:71116362 Name:453 IsHovered:true Position:{X:3731 Y:5073} Stats:map[life:18176 maxlife:32768 level:79 damagereduced:25 fireresist:66 lightningresist:15 coldresist:130 poisonresist:15 velocitypercent:175 attackrate:100 otheranimrate:100 pierceidx:8782] Type:Minion}"
time=14:00:37 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance"
time=14:00:37 level=DEBUG msg="Item Detected: RejuvenationPotion [2] at X:3728 Y:5063"
time=14:00:38 level=DEBUG msg="Picking up: Rejuvenation Potion [Normal]"
time=14:00:38 level=INFO msg="Item picked up: Rejuvenation Potion [Normal]"
time=14:00:38 level=DEBUG msg="Aborting item pickup, monster nearby" monster="{UnitID:1138009248 Name:453 IsHovered:false Position:{X:3733 Y:5064} Stats:map[life:5376 maxlife:32768 level:79 damagereduced:25 fireresist:66 lightningresist:15 coldresist:130 poisonresist:15 velocitypercent:175 attackrate:100 otheranimrate:100 pierceidx:8798] Type:Minion}"
time=14:00:38 level=DEBUG msg="Monster detected close to the player, casting Blizzard over it"
time=14:00:39 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance"
time=14:00:39 level=DEBUG msg="Aborting item pickup, monster nearby" monster="{UnitID:2161182633 Name:492 IsHovered:false Position:{X:3727 Y:5065} Stats:map[life:10240 maxlife:32768 level:80 magicresist:25 fireresist:100 lightningresist:25 coldresist:33 velocitypercent:175 attackrate:100 otheranimrate:100 pierceidx:8785] Type:Minion}"
time=14:00:39 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance"
time=14:00:40 level=DEBUG msg="Aborting item pickup, monster nearby" monster="{UnitID:284498216 Name:453 IsHovered:true Position:{X:3730 Y:5068} Stats:map[life:6656 maxlife:32768 level:79 damagereduced:25 fireresist:66 lightningresist:15 coldresist:130 poisonresist:15 velocitypercent:175 attackrate:100 otheranimrate:100 pierceidx:8798] Type:Minion}"
time=14:00:41 level=DEBUG msg="Looks like monster is not reachable, reducing max attack distance"
time=14:00:41 level=DEBUG msg="Item Detected: FullRejuvenationPotion [2] at X:3730 Y:5059"
time=14:00:41 level=DEBUG msg="Picking up: Full Rejuvenation Potion [Normal]"
time=14:00:41 level=INFO msg="item is too far away" item="Full Rejuvenation Potion"
time=14:00:41 level=INFO msg="item is too far away" item="Full Rejuvenation Potion"
time=14:00:42 level=INFO msg="item is too far away" item="Full Rejuvenation Potion"
time=14:00:42 level=DEBUG msg="Item could not be picked up, going back to town to sell junk and stash"
time=14:00:57 level=DEBUG msg="CTA found: swapping weapon and casting Battle Command / Battle Orders"
time=14:00:57 level=DEBUG msg="Post CTA Buffing..."
time=14:01:26 level=WARN msg="Game finished with errors, reason: max game length reached, try to exit game: 70.11. Game total time: 70.13s" supervisor="Blizzard Sorc" mapSeed=789973385
time=14:01:32 level=DEBUG msg="Fetching map data..." seed=86128373 difficulty=hell

**Comment by Millionaar** [comment]
No issues on my side, so first thought is it might be a config/setup issue
rather than a bot issue.

Are BO and BC bound to F6 and F7?
Did you have this working with BO previously or just added CTA?

Weird that it's saying "Monster detected close to the player, casting
Blizzard over it". but I guess that's possible at Frigid WP.

**Comment by HYPERTONE** [comment]
BO and BC were not bound before. 

This seems to have fixed the issue, thanks 👍 .
