### ISSUE TITLE
Bot is not stashing gold

### ISSUE THREAD

**Issue by jik0n** [hectorgimenez/koolo#31]
I let the bot run for a few hours and came back to it trying to pick up gold on the ground and its inv was full of gold. The runs I'm doing are: runs: [pit, diablo, baal, stony_tomb] and it doesn't appear to be stashing gold

**Comment by hectorgimenez** [comment]
it only stashes gold when stashing any other item, maybe didnt pickup anything during that time? But it's true that it should go to stash once character can not carry more gold

**Comment by jik0n** [comment]
Just did a test, put max gold on my sorc and ran the bot. Confirmed it just tries to pick up gold over and over without actually doing anything besides attempting to get the gold on the ground. I'm including a youtube link, it may take a bit for it to process to 1080p but you can get the idea in SD format

https://youtu.be/cTiDmbDVAG4

**Comment by jik0n** [comment]
as a temp workaround I've set my pickit to ignore gold for now on the ground

**Comment by hectorgimenez** [comment]
With this https://github.com/hectorgimenez/koolo/commit/8a631b4533090d7ce3a535fd6eee88e213fc647a the general idea is: character will force stash if exceedes 1/3 of the max gold. And also will skip picking up gold if character is already full, if you update your branch you can try

**Comment by hectorgimenez** [comment]
Also maybe we can implement the option for gambling, but honestly I never did it so not sure about what's the strategy, what kind of items are interesting, etc... even not sure if it's worth it or not

**Comment by jik0n** [comment]
Will update and try later today. As far as gambling goes it can be worth it if pickit can be used for the items that are gambled. Is this possible?

**Comment by hectorgimenez** [comment]
Yes, the pickit filtering can be used for it, but how to decide the type of item you want to gamble and based on what? Maybe you are only interested in circlets and nothing else, or maybe also gloves or rings/amulets... there should be a way to define those things. As said I never did gambling before so not sure what people usually do.

**Comment by jik0n** [comment]
circlets are super popular. Rings and amulets are popular as well because its a fast way to get them for crafting in the cube

**Comment by hectorgimenez** [comment]
@jik0n added basic gambling functionality, it requires to modify the config.yaml file with the latest few lines from the example file here https://github.com/hectorgimenez/koolo/blob/main/config/config.yaml.dist#L108-L113

**Comment by jik0n** [comment]
@hectorgimenez I'm going to try to test the gold fix tonight and gambling if I have time. I noticed in the config you only have "cornet" will this also pick "circlet" as well? Also, can we put any item name we want in there or does it have to be specially coded for it?

**Comment by hectorgimenez** [comment]
I only tested with coronet, amulet and ring, It's the same value that you use for the .nip files on the [name] attribute, so it should work with any item. If you only specify coronet will go only for coronets, if you want circlets as well you will need to add them into the list (and remove coronets if you don't want them). What it will try to do is buy one of each and restart the loop. For example, if you have [coronet, ring, amulet] the behavior will be:

- Buy one coronet
- Check if passes the item filter (based on the pickit)
- If not pass: sell it
- Buy one ring...
- Buy one amulet...
- Buy one coronet...

In case it finds something that passes the item filtering, it will break the loop and proceed to stash it.
