### ISSUE TITLE
Act 5 issues

### ISSUE THREAD

**Issue by jik0n** [hectorgimenez/koolo#32]
Blizz sorc was having issues where once baal was dead she'd go to talk to Malah then the bot would stop / close. I removed baal and added nihlathak but it appears no matter what if it involves A5 and Malah the bot crashes

2023-10-06T14:36:44.265-0500	FATAL	internal/single_supervisor.go:43	Panic detected, Koolo will exit	{"panic": "Error occurred calculating path, destination point outside current level and matching level not found"}
github.com/hectorgimenez/koolo/internal.(*SinglePlayerSupervisor).Start.func1
	github.com/hectorgimenez/koolo/internal/single_supervisor.go:43
runtime.gopanic
	runtime/panic.go:914
github.com/hectorgimenez/koolo/internal/pather.GetPath
	github.com/hectorgimenez/koolo/internal/pather/path_finder.go:28
github.com/hectorgimenez/koolo/internal/action/step.(*MoveToStep).Run
	github.com/hectorgimenez/koolo/internal/action/step/move_to.go:117
github.com/hectorgimenez/koolo/internal/action.(*StepChainAction).NextStep
	github.com/hectorgimenez/koolo/internal/action/action_step_chain.go:45
github.com/hectorgimenez/koolo/internal/action.(*Chain).NextStep
	github.com/hectorgimenez/koolo/internal/action/action_chain.go:43
github.com/hectorgimenez/koolo/internal/action.(*Chain).NextStep
	github.com/hectorgimenez/koolo/internal/action/action_chain.go:43
github.com/hectorgimenez/koolo/internal/action.(*Chain).NextStep
	github.com/hectorgimenez/koolo/internal/action/action_chain.go:43
github.com/hectorgimenez/koolo/internal.(*Bot).Run
	github.com/hectorgimenez/koolo/internal/bot.go:102
github.com/hectorgimenez/koolo/internal.(*SinglePlayerSupervisor).Start
	github.com/hectorgimenez/koolo/internal/single_supervisor.go:70
main.main.func2
	./main.go:96
golang.org/x/sync/errgroup.(*Group).Go.func1
	golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75

**Comment by hectorgimenez** [comment]
I think this should be fixed now on latest main branch
