### ISSUE TITLE
Act 2 Stashing Errors

### ISSUE THREAD

**Issue by Holynite** [hectorgimenez/koolo#321]
### Details

Bot seems to have issues trying to stash items in Act II. It runs back and forth around the stash trying to open it, but never successfully interacts with it. This will continue until the time limit on the game is reached, but does not happen every game. Anyone else run into this problem?

### Version

v0.4.0

### Logs

time=17:25:07 level=WARN msg="Game finished with errors, reason: max game length reached, try to exit game: 800.03. Game total time: 800.05s"

**Comment by girfli** [comment]
I have the same issue
