### ISSUE TITLE
Pickit Rules not working

### ISSUE THREAD

**Issue by Rubenwayne** [hectorgimenez/koolo#322]
### Details

2 questions:
- Configured the pickit rules for some low runes and other uniq items but the max quantity rule is unaltered. Example: Put maxquantity 10 pieces for Ral runes, but always take 1 as maximum. Also unmark items but still getting it.

- Add some items to the pickit config (unearthedwand Death's web) and I don't know if it's works because the question 1, and the low probabilty to get it ofc.

I've configured in config/nameCharacter/pickit/
Is there any other config rules?

### Version

v0.4.0

### Logs

time=21:05:40 level=DEBUG msg="For item RalRune found 1 max quantity from pickit rule, number of items in the stash tabs 1"

**Comment by Holynite** [comment]
I've recently updated my Ral pickit to 10 so it does work. The only thing I can think of right now is did you restart the bot after making the update and saving the pickit file? Pickits cannot be updated real time if I remember right and require restart.

**Comment by Millionaar** [comment]
Agreed with the above. Main things that go wrong would be:

1. Making updates in pickit files without bot restart (fully closed)
2. Making updates in pickit files within a different character config folder
3. Having the same pickit references in multiple files, or multiple locations in the same file. i.e. having runes referred to in the Misc.nip as well as a new Runes.nip or something.

**Comment by Rubenwayne** [comment]
Well finally I reinstalled again and will try... I don't know what happen really, hope it works. Thanks!
