### ISSUE TITLE
Koolo.exe

### ISSUE THREAD

**Issue by Checkboyt** [hectorgimenez/koolo#33]
I can not find the koolo.exe
where can I find it ?

**Comment by hectorgimenez** [comment]
If you are following the build from code instructions, once you run the build script a new directory called "build" should be created in the root directory, it's inside it.

**Comment by Checkboyt** [comment]
Diablo II: Resurrected
Diablo II: LOD 1.13c (required by https://github.com/blacha/diablo2/tree/master/packages/map)

Do I need both of Diablo2 resurrected and classic ?

**Comment by Checkboyt** [comment]
PS C:\Users\Administrator\Desktop\koolo-main> .\build bat
Start building Koolo
Cleaning up previous artifacts...
Building Koolo binary...
# github.com/robotn/gohook
..\..\go\pkg\mod\github.com\robotn\gohook@v0.41.0\event.go:51:10: undefined: addEvent
..\..\go\pkg\mod\github.com\robotn\gohook@v0.41.0\event.go:62:7: undefined: Start
..\..\go\pkg\mod\github.com\robotn\gohook@v0.41.0\event.go:75:18: undefined: KeyHold
..\..\go\pkg\mod\github.com\robotn\gohook@v0.41.0\event.go:83:18: undefined: KeyUp
..\..\go\pkg\mod\github.com\robotn\gohook@v0.41.0\event.go:95:22: undefined: KeyUp
..\..\go\pkg\mod\github.com\robotn\gohook@v0.41.0\event.go:96:4: undefined: End
..\..\go\pkg\mod\github.com\robotn\gohook@v0.41.0\event.go:113:7: undefined: Start
..\..\go\pkg\mod\github.com\robotn\gohook@v0.41.0\event.go:121:17: undefined: MouseMove
..\..\go\pkg\mod\github.com\robotn\gohook@v0.41.0\event.go:128:22: undefined: MouseDown
..\..\go\pkg\mod\github.com\robotn\gohook@v0.41.0\event.go:129:4: undefined: End
..\..\go\pkg\mod\github.com\robotn\gohook@v0.41.0\event.go:129:4: too many errors
# gocv.io/x/gocv
..\..\go\pkg\mod\gocv.io\x\gocv@v0.33.0\calib3d_string.go:3:9: undefined: CalibFlag
..\..\go\pkg\mod\gocv.io\x\gocv@v0.33.0\calib3d_string.go:29:9: undefined: CalibCBFlag
..\..\go\pkg\mod\gocv.io\x\gocv@v0.33.0\core_string.go:3:9: undefined: MatType
..\..\go\pkg\mod\gocv.io\x\gocv@v0.33.0\core_string.go:57:9: undefined: CompareType
..\..\go\pkg\mod\gocv.io\x\gocv@v0.33.0\core_string.go:75:9: undefined: CovarFlags
..\..\go\pkg\mod\gocv.io\x\gocv@v0.33.0\core_string.go:93:9: undefined: DftFlags
..\..\go\pkg\mod\gocv.io\x\gocv@v0.33.0\core_string.go:113:9: undefined: RotateFlag
..\..\go\pkg\mod\gocv.io\x\gocv@v0.33.0\core_string.go:125:9: undefined: KMeansFlags
..\..\go\pkg\mod\gocv.io\x\gocv@v0.33.0\core_string.go:137:9: undefined: NormType
..\..\go\pkg\mod\gocv.io\x\gocv@v0.33.0\core_string.go:159:9: undefined: TermCriteriaType
..\..\go\pkg\mod\gocv.io\x\gocv@v0.33.0\core_string.go:159:9: too many errors
# github.com/go-vgo/robotgo
..\..\go\pkg\mod\github.com\go-vgo\robotgo@v1.0.0-rc2.1\img.go:92:40: undefined: Bitmap
..\..\go\pkg\mod\github.com\go-vgo\robotgo@v1.0.0-rc2.1\img.go:107:38: undefined: Bitmap
..\..\go\pkg\mod\github.com\go-vgo\robotgo@v1.0.0-rc2.1\img.go:137:20: undefined: Bitmap
..\..\go\pkg\mod\github.com\go-vgo\robotgo@v1.0.0-rc2.1\screen.go:26:28: undefined: Rect
..\..\go\pkg\mod\github.com\go-vgo\robotgo@v1.0.0-rc2.1\robotgo_fn_v1.go:9:2: undefined: Move
..\..\go\pkg\mod\github.com\go-vgo\robotgo@v1.0.0-rc2.1\robotgo_fn_v1.go:17:2: undefined: Toggle
..\..\go\pkg\mod\github.com\go-vgo\robotgo@v1.0.0-rc2.1\robotgo_fn_v1.go:18:2: undefined: MilliSleep
..\..\go\pkg\mod\github.com\go-vgo\robotgo@v1.0.0-rc2.1\robotgo_fn_v1.go:20:2: undefined: MoveSmooth
..\..\go\pkg\mod\github.com\go-vgo\robotgo@v1.0.0-rc2.1\robotgo_fn_v1.go:21:2: undefined: Toggle
..\..\go\pkg\mod\github.com\go-vgo\robotgo@v1.0.0-rc2.1\robotgo_fn_v1.go:29:9: undefined: MoveSmooth
..\..\go\pkg\mod\github.com\go-vgo\robotgo@v1.0.0-rc2.1\robotgo_fn_v1.go:29:9: too many errors
Error occurred #1.

I got this problem, could you let me know how to solve it?

**Comment by hectorgimenez** [comment]
Yes, you need d2r and the classic at 1.13c version. 

Try to follow the steps here https://github.com/hectorgimenez/koolo#development-environment looks like you are missing some dependencies during the build process.
