### ISSUE TITLE
CTA 

### ISSUE THREAD

**Issue by RobotGaston** [hectorgimenez/koolo#34]
Hello, been a long time, happy to see this is going strong! Here I am with some work for you :) 

problem with CTA (battle orders given from the 2nd slot) (call to arms 2nd slot). (weapon swap on character to 2nd slot to cast call to arms)
---
sometimes, on rare occasions , character forced to leave the game by any reason with the switched from the main first to 2nd weapon slot ACTIVE (when he was trying to give BO to himself). (weapon with call to arms is ACTIVE)

In a new next created games character proceed to go with game routine thinking that now this 2nd slot with CTA is a main one (first) and the actual battle first slot is the 2nd now. 

Character is SWITCHING to cast BO from the CTA slot and trying to cast BO from the 1st battle slot now which is ACTIVE (where he dose not have CTA but his fighting weapons). and when fails switching to back to CTA (2nd) slot (which he thinks is the 1st now- which is actually 2nd with cta).

----------------
in short: Game Started. BO slot is on. Character switching to battle slot to give BA. It fails. Then switching back to CTA slot. and proceed with it's on. 
---------------

Suggested behaviour: Implement status force cheek: at the START of the game (in town) check which slot is active (1st or 2nd) if 2nd is ON detected - switch to 1st (press w) then continue with routine.

-----------------------------------------------------------------------Also, not important stuff, read only If you have time to read:

could you please give a quick help, with a CUSTOM script I'm trying to figure out?

What I'm trying to do:

I need the main character at the start of the game go to the location - waypoint (River of flame), make him PRESS THERE a BUTTON on a keyboard (NUMPAD1 for example) then wait there for about 30 seconds, and then go on with the rest of the runs. :)

Im trying this:
-------------------------------------------------------------------
func (m Getbo) BuildActions() []action.Action {
return []action.Action{
m.builder.WayPoint(area.RiverOfFlame), // Moving to starting point (RiverOfFlame))
hid.PressKey("NUMPAD1"), //Pressing a button on a keyboard
m.builder.Wait(time.Second*10),
}

-------------------------------------------------------------------
to make work like this: 
-------------------------------------------------------------------
func (m Getbo) BuildActions() []action.Action {
	return []action.Action{
		m.builder.WayPoint(area.RiverOfFlame), // Moving to starting point (RiverOfFlame))
                                   -----------------wait for th river of flame waypoint location is LOADED------------------
------------IN THIS LINE I need to press a BUTTON after character is LOADED on the river wp-----------(SEND a keypress)
		m.builder.Wait(time.Second*10),
	}

End script - go to others.
-----------------------------------------------------------------
problem, if  I add  :

hid.PressKey("NUMPAD1"),

it doesn't work in this condition. and giving me an ERROR.
It must be implemented somehow with another way :)
please?

Thank you.

Also, I liked the changed behaviour in CS and interaction with the seals. Now character is trying to clear around and only after that trying to press the seal, - working much better! Good job. (sometimes still misses seal defender thou (Lord de Seis) :( )

And, now we have one more problem with cs run: STORM CASTERS.

Sometimes, one of them or several flying off the map screen (into the burning lava), hiding behind walls, staying UNREACHABLE and unkillable for any spells that are casting :)

Character can't get aware of the situation and keeps attacking, attacking and attacking  aaaand attacking hopelessly, because STORM CASTER no matter what wont move from the taken Invincible position he is occupying... (
And forcing character to get stuck in a very long attacking loop keeping him firing his spells into the wall without any hope. (Thinking his attacking storm caster)

how to solve: 
ignore class type - storm caster completely, EXCEPT! unique seal defender...which is one of them unfortunately, 
or
make a counter - monster type - storm caster then - after x failed attacks - ignore and skip target + move on. :)

**Comment by hectorgimenez** [comment]
hey! thanks for the feedback, as usual.

For the CTA thing, I'm working on a refactor for that part and I will include this fix on it, it also happened to me sometimes.

About the key press in river of flame, could you try to explain a bit more about what you are trying to do? So maybe I can be a bit more specific or guide you in the right direction.

About the CS fixes, yeah at some point we need to tackle that, there is also an ongoing discussion here about the same topic: https://github.com/hectorgimenez/koolo/issues/30#issuecomment-1749467443

**Comment by RobotGaston** [comment]
thank you for reply. 
changes for the cta are coming, and this is great!

and I'm trying character to do this sequence of things: )

Steps:

at the start of the run-

1. Character should go to the waypoint. (river of flame for example).
2. Character should make sure he loaded into the location, and make a step  from waypoint.
3. Character should press a button on a keyboard (Numlock1 for example). (I'm calling another program from here (to make a series of steps for me)- switching to the second window, loading barb into waypoint and giving a bo, and giving control back to koolo) - since I can't program these steps with "go", I have to rely on a more simpler solution for me ... :)  )
4. Character should wait  being idle for some amount of time after the key  (Numlock1) was pressed. 
5. Character should end this script and move onto the next one. (andariel for example - start a run)


What I achieved - I can make character go to the river and wait there with the above koolo script, but I can't make it send a key press after it got into location - river , no matter what :)

What I need to do is to make character to --press a button (Numlock1)-- with the code in a koolo script I typed higher after the character took river waypoint and waiting there ... :)

In a way I tried to write it in a script above, it doesn't work.

If I'm not being clear please, tell me, I'll try to re-explain (or we can just scrap it as I feel uncomfortable to bother you with this :) ) ...but here I'm really trying to make it work for me  :) (as I don't have cta any more... unfortunately :) )

By the way, I know you've mentioned leader system working via discord early, but I have no Idea How can I use it, and could It be used for this purpose - FOR a barb to give a BO at the start of the run at the river waypoint to a main character at all... :)
If it can. Please confirm, and I'll go and try to setup it to work via discord :) 

Thank you for patience.
and your time.

**Comment by hectorgimenez** [comment]
I see your point, I don't think there is a proper solution right now. For what you want to do, I would say you need to add the presskey inside an step action, so, in your code, replace `hid.PressKey("NUMPAD1"), //Pressing a button on a keyboard` by 

```		
step.SyncStep(func(d data.Data) error {
	hid.PressKey("NUMPAD1")
	return nil
}),
```

**Comment by RobotGaston** [comment]
thank you for the suggestion, very much. I tried to implement it, the best way I could and the code is look like this:

func (m Getbo) BuildActions() []action.Action {
	return []action.Action{
		m.builder.WayPoint(area.RiverOfFlame), // Moving to starting point (Durance of Hate Level 2)
	step.SyncStep(func(d data.Data) error {
	hid.PressKey("NUMPAD1") //pressing a key on a keyboard
	return nil
}),
		m.builder.Wait(time.Second*2),
	
	}
}

but this code is not working for me and giving me this error: 

internal\run\getbo.go:24:3: cannot use step.SyncStep(func(d data.Data) error {…}) (value of type *step.SyncActionStep) as action.Action value in array or slice literal: *step.SyncActionStep does not implement action.Action (missing method NextStep)

thank you for trying to help with the customization. I don't have enough knowledge to look what I should change here...to make it work.
If it needs a lot of work please, just ignore the topic and close it. 
This custom does not concern the main tool in any way. 
And not a part of it.
I just thought there might be a simple solution for me. :)

Thank you again. <3
