### ISSUE TITLE
troubles running prepare_env.bat

### ISSUE THREAD

**Issue by bagusmatt** [hectorgimenez/koolo#41]
Having problems running prepare_env.bat

Tons of issues but it mostly seems to be opencv? Just to make sure, but when I Edit the 'Path' variable I just add 'C:\Users\Matt\Desktop\bot\mingw64\bin'. I added it to User and System variables just to be sure. I usually figure this stuff out but I'm stuck...

https://justpaste.it/6q67b

Thank you in advance!

**Comment by hectorgimenez** [comment]
OpenCV is not required anymore in latest main version
