### ISSUE TITLE
Act 5 merc not available

### ISSUE THREAD

**Issue by mufreewing** [hectorgimenez/koolo#45]
How can I use Act 5 merc

**Comment by hectorgimenez** [comment]
What kind of problem do you have with it? (I never used it)

**Comment by mufreewing** [comment]
act 3 act 5 When using merc

player perceives the merc

when I start a new game, I want to resurrect a merce.

It seems that the mercenary's HP is not recognized.


In our short opinion

It didn't seem to recognize the Act 5 merc, so I checked with the Act 3 merc, but it was the same problem.

thank you for your interest in my post.
