### ISSUE TITLE
Bot doesnt click through intro to char selection

### ISSUE THREAD

**Issue by IAmBlindNotDeaf** [hectorgimenez/koolo#450]
### Details

When i start the bot, normally it would click through the intro till char selection appears. But it doesnt do anything after starting (not even scrolling through my chars when i am in char selection).

I tried same with offline char:
- I click through intro to char selection
- I press enter to create offline game
- If i try to move, bot is giving direction but doesnt do anything itself

### Version

v0.5.0

### Logs

koolo-log-2024-08-21-13-23-50.txt
time=13:24:27 level=INFO msg="Starting Crash Detector ..." PID=15216 Supervisor="Sorc Nm Andariel"
time=13:24:32 level=DEBUG msg="Arranging windows" displaywidth=2560 displayheight=1440 "max columns"=2 "max rows"=2
time=13:24:33 level=DEBUG msg="Window Positions" supervisor="Sorc Nm Andariel" column=0 row=0 position=-10x0
time=13:24:33 level=ERROR msg="error running supervisor Sorc Nm Andariel: error waiting for character selection screen: character Habibi not found"
time=13:24:59 level=INFO msg="Stopping Crash Detector" PID=15216 Supervisor="Sorc Nm Andariel"
time=13:24:59 level=INFO msg="Crash Detector stopped." PID=15216 Supervisor="Sorc Nm Andariel"

koolo-log-Sorc Nm Andariel-2024-08-21-13-24-25.txt
time=13:24:27 level=INFO msg="Waiting for character selection screen..."
time=13:24:32 level=INFO msg="Character selection screen found"
time=13:24:32 level=INFO msg="Selecting character..."
time=13:24:59 level=INFO msg=Stopping... configuration="Sorc Nm Andariel"
time=13:24:59 level=INFO msg="Finished stopping" configuration="Sorc Nm Andariel"

**Comment by imneckro** [comment]
this is after latest d2r update

**Comment by imneckro** [comment]
still with 0.5.1 can't connect to battlenet.
this happened after d2r latest update.

**Comment by HristiyanBostandzhiev** [comment]
It works for me with 0.5.1
Just had to select Authentication method - Username & Password
If it's set to "none" the bot is searching for the character in single player

**Comment by imneckro** [comment]
It wasn't set to none

**Comment by Sunnyweeb** [comment]
idk why but i guess the auth function right now doesnt work(?), use the username and password method, if you have 2fa activated try to deactivate it
