### ISSUE TITLE
Bot confusing town portal with teleport

### ISSUE THREAD

**Issue by HristiyanBostandzhiev** [hectorgimenez/koolo#454]
### Details

It was running perfectly and the problem started mid runs (I didn't touch anything)
Here is video of the problem - https://streamable.com/e/xx6z94?

### Version

v0.5.1

### Logs

v0.5.1

**Comment by Sunnyweeb** [comment]
hey your comment is 2 weeks old and idk if you fixed it, but it has something to do with the "Back to Town Settings:" uncheck "Equipment Broken" then it should work fine. :D
