### ISSUE TITLE
Error vendor.go

### ISSUE THREAD

**Issue by qwekdo422** [hectorgimenez/koolo#46]
func VendorRefill
!b.shouldVisitVendor(d)

**Comment by hectorgimenez** [comment]
sorry, what's the problem there? could you elaborate?

**Comment by qwekdo422** [comment]
> sorry, what's the problem there? could you elaborate?

sorry. It was my mistake
IntelliJ IDE tool code assist is marked as an error, but there is no problem with execution.
![스크린샷 2023-10-24 085638](https://github.com/hectorgimenez/koolo/assets/17309741/80035eda-4f4c-46dc-9adb-10dea69b4e41)
