### ISSUE TITLE
Bot immediately portaling home instead of doing run

### ISSUE THREAD

**Issue by CCHaynes112** [hectorgimenez/koolo#462]
### Details

Bot will take wp to catacombs level 2, use CTA, teleport 1 or 2 times, and then create tp.
It will then go through the tp, and then go back through the tp.
...and then create another tp, etc.

### Version

0.5.1

### Logs

time=11:32:28 level=DEBUG msg="Belt Stats Health: 8/8 healing, 5/4 mana, 0/4 rejuv."
time=11:32:28 level=DEBUG msg="Checking for items to stash..."
time=11:32:28 level=DEBUG msg="Checking for items to stash..."
time=11:32:31 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=11:32:32 level=DEBUG msg="Load completed, continuing execution"
time=11:32:35 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=11:32:36 level=DEBUG msg="Load completed, continuing execution"
time=11:32:36 level=DEBUG msg="Checking for character corpse..."
time=11:32:36 level=DEBUG msg="Character corpse not found :D"
time=11:32:36 level=DEBUG msg="Checking for items to identify..."
time=11:32:36 level=DEBUG msg="No items to identify..."
time=11:32:36 level=DEBUG msg="Belt Stats Health: 8/8 healing, 5/4 mana, 0/4 rejuv."
time=11:32:36 level=DEBUG msg="Checking for items to stash..."
time=11:32:36 level=DEBUG msg="Checking for items to stash..."
time=11:32:38 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=11:32:39 level=DEBUG msg="Load completed, continuing execution"
time=11:32:42 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=11:32:43 level=DEBUG msg="Load completed, continuing execution"
time=11:32:43 level=DEBUG msg="Checking for character corpse..."
time=11:32:43 level=DEBUG msg="Character corpse not found :D"
time=11:32:43 level=DEBUG msg="Checking for items to identify..."
time=11:32:43 level=DEBUG msg="No items to identify..."
time=11:32:43 level=DEBUG msg="Belt Stats Health: 8/8 healing, 5/4 mana, 0/4 rejuv."
time=11:32:43 level=DEBUG msg="Checking for items to stash..."
time=11:32:43 level=DEBUG msg="Checking for items to stash..."
time=11:32:46 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=11:32:46 level=DEBUG msg="Load completed, continuing execution"
time=11:32:49 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=11:32:50 level=DEBUG msg="Load completed, continuing execution"
time=11:32:50 level=DEBUG msg="Checking for character corpse..."
time=11:32:50 level=DEBUG msg="Character corpse not found :D"
time=11:32:50 level=DEBUG msg="Checking for items to identify..."
time=11:32:50 level=DEBUG msg="No items to identify..."
time=11:32:50 level=DEBUG msg="Belt Stats Health: 8/8 healing, 5/4 mana, 0/4 rejuv."
time=11:32:50 level=DEBUG msg="Checking for items to stash..."
time=11:32:50 level=DEBUG msg="Checking for items to stash..."
time=11:32:53 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=11:32:53 level=DEBUG msg="Load completed, continuing execution"
time=11:32:57 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=11:32:58 level=DEBUG msg="Load completed, continuing execution"
time=11:32:58 level=DEBUG msg="Checking for character corpse..."
time=11:32:58 level=DEBUG msg="Character corpse not found :D"
time=11:32:58 level=DEBUG msg="Checking for items to identify..."
time=11:32:58 level=DEBUG msg="No items to identify..."
time=11:32:58 level=DEBUG msg="Belt Stats Health: 8/8 healing, 5/4 mana, 0/4 rejuv."
time=11:32:58 level=DEBUG msg="Checking for items to stash..."
time=11:32:58 level=DEBUG msg="Checking for items to stash..."
time=11:33:00 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=11:33:01 level=DEBUG msg="Load completed, continuing execution"
time=11:33:04 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=11:33:05 level=DEBUG msg="Load completed, continuing execution"
time=11:33:05 level=DEBUG msg="Checking for character corpse..."
time=11:33:05 level=DEBUG msg="Character corpse not found :D"
time=11:33:05 level=DEBUG msg="Checking for items to identify..."
time=11:33:05 level=DEBUG msg="No items to identify..."
time=11:33:05 level=DEBUG msg="Belt Stats Health: 8/8 healing, 5/4 mana, 0/4 rejuv."
time=11:33:05 level=DEBUG msg="Checking for items to stash..."
time=11:33:05 level=DEBUG msg="Checking for items to stash..."

**Comment by HristiyanBostandzhiev** [comment]
I had the same problem,  when I move some items from the stash and rearrange the order of the runs it gets fixed for some time.

**Comment by Sunnyweeb** [comment]
Hi, if your bot starts an run, teleports for exactly one frame and then opens the TP and goes to town and then to the tp on repeat, then maybe check your settings for "back to town" > "equipment broken", idk why but i had the exact same issue, and after deactivating that specific setting everything worked fine.
