### ISSUE TITLE
Cant connect to battlenet on bot launch. Stuck on singleplayer screen. 

### ISSUE THREAD

**Issue by LindsEmmo** [hectorgimenez/koolo#466]
### Details

As the title says. The bot launches directly from the d2r directory and not from battlenet app. Is there a way to change this>

### Version

v0.5.1

### Logs

None

**Comment by Sunnyweeb** [comment]
Open Koolo, press on "Settings" on your Specific Character Profile, "Battle.net settings" use "Username & Password", you then close the Battlenet App and run the Profile/Character normal. If the Username and Password doesnt work then you may have 2FA activated and need an Authentication Token, you get one from here: https://us.battle.net/login/en/?externalChallenge=login&app=OSI just log in and then copy the URL from your browser search bar (it looks weird and starts with local something) and put it in "Authentication Token", weirdly for ME only username and PW works, the auth token that should work 100% (as an example it works with D2R loader) doesnt work on koolo for me, idk. :D

**Comment by LindsEmmo** [comment]
Ive done that. Still have the same issue.

**Comment by iiBARDii** [comment]
Yeah, the same issue. Not connecting to battlenet, after logging and "connecting to battlenet" screen the game shows me my offline character list. I'm using "Username & Password", auth turned off

**Comment by Sunnyweeb** [comment]
Log out of Blizzard launcher with that account and check if you can login without 2fa/email fa, if you can login without then try to start the bot without blizzard launcher open

**Comment by iiBARDii** [comment]
I don't know why but it start working. Sometimes one post on Github is enougt)

**Comment by Millionaar** [comment]
the "auth turned off" bit is a bit of a giveaway. No auth = single player.
It doesn't launch from the Bnet app so people can run multiple instances.
Can this topic be closed now?

**Comment by JudeaDumont** [comment]
same issue here, completely logged out of battlenet, entered my un (email) and pw into koolo profile. no 2fa setup. can't get in.

I also notice I can't interact with the d2 window that comes up at all.

I just login with a un and pw, however, it does ask me to complete a captcha everytime. 

might need clearer instructions idk.

**Comment by artog11** [comment]
Hello. 

I also have this exact same issue, and have tried all recommended solutions listed in this thread. Unfortunately, I have not been able to find a resolution/work around. Nothing seems to work for me. Not username/password, nor Authentication Token. 

If anybody can provide some more assistance, I'd be very appreciative. 

Not sure what else to do in order to get this thing running. =/

**Comment by ceseleonfyah** [comment]
hey, I have the same proble. Neither acc/pw or token works for me..

**Comment by figgy914** [comment]
Any fix on this?
