### ISSUE TITLE
How to not skip Immunities?

### ISSUE THREAD

**Issue by LindsEmmo** [hectorgimenez/koolo#475]
### Details

Im running a nova sorc with infinity and sunder. I was just wondering why it still skips lightning immunes?

### Version

v0.5.1

### Logs

Nil

**Comment by Sunnyweeb** [comment]
what run? you can always just disable all immunity checks if the run does support it. 

such as: pindle, tz and so on

**Comment by LindsEmmo** [comment]
Chaos.

**Comment by Sunnyweeb** [comment]
okay thats weird, chaos doesnt have any ignore immunity setting, is that the only run you have? does it ONLY occur in chaos?

**Comment by LindsEmmo** [comment]
Yeah I believe it only happens in chaos. Elite pack or not (except seal) my nova sprc ignores the spirits. It's odd.

**Comment by Sunnyweeb** [comment]
does it happen all the time? i did a test with a hacked nova sorc, and let her run chaos with "focus only elites + kill diablo" enabled and it never skipped anything

**Comment by LindsEmmo** [comment]
It doesn't chicken, it literally just ignores the spirits. Every single game. I'll make a new test profile this afternoon and report back.

**Comment by panicco** [comment]
The script specifically ignores spirits to prevent from jumping to an un-walkable area as this MOB is always getting stuck behind the map walls. You could disable this but I would not recommend it.

to disable you will need to edit internal->run->diablo.go
There is a function called skipStormCasterFilter, it must be removed and replaced with the base filter throughout the code.
The function is baked into almost every other functions so it will be quite a bit of work to remove.

I am working on a Izual Script to run the area. I would recommend this as it can run spirits, as they spawn only 2 levels lower here.
