### ISSUE TITLE
Looping to town for Potions

### ISSUE THREAD

**Issue by panicco** [hectorgimenez/koolo#497]
### Details

No matter the Run selected the bot will enter the area, buff, teleport one step and then go back to town, take one step and return to portal and repeat until error or time out. It was working fine for about 50 runs then constant repeat of this error.

the output from logs just repeats over and over. I have tried changing pots settings around and nothing.

### Version

v0.5.1

### Logs

time=14:35:18 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=14:35:18 level=DEBUG msg="Load completed, continuing execution"
time=14:35:18 level=DEBUG msg="Checking for character corpse..."
time=14:35:18 level=DEBUG msg="Character corpse not found :D"
time=14:35:18 level=DEBUG msg="Checking for items to identify..."
time=14:35:18 level=DEBUG msg="No items to identify..."
time=14:35:18 level=DEBUG msg="Belt Stats Health: 8/8 healing, 8/8 mana, 0/0 rejuv."
time=14:35:18 level=DEBUG msg="Checking for items to stash..."
time=14:35:18 level=DEBUG msg="Checking for items to stash..."
time=14:35:21 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=14:35:21 level=DEBUG msg="Load completed, continuing execution"
time=14:35:22 level=DEBUG msg="CTA found: swapping weapon and casting Battle Command / Battle Orders"
time=14:35:22 level=DEBUG msg="Post CTA Buffing..."
time=14:35:26 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=14:35:26 level=DEBUG msg="Load completed, continuing execution"
time=14:35:26 level=DEBUG msg="Checking for character corpse..."
time=14:35:26 level=DEBUG msg="Character corpse not found :D"
time=14:35:26 level=DEBUG msg="Checking for items to identify..."
time=14:35:26 level=DEBUG msg="No items to identify..."
time=14:35:26 level=DEBUG msg="Belt Stats Health: 8/8 healing, 8/8 mana, 0/0 rejuv."
time=14:35:26 level=DEBUG msg="Checking for items to stash..."
time=14:35:26 level=DEBUG msg="Checking for items to stash..."

**Comment by Millionaar** [comment]
What town settings do you have? Go to town for broken equipment is buggy, so could be that if selected.
Do you have any low durability gear on? Also something that's come up in multiple help threads previously.

Try take off your CTA, does that fix it? Is it a javazon? I found the equipment/repair bugs meant that I just couldn't run CTA on a javazon because of needing to repair charges.

**Comment by panicco** [comment]
Yupp that was is, Broken gear. thank you for the help there.
I repaired my gear and back to working again.

For now I have removed the setting to return to town on broken gear. Hopefully that bugs can be smoothed out.

Also Was using a Blizz-Sorc as my Char.

Marking as closed.
