### ISSUE TITLE
town portal repair loop

### ISSUE THREAD

**Issue by Sunnyweeb** [hectorgimenez/koolo#498]
### Details

Hello! Again thanks for the free Bot!

If you select "Back to Town Settings:" > "Equipment Broken" the bot starts the run normally, walks to the desired farming area and opens a portal goes in (town) then instandly goes back to the area, opens a new one and so on in a loop until there are no town scrolls left, then it waits for the max game length.

One small thing would be nice for amazon: the ama should repair the javs every game one time. 

Log:
- start koolbot
- check go back to town: "equipment broken"
- walks to area
- opens tp to town and repairs gear
- goes back to area
- opens tp goes back to town
- goes instandly back in tp to farm area
- repeat until game closes duo to time

### Version

v0.5.1

### Logs

time=14:07:07 level=INFO msg="Waiting for character selection screen..."
time=14:07:15 level=INFO msg="Character selection screen found"
time=14:07:15 level=INFO msg="Selecting character..."
time=14:07:15 level=INFO msg="Character found"
time=14:07:19 level=DEBUG msg="Fetching map data..." seed=1349857473 difficulty=nightmare
time=14:07:20 level=DEBUG msg="Fetch completed" ms=1605
time=14:07:20 level=DEBUG msg="Fetching map data..." seed=1349857473 difficulty=nightmare
time=14:07:22 level=DEBUG msg="Fetch completed" ms=1338
time=14:07:22 level=DEBUG msg="Fetching map data..." seed=1349857473 difficulty=nightmare
time=14:07:23 level=DEBUG msg="Fetch completed" ms=1252
time=14:07:23 level=INFO msg="Starting Game #0. Run list: eldritch"
time=14:07:23 level=INFO msg="Running: eldritch"
time=14:07:23 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=14:07:23 level=DEBUG msg="Load completed, continuing execution"
time=14:07:23 level=DEBUG msg="Switching to legacy mode..."
time=14:07:24 level=DEBUG msg="Checking for character corpse..."
time=14:07:24 level=DEBUG msg="Character corpse not found :D"
time=14:07:24 level=DEBUG msg="Checking for items to stash..."
time=14:07:24 level=DEBUG msg="Checking for items to identify..."
time=14:07:24 level=DEBUG msg="No items to identify..."
time=14:07:24 level=DEBUG msg="Belt Stats Health: 5/6 healing, 0/0 mana, 0/6 rejuv."
time=14:07:24 level=DEBUG msg="Checking for items to stash..."
time=14:07:24 level=DEBUG msg="Checking for items to stash..."
time=14:07:24 level=INFO msg="Current life is 66%, healing on NPC"
time=14:07:26 level=INFO msg="Repairing Glaive, item durability is -1 percent"
time=14:07:35 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=14:07:37 level=DEBUG msg="Load completed, continuing execution"
time=14:07:37 level=DEBUG msg="Checking for character corpse..."
time=14:07:37 level=DEBUG msg="Character corpse not found :D"
time=14:07:37 level=DEBUG msg="Checking for items to identify..."
time=14:07:37 level=DEBUG msg="No items to identify..."
time=14:07:37 level=DEBUG msg="Belt Stats Health: 5/6 healing, 0/0 mana, 0/6 rejuv."
time=14:07:37 level=DEBUG msg="Checking for items to stash..."
time=14:07:37 level=DEBUG msg="Checking for items to stash..."
time=14:07:37 level=INFO msg="Repairing Glaive, item durability is -1 percent"
time=14:07:45 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=14:07:46 level=DEBUG msg="Load completed, continuing execution"
time=14:07:49 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=14:07:51 level=DEBUG msg="Load completed, continuing execution"
time=14:07:51 level=DEBUG msg="Checking for character corpse..."
time=14:07:51 level=DEBUG msg="Character corpse not found :D"
time=14:07:51 level=DEBUG msg="Checking for items to identify..."
time=14:07:51 level=DEBUG msg="No items to identify..."
time=14:07:51 level=DEBUG msg="Belt Stats Health: 5/6 healing, 0/0 mana, 0/6 rejuv."
time=14:07:51 level=DEBUG msg="Checking for items to stash..."
time=14:07:51 level=DEBUG msg="Checking for items to stash..."
time=14:07:53 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=14:07:53 level=DEBUG msg="Load completed, continuing execution"
time=14:07:57 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=14:07:58 level=DEBUG msg="Load completed, continuing execution"
time=14:07:58 level=DEBUG msg="Checking for character corpse..."
time=14:07:58 level=DEBUG msg="Character corpse not found :D"
time=14:07:58 level=DEBUG msg="Checking for items to identify..."
time=14:07:58 level=DEBUG msg="No items to identify..."
time=14:07:58 level=DEBUG msg="Belt Stats Health: 5/6 healing, 0/0 mana, 0/6 rejuv."
time=14:07:58 level=DEBUG msg="Checking for items to stash..."
time=14:07:58 level=DEBUG msg="Checking for items to stash..."
time=14:08:00 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=14:08:00 level=DEBUG msg="Load completed, continuing execution"
time=14:08:04 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=14:08:05 level=DEBUG msg="Load completed, continuing execution"
time=14:08:05 level=DEBUG msg="Checking for character corpse..."
time=14:08:05 level=DEBUG msg="Character corpse not found :D"
time=14:08:05 level=DEBUG msg="Checking for items to identify..."
time=14:08:05 level=DEBUG msg="No items to identify..."
time=14:08:05 level=DEBUG msg="Belt Stats Health: 5/6 healing, 0/0 mana, 0/6 rejuv."
time=14:08:05 level=DEBUG msg="Checking for items to stash..."
time=14:08:05 level=DEBUG msg="Checking for items to stash..."
time=14:08:07 level=DEBUG msg="Loading screen detected, waiting until loading screen is gone"
time=14:08:07 level=DEBUG msg="Load completed, continuing execution"
time=14:08:08 level=INFO msg=Stopping... configuration=AmaGrail
time=14:08:08 level=INFO msg="Finished stopping" configuration=AmaGrail

**Comment by panicco** [comment]
Most likely this,
#497
