### ISSUE TITLE
Picket isn't followed

### ISSUE THREAD

**Issue by Unfolds** [hectorgimenez/koolo#50]
I've noticed stats on the picket aren't followed at all? I've turned off low stat items but yet he keeps stashing them xD

**Comment by Unfolds** [comment]
I use the pickit provided and haven't added anything different, he picks up any magic find % chancies and resistance vipermagi

[name] == chaingloves 		&& [quality] == unique && [flag] != ethereal # [itemmagicbonus] >= 40

[name] == serpentskinarmor 	&& [quality] == unique && [flag] != ethereal # [coldresist] >= 35 && 
[magicdamagereduction] >= 13

**Comment by Millionaar** [comment]
@Unfolds Have you checked the 'unid.nip' pickit? Lots of unique items in there that it will pickup, despite the 'unique.nip' pickit file having the stats limited.

**Comment by hectorgimenez** [comment]
Entire new pickit parser has been rolled out, feel free to open it again if this is still happening
