### ISSUE TITLE
Static field not static fielding enough on Nova Sorc

### ISSUE THREAD

**Issue by itsdaburgundy** [hectorgimenez/koolo#500]
Nova sorc is only static fielding bosses 2-3 times (To about 50-60% health)

**Comment by Millionaar** [comment]
what % are you hoping for? In hell it only goes down to 50% health. Any more casts and it's wasted for most people.
2 casts = 56% life remaining
3 casts = 42% life remaining but will be limited to 50%, so even the 3rd cast is only half effective
This ignores minus resists from auras/spells/gear, but it would work out similar in terms of # of casts anyway.

If you really want to:
In the file "internal/character/lightning_sorceress.go" you could change the number of casts for each boss.

"step.SecondaryAttack(skill.StaticField, m.UnitID, 3,"
If you change the 3 it could cast more statics on that boss.
Make the changes within your internal folder, run the build batch file to include the changes in your koolo, then try run it again.

**Comment by itsdaburgundy** [comment]
Hi

Sorry my mistake :D

thanks for the info, might fiddle with some things just out of curiosity

**Comment by elobo91** [comment]
If you use lastest version it has validation on UI so you cant set it improperly =)
