### ISSUE TITLE
TZ Burial-Crypt-Mausoleum

### ISSUE THREAD

**Issue by itsdaburgundy** [hectorgimenez/koolo#509]
### Details

Bot goes burial-crypt then skips Mausoleum

### Version

v0.5.1

### Logs

time=08:02:59 level=INFO msg="Running: TerrorZone Run: Burial Grounds, Crypt, Mausoleum"
time=08:07:03 level=DEBUG msg="Destination area not found" area="Cold Plains"
time=08:07:04 level=WARN msg="Game finished with errors, reason: unrecoverable error occurred, game can not continue: attempt limit reached on step: InteractEntranceStep: area Cold Plains [3]  not found. Game total time: 244.50s" supervisor=fifif mapSeed=1227568139

**Comment by LotusElise88** [comment]
Do you have Wp I’m running fine but I can’t figure out how to stop it from picking up rares and magic that aren’t in nip

**Comment by itsdaburgundy** [comment]
I do have the wp
Jóhannes Berg

**Comment by HYPERTONE** [comment]
> Do you have Wp I’m running fine but I can’t figure out how to stop it from picking up rares and magic that aren’t in nip

I've had this exact same issue. What have you tried?

**Comment by itsdaburgundy** [comment]
Nothing. I Just dont run those
