### ISSUE TITLE
How to not pick up everythingg

### ISSUE THREAD

**Issue by rcneher** [hectorgimenez/koolo#516]
### Details

The bot is great and I have tried doing it myself but it would be great if the pickit files made it so the bot wouldn't even pick up things that you don't want.

I attempted to remove items from the d2go folder that I replaced in go.mod:

replace github.com/hectorgimenez/d2go => F:/Downloads/BOTS/d2go

This just caused it to fail on:     d.CollisionGrid = gd.GetCachedMapData(isNewGame).CollisionGrid(d.PlayerUnit.Area)

If i get it to work, i'll let everyone else know the fix.

### Version

newest

### Logs

CollisionGrid was not found

**Comment by HYPERTONE** [comment]
I have the same issue.

My solution was to delete a lot of items in the pickit files. It hasn't fully resolved the issue but it seems to have significantly reduced the random items that get picked up.

**Comment by rcneher** [comment]
the pickit file doesn't disallow items from being picked up but only the items you keep.
