### ISSUE TITLE
hi friend i have a question

### ISSUE THREAD

**Issue by qwekdo422** [hectorgimenez/koolo#52]
I do not speak English well. Understand me
Although my development skills are beginner,
I created a shopbot

ShouldItemIt == true -> I want to know the tab location of the shop

Now I don't know the location of the shop's tab, so I'm forced to use tab2.

--------------------------------------------------------------------------------------------------------
func (a Shopbot) BuildActions() []action.Action {
	actions := []action.Action{
		a.builder.WayPoint(area.DuranceOfHateLevel2),
		a.builder.WayPoint(area.KurastDocks),
		action.NewChain(func(d data.Data) []action.Action {
			return a.builder.ShopbotNPC()
		}),
	}
	return actions
}

---------------------------------------------------------------------------------------------------------

func (b *Builder) ShopbotNPC() []Action {
	return []Action{
		b.ShopbotSearchAndBuy(),
	}
}

func (b *Builder) ShopbotSearchAndBuy() *Chain {
	return NewChain(func(d data.Data) []Action {
		openShopStep := step.KeySequence("home", "down", "enter")
		vendorNPC := town.GetTownByArea(d.PlayerUnit.Area).RefillNPC()
		// Jamella trade button is the first one
		if vendorNPC == npc.Jamella {
			openShopStep = step.KeySequence("home", "enter")
		}

		return []Action{b.InteractNPC(vendorNPC,
			openShopStep,
			step.Wait(time.Second),
			step.SyncStep(func(d data.Data) error {
				switchTab(2)
				helper.Sleep(500)
				for _, i := range d.Items.ByLocation(item.LocationVendor) {
					if !b.ShouldItemIt(i) || i.IsPotion() {
						continue
					}

					if !(strings.Contains(string(i.Name), string("Scepter")) || strings.Contains(string(i.Name), string("Wand"))) {
						continue
					}

					/*
						screenPos := ui.GetScreenCoordsForItem(i)
						for tabIdx := 1; tabIdx < 5; tabIdx++ {
							switchTab(tabIdx)
							helper.Sleep(600)
							hid.MovePointer(screenPos.X, screenPos.Y)
							helper.Sleep(600)
							b.logger.Debug(fmt.Sprintf("Item org : [%d], hover: [%d]", i.UnitID, d.HoverData.UnitID))
							fmt.Println(d.HoverData)
							if i.UnitID == d.HoverData.UnitID {
								b.logger.Debug(fmt.Sprintf("TabIdx [%d]", tabIdx))
								b.logger.Debug(fmt.Sprintf("Item org : [%d], hover: [%d]", i.UnitID, d.HoverData.UnitID))
								break
							}
						}
					*/

					if b.BuyItem(i) {
						b.logger.Debug(fmt.Sprintf("Item %s [%d] buy", i.Name, i.Quality))
						break
					}
					break
				}
				return nil
			}),
			step.KeySequence("esc"),
		)}
	})
}

func (b *Builder) ShouldItemIt(i data.Item) bool {
	return itemfilter.Evaluate(i, config.Config.Runtime.Rules)
}

func (b *Builder) BuyItem(i data.Item) bool {
	helper.Sleep(500)
	screenPos := ui.GetScreenCoordsForItem(i)
	hid.MovePointer(screenPos.X, screenPos.Y)
	helper.Sleep(500)
	hid.Click(hid.RightButton)
	helper.Sleep(900)
	b.logger.Debug(fmt.Sprintf("Purchased %s [X:%d Y:%d]", i.Name, i.Position.X, i.Position.Y))
	return true
}

**Comment by hectorgimenez** [comment]
Sadly I don't think we can get the shop tab at this point.
