### ISSUE TITLE
Walking Foh skips buffing and gets stuck in river of flame

### ISSUE THREAD

**Issue by roed5** [hectorgimenez/koolo#521]
### Details

Walking Foh skips buffing holy shield at waypoint when no CTA is equipped.
Bot will cast holy shield about 1/3rd of the way to chaos.
When CTA is equipped the bot buffs at the waypoint like normal.

Bot then gets stuck on monsters while navigating through river of flame and has trouble clearing a path.
Does not happen in 0.5.1

https://github.com/user-attachments/assets/c2688dd5-2977-4812-87f1-b19700d11621

### Version

refactor

### Logs

time=01:52:44 level=INFO msg="Starting Game #4. Run list: diablo"
time=01:52:44 level=DEBUG msg="Fetching map data..." seed=330551600 difficulty=nightmare
time=01:52:49 level=DEBUG msg="Fetch completed" ms=4773
time=01:52:49 level=DEBUG msg="Switching to legacy mode..."
time=01:52:50 level=DEBUG msg="Checking for items to identify..."
time=01:52:50 level=DEBUG msg="No items to identify..."
time=01:52:50 level=DEBUG msg="Belt Stats Health: 2/8 healing, 4/4 mana, 0/4 rejuv."
time=01:52:50 level=DEBUG msg="Need more pots, let's buy them."
time=01:52:50 level=INFO msg="Visiting vendor..." forceRefill=false
time=01:52:54 level=DEBUG msg="Buying: 6 Healing potions and 0 Mana potions"
time=01:52:55 level=DEBUG msg="Purchased Greater Healing Potion [X:9 Y:9]"
time=01:52:56 level=DEBUG msg="Purchased Greater Healing Potion [X:9 Y:9]"
time=01:52:57 level=DEBUG msg="Purchased Greater Healing Potion [X:9 Y:9]"
time=01:52:58 level=DEBUG msg="Purchased Greater Healing Potion [X:9 Y:9]"
time=01:52:59 level=DEBUG msg="Purchased Greater Healing Potion [X:9 Y:9]"
time=01:53:00 level=DEBUG msg="Purchased Greater Healing Potion [X:9 Y:9]"
time=01:53:01 level=DEBUG msg="Checking for items to stash..."
time=01:53:01 level=DEBUG msg="Checking for items to stash..."
time=01:53:01 level=DEBUG msg="Cube recipes are disabled, skipping"
time=01:53:05 level=DEBUG msg="Post CTA Buffing..."
time=01:53:28 level=DEBUG msg="Monsters detected close to the item being picked up, killing them..." monster="{UnitID:34 Name:305 IsHovered:false Position:{X:7784 Y:5722} Stats:map[life:31744 maxlife:32768 level:57 fireresist:60 lightningresist:60 velocitypercent:75 attackrate:100 otheranimrate:100 pierceidx:13508] Type:None States:[44 105]}"
time=01:53:28 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:29 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:29 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:29 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:29 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:30 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:30 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:30 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:30 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:31 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:31 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:31 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:31 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:32 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:32 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:32 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:32 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:33 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:33 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:33 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:33 level=DEBUG msg="Item Detected: Flail [6] at X:7778 Y:5733"
time=01:53:33 level=DEBUG msg="Picking up: Flail [Rare]"
time=01:53:33 level=DEBUG msg="Using HealingPotion potion on Mercenary [Column: 2]. HP: 51"
time=01:53:36 level=INFO msg="Picked up: Flail [Rare]"
time=01:53:36 level=DEBUG msg="Monsters detected close to the item being picked up, killing them..." monster="{UnitID:34 Name:305 IsHovered:false Position:{X:7784 Y:5722} Stats:map[life:28672 maxlife:32768 level:57 fireresist:60 lightningresist:60 velocitypercent:75 attackrate:100 otheranimrate:100 pierceidx:13510] Type:None States:[28 44 105 107]}"
time=01:53:36 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:36 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:36 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:37 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:37 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:37 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:38 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:38 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:38 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:38 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:39 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:39 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:39 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:39 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:40 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:40 level=DEBUG msg="Item Detected: ShortSpear [4] at X:7780 Y:5729"
time=01:53:41 level=DEBUG msg="Picking up: Short Spear [Magic]"
time=01:53:41 level=INFO msg="Picked up: Short Spear [Magic]"
time=01:53:41 level=DEBUG msg="Monsters detected close to the item being picked up, killing them..." monster="{UnitID:33 Name:305 IsHovered:false Position:{X:7791 Y:5713} Stats:map[life:32768 maxlife:32768 level:57 fireresist:60 lightningresist:60 velocitypercent:75 attackrate:100 otheranimrate:100 pierceidx:13502] Type:None States:[105]}"
time=01:53:41 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:42 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:42 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:42 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:42 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:43 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:43 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:43 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:44 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:53:44 level=DEBUG msg="Item Detected: RejuvenationPotion [2] at X:7778 Y:5729"
time=01:53:44 level=DEBUG msg="Picking up: Rejuvenation Potion [Normal]"
time=01:53:44 level=INFO msg="Picked up: Rejuvenation Potion [Normal]"
time=01:53:45 level=DEBUG msg="Post CTA Buffing..."
time=01:53:52 level=DEBUG msg="Using HealingPotion potion [Column: 2]. HP: 74 MP: 100"
time=01:54:00 level=DEBUG msg="Using HealingPotion potion [Column: 2]. HP: 75 MP: 100"
time=01:54:10 level=DEBUG msg="Monsters detected close to the item being picked up, killing them..." monster="{UnitID:43 Name:305 IsHovered:false Position:{X:7827 Y:5670} Stats:map[life:32768 maxlife:32768 level:57 fireresist:60 lightningresist:60 velocitypercent:75 attackrate:100 otheranimrate:100 pierceidx:13519] Type:None States:[105 107]}"
time=01:54:11 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:54:11 level=INFO msg="Enemy is out of range and can not be reached" monster=305
time=01:54:19 level=DEBUG msg="Using HealingPotion potion [Column: 2]. HP: 70 MP: 100"
time=01:54:24 level=DEBUG msg="Using HealingPotion potion [Column: 1]. HP: 63 MP: 100"
time=01:54:27 level=DEBUG msg="Using RejuvenationPotion potion [Column: 4]. HP: 85 MP: 100"
time=01:54:34 level=DEBUG msg="Using HealingPotion potion on Mercenary [Column: 1]. HP: 78"
time=01:54:42 level=DEBUG msg="Using HealingPotion potion [Column: 1]. HP: 68 MP: 100"
time=01:54:52 level=DEBUG msg="Using HealingPotion potion [Column: 1]. HP: 74 MP: 100"
time=01:54:55 level=DEBUG msg="Item Detected: Amulet [4] at X:7822 Y:5621"
time=01:54:56 level=INFO msg="At least 4 monsters detected close to the character, targeting closest one: 189"
time=01:55:06 level=DEBUG msg="Picking up: Amulet [Magic]"
time=01:55:06 level=INFO msg="Picked up: Amulet [Magic]"
time=01:55:06 level=DEBUG msg="Monsters detected close to the item being picked up, killing them..." monster="{UnitID:59 Name:311 IsHovered:false Position:{X:7822 Y:5621} Stats:map[life:32256 maxlife:32768 level:57 fireresist:40 lightningresist:80 coldresist:40 poisonresist:40 velocitypercent:75 attackrate:100 otheranimrate:100 pierceidx:13442] Type:None States:[105]}"
time=01:55:11 level=DEBUG msg="Item Detected: Amulet [4] at X:7822 Y:5621"
time=01:55:11 level=DEBUG msg="Picking up: Amulet [Magic]"
time=01:55:12 level=INFO msg="Picked up: Amulet [Magic]"
time=01:55:12 level=DEBUG msg="Item Detected: Flail [4] at X:7780 Y:5676"
time=01:55:23 level=DEBUG msg="Picking up: Flail [Magic]"
time=01:55:24 level=INFO msg="Picked up: Flail [Magic]"
time=01:55:24 level=DEBUG msg="Clearing area around character..." distance=10
time=01:55:26 level=DEBUG msg="Checking for items to identify..."
time=01:55:26 level=INFO msg="Identifying 4 items..."
time=01:55:37 level=INFO msg="Visiting vendor..." forceRefill=false
time=01:55:43 level=DEBUG msg="Buying: 8 Healing potions and 0 Mana potions"
time=01:55:44 level=DEBUG msg="Purchased Greater Healing Potion [X:9 Y:8]"
time=01:55:45 level=DEBUG msg="Purchased Greater Healing Potion [X:9 Y:8]"
time=01:55:46 level=DEBUG msg="Purchased Greater Healing Potion [X:9 Y:8]"
time=01:55:47 level=DEBUG msg="Purchased Greater Healing Potion [X:9 Y:8]"
time=01:55:48 level=DEBUG msg="Purchased Greater Healing Potion [X:9 Y:8]"
time=01:55:49 level=DEBUG msg="Purchased Greater Healing Potion [X:9 Y:8]"
time=01:55:50 level=DEBUG msg="Purchased Greater Healing Potion [X:9 Y:8]"
time=01:55:51 level=DEBUG msg="Purchased Greater Healing Potion [X:9 Y:8]"
time=01:55:51 level=DEBUG msg="Filling TP Tome..."
time=01:55:52 level=DEBUG msg="Filling IDs Tome..."
time=01:55:54 level=DEBUG msg="Item Amulet [Magic] sold"
time=01:55:55 level=DEBUG msg="Item Flail [Rare] sold"
time=01:55:56 level=DEBUG msg="Item Flail [Magic] sold"
time=01:55:57 level=DEBUG msg="Item Short Spear [Magic] sold"
time=01:55:57 level=DEBUG msg="Checking for items to stash..."
time=01:55:57 level=DEBUG msg="Checking for items to stash..."
time=01:55:57 level=DEBUG msg="Cube recipes are disabled, skipping"
time=01:55:58 level=INFO msg=Pausing... configuration="lower foh"

**Comment by elobo91** [comment]
thats because refactor branch is not a final product  its constantly changing.
Currently doesnt handle the clearing to chaos by walking  but is on the todo list.
