### ISSUE TITLE
Not creating game after last update

### ISSUE THREAD

**Issue by HristiyanBostandzhiev** [hectorgimenez/koolo#553]
### Details

After the last update (0.6.1) when bot is started it goes through the characters and then stops on the rigth one, but doest not click on play and just stays like this

### Version

0.6.1

### Logs

time=11:00:18 level=INFO msg="Waiting for character selection screen..."
time=11:00:18 level=INFO msg="Character selection screen found"
time=11:00:18 level=INFO msg="Selecting character..."
time=11:00:18 level=INFO msg="Character found"
time=11:00:21 level=INFO msg=Stopping... configuration=PoliCron
time=11:00:21 level=INFO msg="Finished stopping" configuration=PoliCron
time=11:00:24 level=ERROR msg="Error creating new game: failed to create game"

**Comment by artosimonyan** [comment]
Most likely you don't have the correct resolution. Make sure the window's set to 1280x720

**Comment by HristiyanBostandzhiev** [comment]
@artosimonyan Yep... that was it.
I didn't have to do this before it automatically changed the game to windowed mode and changed the resolution, but it works now .
Thanks a lot!
