### ISSUE TITLE
minor stuff/improvements

### ISSUE THREAD

**Issue by Elanoran** [hectorgimenez/koolo#56]
Thanks for your hard work, just what i needed! Some minor stuff/improvements:

1.  sometimes the bot fails to id items just after exiting the portal, leaving the game menu open (esc), (maybe my vm machine is too slow)
2.  when it fails to id items, or game crash, items are stashed in the chest unidentified.
3.  maybe have a way to use cain to id items in config
4.  ~~a way to set game creation name prefix in config, ie somegamename and it will ad the numbers itself~~
5.  keys are not set as standard in the picit files, and it will get stuck at meph with no keys, when trying to open locked chests ([Name] == Key # # [MaxQuantity] == 12)

*cheers*

**Comment by Millionaar** [comment]
Agreed on point 1, mine does the same sometimes and happens not in VM also.
Definitely can happen if you have an item in inventory it wants to identify but it can't because it's in a locked square in config. I'd try check that in the first instance.

**Comment by Elanoran** [comment]
Thank you for confirming the issue, all my locked squares are occupied by charms etc. I will try mess around and see if i can figure out how to maybe ad a delay after exit the portal and see if that will work.

I also experience another issue that has already been posted about items being stuck in hand after new game, maybe after a crash?, might have to ad a function to drop item first thing when enter the game in that case, will see if i can do that as well for testing.

**Comment by Elanoran** [comment]
After adding a delay when identify objects i have not had any issues so far, 100+ games.

identify.go

`b.logger.Debug("Checking for items to identify...")
		if len(items) == 0 || skipIdentify {
			b.logger.Debug("No items to identify...")
			return
		}

		helper.Sleep(2000)

		idTome, found := d.Items.Find(item.TomeOfIdentify, item.LocationInventory)
		if !found {
			b.logger.Warn("ID Tome not found, not identifying items")
			return
		}`

**Comment by hectorgimenez** [comment]
Hello! Thanks for reporting this (and providing the solution), let me implement it in main branch.
