### ISSUE TITLE
keep getting this error

### ISSUE THREAD

**Issue by AamonVan** [hectorgimenez/koolo#59]
2023-12-28T18:23:00.132+0100	WARN	internal/single_supervisor.go:72	Game finished with errors, reason: unrecoverable error occurred, game can not continue: attempt limit reached on step: InteractEntranceStep: area 41 not found. Game total time: 69.30s
github.com/hectorgimenez/koolo/internal.(*SinglePlayerSupervisor).Start
	github.com/hectorgimenez/koolo/internal/single_supervisor.go:72
main.main.func2
	./main.go:91
golang.org/x/sync/errgroup.(*Group).Go.func1
	golang.org/x/sync@v0.5.0/errgroup/errgroup.go:75

And it leave the game
Any Idea?

**Comment by hectorgimenez** [comment]
Is this always happening to you? I think I also face this from time to time when doing stony tombs, but not a very common problem for me

**Comment by AamonVan** [comment]
Can't make it work this is my config:

debug:
  log: true # Prints extra log information
  renderMap: false # Render current map data into 'cg.png' file

logFilePath: log.txt
maxGameLength: 500 # Max game length (in seconds), bot will try to quit game arrived that point
D2LoDPath: 'D:\Diablo II'

# In order to use to Discord Bot, you need the Application Token. https://discord.com/developers/docs/intro
discord:
  enabled: false
  channelId: ''
  token: ''

telegram:
  enabled: false
  chatId: 0
  token: ''

health: # Healing configuration, all values in %
  healingPotionAt: 75
  manaPotionAt: 10
  rejuvPotionAtLife: 50
  rejuvPotionAtMana: 0
  mercHealingPotionAt: 80
  mercRejuvPotionAt: 30
  chickenAt: 30
  mercChickenAt: 10

bindings:
  openInventory: i
  openCharacterScreen: c
  openSkillTree: t
  openQuestLog: q
  potion1: 1
  potion2: 2
  potion3: 3
  potion4: 4

  # Skills
  forceMove: e
  standStill: shift
  swapWeapon: w
  teleport: a
  tp: f1
  CTABattleCommand: f3
  CTABattleOrders: f2

  # Class specific bindings
  sorceress:
    blizzard: f2
    staticField: f3
    frozenArmor: f5
    fireBall: f2 # During leveling only
    nova: f2
    energyShield: f8

  paladin:
    concentration: z # Will be used for Might during leveling
    holyShield: x
    vigor: f6
    redemption: f8
    cleansing: f4

inventory:
  inventoryLock:
    - [ 1, 1, 1, 1, 1, 1, 0, 0, 0, 0 ] # 0: Item locked and won't be moved.
    - [ 1, 1, 1, 1, 1, 1, 0, 0, 0, 0 ] # 1: Item unlocked, it will be stashed, sold or dropped.
    - [ 1, 1, 1, 1, 1, 1, 0, 0, 0, 0 ]
    - [ 1, 1, 1, 1, 1, 1, 0, 0, 0, 0 ]

  beltColumns: # Amount of columns for each type of potion, sum of all should not be more than 4
    healing: 0
    mana: 0
    rejuvenation: 4

character:
  class: hammerdin # Allowed values: sorceress, lightning, hammerdin, paladin (leveling only)
  castingFrames: 8 # https://diablo2.diablowiki.net/Breakpoints#Faster_Cast_Rate
  useMerc: true

game:
  clearTPArea: true # Will clear the TP area before clicking it
  difficulty: hell # Allowed values: normal, nightmare, hell
  randomizeRuns: false # Will randomize the order of the runs each game
  # Just add the runs you want to do and they will be executed respecting the order, unless randomizeRuns is set to true
  # Available runs: countess, andariel, ancient_tunnels, summoner, mephisto, council, eldritch, pindleskin, nihlathak,
  #                 tristram, lower_kurast, stony_tomb, pit, arachnid_lair, tal_rasha_tombs, baal, diablo, cows, terror_zone
  # leveling: there is a "leveling" run, in combination with "sorceress or paladin" class will be able to start leveling character from level 1 (don't expect too much)
  # terror_zone: will detect current TZ and clear it
  runs: [stony_tomb, pit, arachnid_lair]

  # Specific runs settings
  pindleskin:
    skipOnImmunities: [ ] # Allowed values: cold, fire, light, poison
  mephisto:
    killCouncilMembers: true # Will kill the council members after killing Mephisto
    openChests: true # Will open chests after killing Mephisto
  tristram:
    focusOnElitePacks: false # Will clear only Elite monsters
    clearPortal: true # Kills Rakanishu and makes easier selecting the portal
  nihlathak:
    clearArea: true
  baal:
    killBaal: false
  terrorZone:
    focusOnElitePacks: false # Will clear only Elite monsters
    skipOnImmunities: [ ] # Allowed values: cold, fire, light, poison
    skipOtherRuns: false # If current TZ is allowed, will skip other runs and only do TZ instead
    areas:
      - 2 # Blood Moor
      - 8 # Den of Evil
      - 3 # Cold Plains
      - 9 # Cave Level 1
      - 10 # Cave Level 2
      - 12 # Pit Level 1 (Will do Pit run)
      - 17 # Burial Grounds
      - 18 # Crypt
      - 19 # Mausoleum
      - 4 # Stony Field
      - 5 # Dark Wood
      - 10 # Underground Passage Level 1
      - 14 # Underground Passage Level 2
      - 6 # Black Marsh
      - 11 # Hole Level 1
      - 15 # Hole Level 2
      - 20 # Forgotten Tower (Will do Countess run)
      - 29 # Jail Level 1
      - 30 # Jail Level 2
      - 31 # Jail Level 3
      - 32 # Inner Cloister
      - 33 # Cathedral
      - 34 # Catacombs Level 1
      - 35 # Catacombs Level 2
      - 36 # Catacombs Level 3
      - 38 # Tristram (Will do Tristram run)
      - 39 # Moo Moo Farm (Will do Cows run)
      - 41 # Rocky Waste (Will do Stony Tomb run)
      - 47 # Sewers Level 1
      - 48 # Sewers Level 2
      - 49 # Sewers Level 3
      - 42 # Dry Hills
      - 56 # Halls of the Dead Level 1
      - 57 # Halls of the Dead Level 2
      - 60 # Halls of the Dead Level 3
      - 43 # Far Oasis
      - 44 # Lost City
      - 45 # Valley of Snakes
      - 58 # Claw Viper Temple Level 1
      - 61 # Claw Viper Temple Level 2
      - 65 # Ancient Tunnels (Will do Ancient Tunnels run)
      - 66 # Tal Rasha's Tomb 1 (Will do Tal Rasha Tombs run)
      - 74 # Arcane Sanctuary (Will do Summoner run)
      - 76 # Spider Forest
      - 85 # Spider Cavern
      - 83 # Travincal (Will do Council run)
      - 77 # Great Marsh
      - 78 # Flayer Jungle
      - 88 # Flayer Dungeon Level 1
      - 89 # Flayer Dungeon Level 2
      - 91 # Flayer Dungeon Level 3
      - 80 # Kurast Bazaar
      - 94 # Ruined Temple
      - 95 # Disused Fane
      - 100 # Durance of Hate Level 1 (Will do Mephisto run)
      - 104 # Outer Steppes
      - 105 # Plains of Despair
      - 106 # City of the Damned
      - 107 # River of Flame
      - 108 # Chaos Sanctuary (Will do Diablo run)
      - 110 # Bloody Foothills
      - 111 # Frigid Highlands
      - 125 # Abaddon
      - 115 # Glacial Trail
      - 116 # Drifter Cavern
      - 113 # Crystalline Passage
      - 114 # Frozen River
      - 112 # Arreat Plateau
      - 126 # Pit of Acheron
      - 118 # The Ancients' Way
      - 119 # Icy Cellar
      - 121 # Nihlathak's Temple (Will do Nihlathak run)
      - 128 # The Worldstone Keep Level 1 (Will do Baal run)

companion:
  enabled: false
  leader: true
  leaderName: ''
  remote: discord # Only discord supported, telegram doesn't allow interacting between bots
  gameNameTemplate:

# Gambling settings. If enabled, bot will start gambling when all the gold stash tabs are full.
# While gold > 500k it will iterate over the items list trying to buy one of each item type.
# Item filtering will be done via the same pickup configuration, discarded items will be sold to vendor
gambling:
  enabled: true # If gambling is disabled, bot will stop picking up gold when can not carry more
  items: [ coronet, amulet, ring ] # Items to gamble, same value as [name] in pickit files.
