### ISSUE TITLE
Frigid Highlands waypoint unable to be used/not found

### ISSUE THREAD

**Issue by Millionaar** [hectorgimenez/koolo#61]
When running Eldritch it thinks I am missing the Frigid Highlands waypoint, so it teleports or walks to Eldritch instead of using the waypoint. When it gets there it tries to trigger the waypoint so it definitely thinks I don't have it.

Anyone else have this issue? All other runs I've tried work fine, both with sorceress or hammerdin without teleport.

**Version**
I'm running the latest version [v0.3.2] and have not compiled it from source.

**My best guess:**
Seems odd that it's just this Waypoint, so maybe the coordinates of that first row of waypoints isn't quite right?
Looking at my logs below, the color matching operating score of 76.42276422764228 is also what shows up when leveling, i.e. time to find Baal for the first time, it doesn't have the waypoint, and returns that number.
So it seems like it is correctly matching a waypoint, but one that is blank. So it's possible matching the wrong waypoint or something?

Happy to be pointed in the right direction of the code to try and test myself.

**Log Extract**
From back in December but issue still exists on a newer install.

2023-12-14T22:49:02.051+1300    DEBUG   action/stash.go:28      Checking for items to stash...
2023-12-14T22:49:02.052+1300    DEBUG   action/stash.go:30      No items to stash...
2023-12-14T22:49:08.345+1300    DEBUG   ui/template_finder.go:130       Color matching operation        {"score": 73.98373983739837}
2023-12-14T22:49:08.346+1300    DEBUG   ui/template_finder.go:130       Color matching operation        {"score": 76.42276422764228}
2023-12-14T22:49:08.346+1300    INFO    action/waypoint.go:99   Traversing areas to reach destination   {"areas": [109,110,111]}

**Comment by hectorgimenez** [comment]
First score is 73.98 and the threshold is set at 75, it might be the reason. I need to update the WP detector to read the available WP from memory instead of using UI matching, I hope I have some time within the next weeks to do it.

**Comment by hectorgimenez** [comment]
@Millionaar give it a try to the latest release

**Comment by Millionaar** [comment]
Thank you all fixed. Only just had the chance to test but appreciate the quick fix!
