### ISSUE TITLE
Option to skip chest (LK, Cows)

### ISSUE THREAD

**Issue by willzxp** [hectorgimenez/koolo#67]
Hello are there any ways to NOT open any chest in cows and LK? I never have keys and there are no options to turn off this option. It will keep trying to open a lock chest before ending the game.

**Comment by Millionaar** [comment]
Not a solution, but my workaround is to have a set of keys in inventory and use your config to lock that slot. Problem is you have to try pick up keys to refill, so it will often have a second inventory slot of keys before selling that unlocked slot of them.
Gets the bot working in thsoe areas in the meantime though.

**Comment by willzxp** [comment]
Yes that works for me! I also see that it auto buys and refills keys from akara act 1 using this method
