### ISSUE TITLE
Koolo.exe auto closes

### ISSUE THREAD

**Issue by willzxp** [hectorgimenez/koolo#70]
Was running fine for a week. Paused and shut down this morning to check stash. Then tried to run the bot up again to no prevail.

Right click Koolo.exe run as administrator and it opens for a millisecond then automatically closes the CMD. Please help!

**Comment by Millionaar** [comment]
Most likely something wrong in your config file. Try running it with an older version of your config or a freshly downloaded one.
Any small typo has caused that for me.

**Comment by willzxp** [comment]
Narrowed the issue down to rare pickit. If i delete the // in front of the rare circlets, the CMD refuses to run and auto closes.

**Comment by hectorgimenez** [comment]
maybe wrong syntax? share the line causing the crash

**Comment by willzxp** [comment]
So if I delete the // in front of [type] for all 3 lines, koolo.exe refuses to open and run.


// rare circlets
                                                                                                                                                 //[type] == circlet 		&& [quality] == rare && [flag] != ethereal # [sockets] >= 2 && [itemaddclassskills] >= 2 && [fcr] >= 20 && ([dexterity]+[strength] >= 10 || [maxhp] >= 20) && (([itemtohitpercentperlevel] >= 1) || ([dexterity]+[strength] >= 20) || ([maxhp] >= 35) || ([enhanceddamage] >= 15) || ([fhr] >= 10) || ([frw] >= 30) || ([coldresist]+[fireresist]+[lightresist]+[poisonresist] >= 40))
                                                                                                                                                 //[type] == circlet 		&& [quality] == rare && [flag] != ethereal # [sockets] >= 2 && [amazonskills] >= 2 	   && [frw] >= 30 && ([dexterity]+[strength] >= 10 || [maxhp] >= 20) && (([itemtohitpercentperlevel] >= 1) || ([dexterity]+[strength] >= 20) || ([maxhp] >= 35) || ([enhanceddamage] >= 15) || ([fhr] >= 10) || ([fcr] >= 20) || ([coldresist]+[fireresist]+[lightresist]+[poisonresist] >= 40))
                                                                                                                                                 //[type] == circlet 		&& [quality] == rare && [flag] != ethereal # [sockets] >= 2 && [paladinskills] >= 2 	   && [itemtohitpercentperlevel] >= 1 && (([dexterity]+[strength] >= 10) + ([dexterity]+[strength] >= 20) + ([maxhp] >= 20) + ([maxhp] >= 35) + ([enhanceddamage] >= 15) + ([fhr] >= 10) + ([frw] >= 30) + ([fcr] >= 20) + ([coldresist]+[fireresist]+[lightresist]+[poisonresist] >= 40)) >= 2
