### ISSUE TITLE
Koolo - stash/vendor repeats

### ISSUE THREAD

**Issue by owenhope** [hectorgimenez/koolo#74]
I have everything running, but on 1280x720 when viewing tabs and making vendor purchases everything is slightly off (by about 2 vertical grid squares)

For isntance in stash it misses the gold button to the left by about 1 inch, the tabs in the stash by about 1 inch and then going to malah it misses clicking her. When we buy off Atma in act 1, it says buying Health Pots, but it selects the stamina pot in the top left.

Any suggestions? My monitor is 2560x1440 and im not touching anything once the game starts.

I could make a video if that's easier.

**Comment by divuslol** [comment]
Got the same problem here, any solutions yet?

**Comment by BrandtNick** [comment]
Same here, tried a lot of different resolutions on both game and monitor.

**Comment by hectorgimenez** [comment]
Could you try with latest 0.4.0 beta version?

**Comment by BrandtNick** [comment]
> Could you try with latest 0.4.0 beta version?

Tried it, it had a few bugs still:

- Eldritch it just goes to the wp and probably tries to go to frigid but doesnt happen and it says run finished and goes next after like 5-6  seconds.
- Tried Pindleskin run and it seemed to work until it found items and on the next run it picked up one item and just hovered it in the air and mouse moved around (maybe I missed some setting?).
- Tried Mephisto, worked well until game after when it was gonna stash, it went to the stash then it looked like it accidently closed the stash and just ran around and said stash was full

Tried mostly 1280x720 and one try on 1920x1080 that didnt work either.

But the fact that it runs and I can move around with my mouse and do whatever is really cool man, gj! Looks really promising this.

**Comment by hectorgimenez** [comment]
I will close this, feel free to open a new issue if you find new bugs
