### ISSUE TITLE
Request: Implementation of a follower functionality

### ISSUE THREAD

**Issue by githubpersttn** [hectorgimenez/koolo#75]
Hello,

Great work here!

Looking at the companion functionality it made me thinking why not to implement a "follower" functionality which will be a simplified version of the companion.

The use case is when you have D2R in e.g. virtual machines and you want your other accounts to follow you. This could be a party with you main character being a blizz sorc but other accounts are a summoner(s) and paladins.

The minimal implementation is just to follow your leader, changing the areas as well. A little bit more advanced could be joining the game, entering a portal, using a portal to enter a city. In the most advanced case an attack sequence can be added, but that's probably not important. As long as e.g. a summoner and a pala follows you it's enough.

This functionality will be useful for people who want to plain in a solo party or during new ladders.

Regards

**Comment by hectorgimenez** [comment]
It's a good point and I will lie if I say I've been not thinking about it many times, it could be good to implement it but I don't think I have enough time for it. Let's keep it in the wishlist, for now I'm focusing on making it less invasive so we can run it without VM and keep using the computer. (or tu run multiple instances in one single VM)

**Comment by 13413j1j13j5315n13** [comment]
With such as massive change recently, this is not relevant per se anymore. Will open a new ticket later if needed
