### ISSUE TITLE
Stuck on Chests

### ISSUE THREAD

**Issue by owenhope** [hectorgimenez/koolo#78]
<img width="920" alt="Screenshot 2024-02-22 at 11 47 52 AM" src="https://github.com/hectorgimenez/koolo/assets/6454237/e45bbf70-19d5-4448-b0c7-234b5c2c3944">

Any idea how to make it so we don't get stuck on locked chests?

Love it so far!

**Comment by hectorgimenez** [comment]
Good catch, let's add a check to be sure character has keys if the chest is locked

**Comment by Elanoran** [comment]
Adding keys to the picit should fix this issue:

`[Name] == Key # # [MaxQuantity] == 12`

**Comment by willzxp** [comment]
My simple fix was to buy 1 key or 12 keys. The bot will auto buy more keys according to my test runs
