### ISSUE TITLE
Can you tell me the manual for execution in detail?

### ISSUE THREAD

**Issue by s2wgood** [hectorgimenez/koolo#85]
I've used up all of my day to run the program, but I ended up failing. I installed Diablo 2 LOD, but the version was 1.14b, is this an issue?? I don't even know what options I should put into something like I should put an option to run koolo-map.exe. I read and read the manual you wrote nearly 100 times, but I couldn't solve it, so I wrote so much.

**Comment by jstnmthw** [comment]
Try using [D2VersionChanger](https://github.com/ChaosMarc/D2VersionChanger) which worked for me. You can also use the downloaded version from Blizzard (by running the [mpq fix](https://github.com/ChaosMarc/D2VersionChanger/tree/master/VersionChanger/MPQFix)).
