### ISSUE TITLE
pickit and inventory full

### ISSUE THREAD

**Issue by Aivenn85** [hectorgimenez/koolo#86]
Having an issue with pickit still picking up items I've commented out. 
I commented out everything which I'm not interested in which is basically all magic /rare items and most of the set/unique/white items. Only looking for a handful of items basically just to see what I can find. I noticed the bot is still picking up any and every rare/magic item it finds regardless of the nip files.

Also when it picks up a bunch of items and the inventory gets full it'll just sit there casting telekinesis until the game time runs out.

**Comment by Millionaar** [comment]
If your gold is below a certain amount I think it overrides it and picks up lots of items to sell. Maybe 500k gold per the gambling section? Could just be that.
Unsure on the full inventory issue though, haven't run into that with telekinesis.

**Comment by Aivenn85** [comment]
I have gambling set to false and I'm well over 500k in the stash atm. So far it seems to be running really well for Andy runs outside of the inventory full issue and picket problem. I'd like to try cows but it keeps running into an error when it uses the Stony WP.

I think your right about the 500k thing though, Now that I'm well over 500k it seems to be picking up less junk.
