### ISSUE TITLE
bot wont use online tab when starting game

### ISSUE THREAD

**Issue by childofwar1980** [hectorgimenez/koolo#93]
bot auto starts the game and when it reaches the character screen it is in the offline tab and when i stop or pause the bot and try to switch to online tab it says cannot connect to server

**Comment by hectorgimenez** [comment]
Are you entering bnet credentials on the character config file? Check it please

**Comment by childofwar1980** [comment]
I used my username and my email address associated with the account and
also my battletag, tried all those things and same result. Would it help if
I sent a video or screenshots?

**Comment by childofwar1980** [comment]
I was using the previous release just fine but when this release came out
my old release stopped working as well. Not sure if it's related

**Comment by RobotGaston** [comment]
just tested, it's working for me (windows 10 here). You should put your email address and username (not sure about battle tag ) into your config file, which is in the , - main folder-config-character name-config.yaml.

Then press start. It should autologin into ONLINE mode. (Check your realm also in confog.yaml)

First run main.exe. Configure it till the character name is asked. Type it in there. After that go into main folder-config-character name-config.yaml. Put your bnet account in there. Save. Press start in main window. It should start the game and load you into online bnet. It does for me...

**Comment by childofwar1980** [comment]
To confirm the correct realm would be us.actual.battle.net? If I have
selected the Americas as my realm? And email AND my user name? Or one or
the other? The only thing I did not try is the email and user name combined.

**Comment by childofwar1980** [comment]
i re-did everything and it worked this time. im not sure what kind of brain fart i must have had but i must have typed something in wrong and looked at it 20000 times and not noticed the mistake somehow. ty very much for your great work and your swift response. :)

**Comment by RobotGaston** [comment]
yes, correct , if you using us realm it should be us.actual.battle.net.
you put into confing.yaml in the string username: '---here---your---email--which--is--a-login-to-bnet-account'
and into password: '---here---you--put---the--password--of--our--bnetaccount'

if this still not working, try to reconfigure everything from the clean start - delete folder with tool, redownload fresh and reconfigure again...
