### ISSUE TITLE
cannot stash items

### ISSUE THREAD

**Issue by childofwar1980** [hectorgimenez/koolo#94]
bot starts fine and enters game and will run andarial but when the run is over the bot will try to stash item and leave the stash screen and run around and quit the game then re-enter and do the same thing on a loop. also unable to use merchant correctly. i thought it might be the resolution and and dpi and scaling settings but after trying every combination i get the same results. this was not an issue with the previous build.

**Comment by hectorgimenez** [comment]
Interesting... what windows version are you using?

**Comment by childofwar1980** [comment]
windows 10 pro

**Comment by childofwar1980** [comment]
its the weirdest thing i should send a video because its hard to explain

**Comment by childofwar1980** [comment]
can only attache 10 mb files to this site i have a video and if you want it i can send it to you. let me know if you want it and where to send it

**Comment by childofwar1980** [comment]
i also noticed that the log files are empty, just blank pages

**Comment by hectorgimenez** [comment]
> can only attache 10 mb files to this site i have a video and if you want it i can send it to you. let me know if you want it and where to send it

You can upload it in youtube and make it available via direct link only, so you dont have any restriction

**Comment by globusV1** [comment]
its the problem of click positions
when bot trying to stash - it try to click on stash tab and with wrong positions its starts running
the problems same in stash, at vendor, at repair

i build from sources and change all click positions - and bot works perfect

**Comment by childofwar1980** [comment]
https://youtu.be/esFrD1jyfsA

**Comment by childofwar1980** [comment]
> its the problem of click positions when bot trying to stash - it try to click on stash tab and with wrong positions its starts running the problems same in stash, at vendor, at repair
> 
> i build from sources and change all click positions - and bot works perfect

how would i know how to adjust click positions if i cant see where its clicking? i will try to build from source and see what i can do ty :)

**Comment by childofwar1980** [comment]
> its the problem of click positions when bot trying to stash - it try to click on stash tab and with wrong positions its starts running the problems same in stash, at vendor, at repair
> 
> i build from sources and change all click positions - and bot works perfect

how do i change click positions? i am new to this but i can figure it out with a little direction

**Comment by hectorgimenez** [comment]
I can not see the video, maybe you should make it public visible only with the link or something

**Comment by globusV1** [comment]
> > its the problem of click positions when bot trying to stash - it try to click on stash tab and with wrong positions its starts running the problems same in stash, at vendor, at repair
> > i build from sources and change all click positions - and bot works perfect
> 
> how do i change click positions? i am new to this but i can figure it out with a little direction

using this - to get click position
https://github.com/Bluegrams/MPos?tab=readme-ov-file

tabs coords
https://github.com/hectorgimenez/koolo/blob/main/internal/action/stash.go
func (b *Builder) switchTab(tab int) {
	x := 107
	y := 128
	tabSize := 82
	x = x + tabSize*tab - tabSize/2

	b.HID.Click(game.LeftButton, x, y)
	helper.Sleep(500)
}


https://github.com/hectorgimenez/koolo/blob/763c2f5d52f86a483e3f27f682e116d8325a7cb2/internal/ui/coordinates.go#L42
Inventory cell coords
inventoryTopLeftX = 846
inventoryTopLeftY = 369
vendor cell coords 
topCornerVendorWindowX = 109
topCornerVendorWindowY = 147



for example this code is working perfect for me

func (b *Builder) switchTab(tab int) {
	x := 75
	y := 75
	tabSize := 100
	x = x + tabSize*(tab-1)

	b.HID.Click(game.LeftButton, x, y)
	helper.Sleep(500)
}

**Comment by childofwar1980** [comment]
Perfect Ty very much I'll tinker and see what I can do

**Comment by childofwar1980** [comment]
Can you send me your waypoint.go coords? It's having trouble with waypoints
as well

**Comment by childofwar1980** [comment]
> I can not see the video, maybe you should make it public visible only with the link or something
i made it public now sorry

**Comment by childofwar1980** [comment]
> > > its the problem of click positions when bot trying to stash - it try to click on stash tab and with wrong positions its starts running the problems same in stash, at vendor, at repair
> > > i build from sources and change all click positions - and bot works perfect
> > 
> > 
> > how do i change click positions? i am new to this but i can figure it out with a little direction
> 
> using this - to get click position https://github.com/Bluegrams/MPos?tab=readme-ov-file
> 
> tabs coords https://github.com/hectorgimenez/koolo/blob/main/internal/action/stash.go
> 
> ```
> func (b *Builder) switchTab(tab int) {
> 	x := 107
> 	y := 128
> 	tabSize := 82
> 	x = x + tabSize*tab - tabSize/2
> 
> 	b.HID.Click(game.LeftButton, x, y)
> 	helper.Sleep(500)
> }
> ```
> 
> https://github.com/hectorgimenez/koolo/blob/763c2f5d52f86a483e3f27f682e116d8325a7cb2/internal/ui/coordinates.go#L42
> 
> Inventory cell coords
> 
> ```
> inventoryTopLeftX = 846
> inventoryTopLeftY = 369
> ```
> 
> vendor cell coords
> 
> ```
> topCornerVendorWindowX = 109
> topCornerVendorWindowY = 147
> ```
> 
> windowed mode 1280x720 for example this code is working perfect for me but the default one is just opening stash and running
> 
> ```
> func (b *Builder) switchTab(tab int) {
> 	x := 75
> 	y := 75
> 	tabSize := 100
> 	x = x + tabSize*(tab-1)
> 
> 	b.HID.Click(game.LeftButton, x, y)
> 	helper.Sleep(500)
> }
> ```

i just tried your coords and still not working and i am running at the same resolution. im not sure why this problem is happening as i said i had it working fine on previous build

**Comment by globusV1** [comment]
do u play in windowed mode or in full screen?

**Comment by childofwar1980** [comment]
> do u play in windowed mode or in full screen?

ive tried both and previous release worked on both

**Comment by Sunnyweeb** [comment]
in an other thread mentioned: dont activate "large font mode" it messes around with your inventory/stash/vendor invetentory and all that. deactivate it under options > gameplay > section: "accessibility" and then deactivate "large font mode", that should fix it.

**Comment by childofwar1980** [comment]
> in an other thread mentioned: dont activate "large font mode" it messes around with your inventory/stash/vendor inventory (it makes it smaller) and all that. deactivate it under options > gameplay > section: "accessibility" and then deactivate "large font mode", that should fix it.
> 
> note: i think it would be nice to mention it on the "quickstart guide" bc you are the 3 or 4 person with that exact problem

oh my good lord that worked!!!! after everything i tried it was such a silly little thing i overlooked. thank you sooooo much you are god tier :)

**Comment by childofwar1980** [comment]
ty very much for all the great help and suggestions it turns out it was the large font mode that was the issue and the problem is now resolved.
