### ISSUE TITLE
bot clicking issue

### ISSUE THREAD

**Issue by childofwar1980** [hectorgimenez/koolo#96]
bot logs in and joins game perfectly but it seems like there is some kind of scaling or window size issue that is causing the bot to fail i have tried every possible dpi and scaling setting i can think of and ran it windowed and fullscreen at both 720p and 1080p resolutions with every combination of scaling settings in both windows and nvidia settings. what is the best system set up to get this to work?

**Comment by hectorgimenez** [comment]
I'm using 4k with 150% scale factor in Windows and running the game at 1920x1080

**Comment by jstnmthw** [comment]
@childofwar1980 Make sure you set default legacy keybindings. I had custom bindings and it wasn't working.

**Comment by childofwar1980** [comment]
Ty for the tip but yeah I am set to legacy I thought that might be it too
but no luck

**Comment by hectorgimenez** [comment]
Try with latest beta 3 release, check your Windows settings to check your display scale, and run the game according to that. The tool is designed to run in windowed mode at 1280x720, so if your scale is 150%, then you should set the game to 1920x1080. If 200% then 2560x1440, etc...

**Comment by childofwar1980** [comment]
ty very much for all the great help and suggestions it turns out it was the large font mode that was the issue and the problem is now resolved.
